"""General teaching algorithms for PythonReview coding solutions.

Step 1 is always a layman “what is the problem / how we solve it” line.
Later steps are the how-to. Matching `# Step N:` comments live in the .py files.
"""

ALGORITHMS: dict[str, list[str]] = {
    "Q1.1": [
        "A hospital stay costs money each day. We multiply days by the daily room price, take off an insurance discount if they have it, and show the final bill.",
        "Validate that money and day inputs are usable (non-negative).",
        "Calculate the stay subtotal from daily charge × days.",
        "If insurance applies, compute a 20% discount; otherwise use zero discount.",
        "Subtract the discount and round money to two decimal places.",
        "Return patient details together with subtotal, discount, and final amount.",
    ],
    "Q1.3": [
        "Medicines must be taken at different times. We put each medicine into a “box” labeled with its time, so we can quickly see what to take at 8:00 or add/remove one later.",
        "Maintain a schedule of medication times and their corresponding medicines using a dictionary.",
        "Create an empty dictionary called schedule.",
        "Read each (medicine, time) from the input list.",
        "If the time is not already present in schedule, create a new empty list for that time.",
        "Add the medicine to the list for the corresponding time.",
        "Repeat Steps 4–6 until all medications have been processed.",
        "To add a medication later: if the time is missing, create its list; then append the medicine.",
        "To remove a medication: if the time exists and the medicine is present, remove it; if the list becomes empty, delete that time from schedule.",
        "To get medications for a specific time: if the time exists, return its list; otherwise return an empty list.",
        "Return the final medication schedule.",
    ],
    "Q1.5": [
        "We have several days of blood pressure, temperature, and dates. We want simple summaries: average pressures, the hottest temperature, and the first-to-last date range.",
        "Require at least one vital-sign reading.",
        "Separate the readings into columns: systolic, diastolic, temperature, and date.",
        "Compute average systolic and average diastolic.",
        "Find the highest temperature.",
        "Find the earliest and latest dates.",
        "Return averages, max temperature, and the date range as one result.",
    ],
    "Q1.8": [
        "Think of a filing cabinet: each patient gets one folder (by id) with personal info, medical info, and visits. We add folders, update them, and search by blood type.",
        "Keep patient records in a dictionary keyed by patient id.",
        "To add a patient: reject duplicates, then store personal, medical, and an empty visits list.",
        "To update a patient: merge the new fields into the existing record.",
        "To search by blood type: collect ids whose medical blood type matches.",
        "To get visit history: return a copy of that patient’s visits.",
    ],
    "Q1.11": [
        "Before giving a new medicine, check if it fights with medicines the patient already takes. We look up known bad pairs and see if any of those partners are already on the list.",
        "Normalize medication names so comparisons are case-insensitive.",
        "Look up interaction partners for the new medication.",
        "Find the overlap between current medications and those partners.",
        "Mark the prescription safe only when there is no overlap.",
        "Return safety, the conflict set, and a short recommendation.",
    ],
    "Q2.1": [
        "Before we trust patient data, we check the basics: id and age look okay, blood type is a real choice, vitals are present and inside safe ranges, and emergency contact has name and phone if given.",
        "Reject invalid identity inputs (blank id, age out of range, wrong blood-type type, empty vitals).",
        "If an emergency contact is provided, require both name and phone.",
        "Check every vital-sign reading against allowed ranges.",
        "Return True only when all checks pass; otherwise False.",
    ],
    "Q3.1": [
        "We calculate BMI from weight and height, maybe lower the medicine dose for older patients, figure out how many days a bottle lasts, and say if BMI looks healthy.",
        "Reject non-positive height or dosage.",
        "Calculate BMI from weight and height.",
        "Reduce dosage for patients over 65; otherwise keep the base dosage.",
        "Estimate days of supply from a fixed total amount ÷ dosage.",
        "Flag whether BMI falls in the healthy range.",
        "Return BMI, adjusted dosage, days supply, and the healthy flag.",
    ],
    "Q3.2": [
        "Like a traffic light for sick patients: check the scariest warning signs first (Critical), then medium ones (Urgent), otherwise they are Standard.",
        "Read systolic and diastolic from the blood-pressure pair.",
        "If any critical rule matches, return Critical.",
        "Else if any urgent rule matches, return Urgent.",
        "Otherwise return Standard.",
    ],
    "Q3.3": [
        "Permissions are like light switches: Read, Write, Delete. We flip switches on or off, and we can ask “is this switch on?”",
        "Represent each permission as a distinct bit flag.",
        "Store the current permissions as one integer.",
        "To grant a permission: turn its bit on.",
        "To revoke a permission: turn its bit off.",
        "To check a permission: test whether the required bits are set.",
    ],
    "Q3.4": [
        "We answer four yes/no questions: scary symptoms? accepted insurance? bad history conflict? was history given at all? We do that by checking overlaps with known lists.",
        "Define the reference sets: critical symptoms, accepted insurers, conflicting history.",
        "Convert symptoms and history into sets (treat missing history as empty for comparison).",
        "Detect overlap with critical symptoms.",
        "Detect overlap with accepted insurance.",
        "Detect overlap with conflicting history.",
        "Record whether history was provided at all (None vs a list).",
        "Return the four boolean results.",
    ],
    "Q3.5": [
        "Walk through each patient once. While looking, note problems (high BMI, fever, too many medicines). Keep only the patients who got at least one note.",
        "Prepare an empty results list.",
        "For each patient, start an empty flags list.",
        "Compute BMI and flag obesity when BMI is above 30.",
        "Read temperature and flag fever when it is high enough.",
        "Count medications and flag polypharmacy when the count is large.",
        "If any flags exist, keep that patient’s id and flags.",
        "Return only the flagged patients.",
    ],
    "Q4.1": [
        "Decide what to do in order of urgency: emergencies first, then long-term issues, then common colds, else “need more tests.” Extra helpers make check-in messages and medicine reminder lines.",
        "Check emergency conditions first and return immediately if they match.",
        "Else check chronic indicators and return if they match.",
        "Else check common-ailment indicators and return if they match.",
        "Otherwise return a default “further testing” result.",
        "For monitoring: emit a status message every fixed time interval.",
        "For daily schedule: flatten each time → drug list into take instructions.",
    ],
    "Q5.1": [
        "From a pile of patient cards, pull out different views: who has diabetes, each person’s latest vitals, every unique medicine, and a “high risk” list we can walk one-by-one.",
        "Build a list of patient ids that have diabetes.",
        "Build a dictionary of each patient’s latest vital reading.",
        "Build a set of all unique medications across patients.",
        "Create a generator that yields high-risk patient ids.",
        "Return the list, dictionary, set, and generator together.",
    ],
    "Q6.1": [
        "Booking a visit needs patient and doctor for sure; extra details and options are optional bags we pack along. Updating a record also has strict rules about which arguments are required how.",
        "Require patient id and doctor id.",
        "Collect any extra positional appointment details.",
        "Collect any keyword scheduling options.",
        "For updates: require patient id positionally; allow optional name/age; require blood type / emergency contact as keywords only.",
        "Return structured dictionaries for both operations.",
    ],
    "Q6.2": [
        "Family risk is like climbing a family tree: if someone has the condition, add a score that gets smaller the farther up you go. Drug interactions are like following “friends of friends” without visiting the same person twice.",
        "Track visited people/drugs so recursion does not loop forever.",
        "Stop with zero (or empty) when the current node is missing or already visited.",
        "Score the current person if they have the condition, scaled by generation.",
        "Add scores from each parent by recursing one generation deeper.",
        "For drug interactions: take direct neighbors, then recursively union their neighbors.",
        "Return the accumulated score or interaction set.",
    ],
    "Q6.3": [
        "Each lab test has a “normal” window. We measure how far outside that window a value is, list the bad ones, score them, and sort the worst first.",
        "Define how far a lab value sits outside its normal range (0 if inside).",
        "Filter the rows that are outside range.",
        "Map each row to a severity score.",
        "Sort all rows by severity (worst first).",
        "Return abnormal rows, scores, and the priority order.",
    ],
    "Q6.4": [
        "The hospital has shared settings on a notice board (global). Nested helpers can read that board, and one helper is allowed to update a number on it after checking it is valid.",
        "Keep shared hospital settings in a module-level configuration.",
        "Inside a factory function, define a helper that reads capacity from that configuration.",
        "Choose doctor type from severity while reading the shared capacity.",
        "Define a helper that updates the shared capacity after validating the new limit.",
        "Return both helpers so callers can use them.",
    ],
    "Q7.1": [
        "We use Python’s built-in tools like a toolbox: pull ages, filter older patients, pair records with labs, sort by risk, and compute simple min/max stats.",
        "Extract ages with map; filter elderly patients.",
        "Use reduce to find the patient with the most medications.",
        "Pair records with labs using zip; number patients with enumerate.",
        "Sort patients by risk-related keys.",
        "Compute simple statistics with min and max.",
        "Record types with type(), and build time slots with range().",
        "Return all analysis pieces in one dictionary.",
    ],
    "Q8.1": [
        "Build a tiny hospital app: store patients, add them carefully, attach vitals, print a filtered report, and run a list of jobs on the whole system.",
        "Initialize an empty patient store.",
        "Add a patient only when id is a non-empty string and not already present.",
        "Append vitals using variable positional values plus optional metadata.",
        "Generate a report by yielding patients that pass an optional filter.",
        "Run a batch of operations against the system and collect their results.",
    ],
}
