"""Kid-friendly HTML model answers for PythonReview slides.

Rendered in a white .model-answer box (bold + paragraphs).
"""

KID_ANSWERS: dict[str, str] = {
    "Q1.1": (
        "<p>A hospital stay bill is like a shopping receipt for days in a room.</p>"
        "<p><b>Step 1:</b> Check that money and days are not negative "
        "(you cannot stay −3 days).</p>"
        "<p><b>Step 2:</b> Multiply <b>room charge × days</b> → that is the "
        "<b>subtotal</b>.</p>"
        "<p><b>Step 3:</b> If the patient has <b>insurance</b>, take off "
        "<b>20%</b> (keep only 80%). If not, charge the full subtotal.</p>"
        "<p><b>Step 4:</b> Put the answer in a <b>dictionary</b> with clear names "
        "(patient name, amount, etc.).</p>"
        "<p>For real money, prefer Decimal (<b>exact decimal arithmetic</b>) "
        "instead of plain <code>float</code>, because float can be a tiny bit wrong:</p>"
        "<div class=\"step-pre\">from decimal import Decimal, ROUND_HALF_UP\n\n"
        "print(0.1 + 0.2)                    # float — can look odd\n"
        "print(Decimal(\"0.1\") + Decimal(\"0.2\"))  # Decimal(\"0.3\") — exact\n\n"
        "subtotal = Decimal(\"350.00\") * 3\n"
        "final = (subtotal * Decimal(\"0.80\")).quantize(\n"
        "    Decimal(\"0.01\"), rounding=ROUND_HALF_UP\n"
        ")  # money rounded to 2 places</div>"
        "<table class=\"data-tbl\">"
        "<tr><th></th><th><code>float</code></th><th><code>Decimal</code></th></tr>"
        "<tr><td>Good for</td><td>Science / graphics</td><td><b>Money / bills</b></td></tr>"
        "<tr><td>Exact cents?</td><td>Not always</td><td>Yes, when you set precision</td></tr>"
        "</table>"
    ),
    "Q1.2": (
        "<p>Think of an ID as a <b>name tag</b> for a patient.</p>"
        "<p>An <b>integer</b> ID like <code>12345</code> stores a number. "
        "In Python it is a whole object — about <b>28 bytes</b> "
        "(not 4 bytes like C# <code>int</code>).</p>"
        "<p>A <b>string</b> ID like <code>\"P12345\"</code> stores letters and digits. "
        "It needs more space — about <b>47 bytes</b> — because each character "
        "takes room plus string overhead.</p>"
        "<p><b>Use int</b> for internal database keys (fast, small).<br>"
        "<b>Use str</b> when you need prefixes like <code>P</code> or leading zeros.</p>"
        "<p>Best design: keep <b>both</b> — a secret internal number for the computer, "
        "and a public string for badges and labels. A string ID is <b>not</b> a password.</p>"
    ),
    "Q1.3": (
        "<p>Imagine medicine times as <b>labeled boxes</b> on a shelf.</p>"
        "<p>The <b>time</b> (like <code>\"8:00\"</code>) is the box label. "
        "Inside each box is a <b>list of medicines</b> due at that time.</p>"
        "<p>In Python that is a <b>dictionary</b>: "
        "<code>{ \"8:00\": [\"Aspirin\", \"Insulin\"], ... }</code>.</p>"
        "<p>When you add a medicine: find the time box (or make a new empty list), "
        "then <b>append</b> the medicine name.</p>"
        "<p>When you remove the last medicine from a time, <b>delete that empty box</b> "
        "so the shelf stays tidy.</p>"
        "<p>When someone asks “what is due at 8:00?”, return a <b>copy</b> of the list "
        "so they cannot accidentally mess up your real schedule.</p>"
    ),
    "Q1.4": (
        "<p>Think of a Python <b>list</b> like a <b>row of seats</b> in a waiting room.</p>"
        "<p>Each seat holds one <b>patient card</b>.</p>"
        "<p><b>Adding at the END</b> (<code>append</code>) is easy — "
        "they sit in the next empty seat.<br>"
        "That is usually very fast (<b>amortized O(1)</b>).</p>"
        "<p><b>Adding at the FRONT</b> (<code>insert(0, …)</code>) is hard — "
        "everyone already seated must stand up and move one seat back to make room.<br>"
        "With <b>10,000</b> people, that is a lot of moving (<b>O(n)</b>).</p>"
        "<p><b>Java ArrayList</b> works the same way: both are <b>dynamic arrays</b> "
        "(a row of seats that can grow).</p>"
        "<p>Yes — Python has a deque (<b>double-ended queue</b>) in the "
        "<code>collections</code> module. It is not a built-in like <code>list</code>, "
        "but it is in the standard library:</p>"
        "<div class=\"step-pre\">from collections import deque\n\n"
        "triage = deque()\n"
        "triage.append(\"Patient A\")   # add at the end — fast\n"
        "triage.append(\"Patient B\")\n"
        "next_up = triage.popleft()   # take from the front — also fast</div>"
        "<table class=\"data-tbl\">"
        "<tr><th></th><th><code>list</code></th><th><code>deque</code></th></tr>"
        "<tr><td>Add/remove at <b>end</b></td><td>Fast</td><td>Fast</td></tr>"
        "<tr><td>Add/remove at <b>front</b></td>"
        "<td>Slow (<code>insert(0)</code> / <code>pop(0)</code>)</td>"
        "<td>Fast (<code>appendleft</code> / <code>popleft</code>)</td></tr>"
        "<tr><td>Best for</td><td>General lists, random index access</td>"
        "<td>Queues (first-in, first-out)</td></tr>"
        "</table>"
        "<p>For a real hospital waiting line: use <code>collections.deque</code>, "
        "not a plain list — it is built for <b>fast add/remove at both ends</b>, "
        "like two doors on a line.</p>"
    ),
    "Q1.5": (
        "<p>Vital signs are like daily <b>report cards</b>: blood pressure, temperature, date.</p>"
        "<p>First: if the pile of readings is <b>empty</b>, stop — you cannot average nothing.</p>"
        "<p>Then open each card and pull out the numbers you need "
        "(systolic, diastolic, temperature, date).</p>"
        "<p>Compute <b>averages</b>, find the <b>highest temperature</b>, "
        "and note the <b>first and last dates</b>.</p>"
        "<p>Pack the final report into a <b>tuple</b> — like sealing an envelope — "
        "so the snapshot does not change by accident.</p>"
    ),
    "Q1.6": (
        "<p>In Python, <b>parentheses alone do not make a tuple</b>.</p>"
        "<p><code>(98.6)</code> is just grouping — like saying “the number 98.6”. "
        "Its type is still a <b>float</b>.</p>"
        "<p><code>(98.6,)</code> has a <b>comma</b>. The comma is the magic that says "
        "“this is a one-item box (tuple).”</p>"
        "<div class=\"step-pre\">temp = (98.6)\n"
        "print(type(temp))   # &lt;class 'float'&gt; — NOT a tuple\n\n"
        "temp = (98.6,)\n"
        "print(type(temp))   # &lt;class 'tuple'&gt; — one-item tuple\n"
        "print(temp[0])      # 98.6</div>"
        "<p>This matters when an API expects a <b>sequence of readings</b>, not one number. "
        "It loops (or indexes) the values — a float has no items to walk.</p>"
        "<p><b>1) No type hints</b> — works the same at run time:</p>"
        "<div class=\"step-pre\">def average_temps(readings):\n"
        "    # API expects a sequence: (98.6,) or [98.6, 99.1]\n"
        "    return sum(readings) / len(readings)\n"
        "\n"
        "# FAIL — scalar float\n"
        "average_temps(98.6)\n"
        "# TypeError: 'float' object is not iterable\n"
        "\n"
        "# SUCCEED — one-item tuple\n"
        "average_temps((98.6,))\n"
        "# OUTPUT → 98.6</div>"
        "<p><b>2) With type hints</b> "
        "(<code>readings: tuple</code>, <code>-&gt; float</code>) — "
        "<b>same output</b>. Python does <b>not</b> check types when you run the file. "
        "Hints are notes for humans and tools like <b>mypy</b> / <b>pyright</b>.</p>"
        "<div class=\"step-pre\">def average_temps(readings: tuple) -> float:\n"
        "    # API expects a sequence: (98.6,) or [98.6, 99.1]\n"
        "    return sum(readings) / len(readings)\n"
        "\n"
        "# Still FAIL at run time — type hint does NOT block this\n"
        "average_temps(98.6)\n"
        "# TypeError: 'float' object is not iterable\n"
        "\n"
        "# Still SUCCEED — same numbers as version 1\n"
        "average_temps((98.6,))\n"
        "# OUTPUT → 98.6\n"
        "average_temps((98.6, 99.1))\n"
        "# OUTPUT → 98.85</div>"
        "<table class=\"data-tbl\">"
        "<tr><th></th><th>No hints</th><th>With <code>: tuple</code> / <code>-&gt; float</code></th></tr>"
        "<tr><td>Run-time output</td><td>Same</td><td>Same</td></tr>"
        "<tr><td><code>average_temps(98.6)</code></td>"
        "<td>TypeError</td><td>TypeError (still crashes)</td></tr>"
        "<tr><td><code>average_temps((98.6,))</code></td>"
        "<td>98.6</td><td>98.6</td></tr>"
        "<tr><td>Extra value</td><td>—</td>"
        "<td>mypy/pyright can <b>warn early</b> that 98.6 is not a tuple</td></tr>"
        "</table>"
        "<p><b>Example — average one patient’s temperature readings:</b></p>"
        "<div class=\"step-pre\"># INPUT\n"
        "patient_temps = (98.6, 99.1, 98.9)\n"
        "result = round(average_temps(patient_temps), 2)\n"
        "print(result)\n"
        "\n"
        "# OUTPUT\n"
        "98.87</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Write this</th><th>What you get</th><th>When to use</th></tr>"
        "<tr><td><code>98.6</code> or <code>(98.6)</code></td><td>float</td>"
        "<td>One temperature number</td></tr>"
        "<tr><td><code>(98.6,)</code></td><td>tuple of length 1</td>"
        "<td>API wants a one-item sequence</td></tr>"
        "</table>"
    ),
    "Q1.7": (
        "<p>A <b>tuple</b> is a fixed photo. A <b>list</b> is a sticky note you can edit.</p>"
        "<p>GPS coordinates like <code>(12.97, 80.22)</code> should not change — "
        "use a <b>tuple</b>. It is smaller (no extra empty slots) and can be a "
        "<b>dict key</b>.</p>"
        "<p>If you must add, remove, or change points later, use a <b>list</b>.</p>"
        "<p><b>Why it matters for thousands of scan points.</b> One coordinate looks tiny, "
        "but a CT/MRI slice holds <b>thousands</b> of them — so the per-point cost gets "
        "multiplied thousands of times.</p>"
        "<p><b>1) Memory — one point</b><br>"
        "A list keeps <b>spare empty slots</b> so it can grow later. A tuple never grows, "
        "so it needs no spare room.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "import sys\n"
        "print(sys.getsizeof((1.0, 2.0, 3.0)))   # tuple\n"
        "print(sys.getsizeof([1.0, 2.0, 3.0]))   # list\n"
        "\n"
        "# OUTPUT\n"
        "64      # tuple (x, y, z)\n"
        "88      # list  (x, y, z) — 24 bytes more</div>"
        "<p><b>2) Memory — 1,000 imaging points</b><br>"
        "Same 24 extra bytes, now paid 1,000 times.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "import sys\n"
        "tuples = [(float(i), float(i), float(i)) for i in range(1000)]\n"
        "lists  = [[float(i), float(i), float(i)] for i in range(1000)]\n"
        "\n"
        "def total(points):\n"
        "    return sys.getsizeof(points) + sum(sys.getsizeof(p) for p in points)\n"
        "\n"
        "print(total(tuples))\n"
        "print(total(lists))\n"
        "\n"
        "# OUTPUT\n"
        "72856   # tuples  ~71 KB\n"
        "88856   # lists   ~87 KB  → ~16 KB wasted per 1,000 points</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Points stored</th><th>Tuples</th><th>Lists</th><th>Extra cost of lists</th></tr>"
        "<tr><td>1</td><td>64 B</td><td>88 B</td><td>+24 B</td></tr>"
        "<tr><td>1,000</td><td>~71 KB</td><td>~87 KB</td><td>~+16 KB</td></tr>"
        "<tr><td>100,000</td><td>~7 MB</td><td>~9 MB</td><td>~+2 MB</td></tr>"
        "</table>"
        "<p><b>3) Access speed — almost identical</b><br>"
        "Both are indexed <b>directly</b> (<code>O(1)</code>), so reading "
        "<code>point[0]</code> is equally fast. Tuples win only slightly, "
        "because less memory means better cache use.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "import timeit\n"
        "print(timeit.timeit(lambda: [p[0] for p in tuples], number=200))\n"
        "print(timeit.timeit(lambda: [p[0] for p in lists], number=200))\n"
        "\n"
        "# OUTPUT\n"
        "0.0054   # tuples\n"
        "0.0056   # lists — practically the same</div>"
        "<p><b>4) The real deciding factor — a tuple can be a dict key</b><br>"
        "Imaging code often caches a value <b>per voxel</b>. Only tuples can be keys.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "density = {(10.0, 20.0, 5.0): 0.87}   # tuple key — works\n"
        "print(density[(10.0, 20.0, 5.0)])\n"
        "\n"
        "bad = {[10.0, 20.0, 5.0]: 0.87}       # list key\n"
        "\n"
        "# OUTPUT\n"
        "0.87\n"
        "TypeError: unhashable type: 'list'</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Need</th><th>Choose</th><th>Why</th></tr>"
        "<tr><td>Store thousands of scanned (x, y, z)</td><td><b>tuple</b></td>"
        "<td>~27% less memory; coordinates never change after capture</td></tr>"
        "<tr><td>Cache/index a value per voxel</td><td><b>tuple</b></td>"
        "<td>Hashable → can be a <code>dict</code> key or in a <code>set</code></td></tr>"
        "<tr><td>Algorithm moves / smooths points</td><td><b>list</b></td>"
        "<td>Editable in place — no rebuilding each point</td></tr>"
        "<tr><td>Point count grows while scanning</td><td><b>list</b></td>"
        "<td><code>append</code> is cheap; tuples must be recreated</td></tr>"
        "</table>"
        "<p>Rule: <b>fixed record → tuple</b>. <b>Growing / editing → list</b>.</p>"
    ),
    "Q1.8": (
        "<p>Think of the store as a <b>filing cabinet</b>: each patient ID opens one "
        "folder, with smaller folders for personal details, medical details, and visits.</p>"
        "<div class=\"step-pre\">records = {\n"
        "    \"P1\": {\n"
        "        \"personal\": {\"name\": \"Asha\", \"age\": 42},\n"
        "        \"medical\": {\"blood_type\": \"O+\", \"allergies\": []},\n"
        "        \"visits\": [{\"date\": \"2025-01-15\", \"diagnosis\": \"Checkup\"}],\n"
        "    }\n"
        "}</div>"
        "<p><b>Add</b> checks for a duplicate ID, then creates those nested folders. "
        "<b>Update</b> finds the existing folder and changes the requested part.</p>"
        "<div class=\"step-pre\"># INPUT — add, then update\n"
        "db.add(\"P2\", {\"name\": \"Ben\"}, {\"blood_type\": \"A+\"})\n"
        "db.update(\"P2\", personal={\"name\": \"Ben\", \"age\": 30})\n"
        "\n"
        "# OUTPUT\n"
        "db.records[\"P2\"][\"personal\"]  # {\"name\": \"Ben\", \"age\": 30}</div>"
        "<p>For a blood-type search, <b>normalize</b> the text first: remove outside "
        "spaces and make it uppercase. Then <code>\" a+ \"</code> and <code>\"A+\"</code> match.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "db.by_blood_type(\" a+ \")\n"
        "\n"
        "# OUTPUT\n"
        "[\"P2\"]</div>"
        "<p>Return visit history as a <b>copy</b>, not the store's actual list. "
        "That lets a caller edit their result without changing the saved record.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "history = db.visits(\"P1\")\n"
        "history.append({\"date\": \"2025-02-01\", \"diagnosis\": \"Added only here\"})\n"
        "\n"
        "# OUTPUT\n"
        "len(history)                 # 2\n"
        "len(db.records[\"P1\"][\"visits\"])  # 1 — stored visits stay unchanged</div>"
    ),
    "Q1.9": (
        "<p>A dictionary is like hospital lockers. A <b>key</b> is the locker label, "
        "so it must stay the same after the locker is assigned.</p>"
        "<p>Python uses a <b>hash</b> to find the locker quickly. Keys must be "
        "<b>hashable</b>: they have a stable hash and clear equality.</p>"
        "<table class=\"data-tbl\">"
        "<tr><th>Type</th><th>Can be a dict key?</th><th>Healthcare example</th></tr>"
        "<tr><td><code>str</code></td><td>Yes</td><td><code>\"P123\"</code> patient ID</td></tr>"
        "<tr><td><code>int</code></td><td>Yes</td><td>room number <code>101</code></td></tr>"
        "<tr><td><code>tuple</code></td><td>Yes, if every item is hashable</td><td>fixed symptom pattern</td></tr>"
        "<tr><td><code>list</code>, <code>set</code>, <code>dict</code></td><td>No</td><td>they can change</td></tr>"
        "</table>"
        "<p>A symptom <b>list</b> can be edited later, so Python refuses it as a key. "
        "A tuple of symptom strings is fixed, so it works.</p>"
        "<div class=\"step-pre\"># INPUT — list key fails\n"
        "symptom_rules = {}\n"
        "symptom_rules[[\"fever\", \"cough\"]] = \"screen\"\n"
        "\n"
        "# OUTPUT\n"
        "TypeError: unhashable type: 'list'\n"
        "\n"
        "# INPUT — tuple key works\n"
        "symptom_rules[(\"fever\", \"cough\")] = \"screen\"\n"
        "print(symptom_rules[(\"fever\", \"cough\")])\n"
        "\n"
        "# OUTPUT\n"
        "screen</div>"
        "<p>A tuple is only safe when <b>everything inside it</b> is hashable too; "
        "a tuple containing a list still fails.</p>"
    ),
    "Q1.10": (
        "<p>Two ways to open a patient dict folder:</p>"
        "<p><code>record[\"blood_type\"]</code> — subscription.<br>"
        "If the field is missing → <b>KeyError</b> (loud alarm). "
        "Good for <b>required</b> data.</p>"
        "<p><code>record.get(\"nickname\")</code> — get.<br>"
        "If missing → returns <b>None</b> (or a default you choose). "
        "Quiet. Good for <b>optional</b> fields.</p>"
        "<div class=\"step-pre\">patient = {\"name\": \"Asha\", \"blood_type\": \"A+\"}\n\n"
        "print(patient[\"blood_type\"])          # \"A+\" — required field\n"
        "# print(patient[\"nickname\"])         # KeyError if missing\n\n"
        "print(patient.get(\"nickname\"))       # None — quiet\n"
        "print(patient.get(\"nickname\", \"N/A\"))  # \"N/A\" — your default</div>"
        "<table class=\"data-tbl\">"
        "<tr><th></th><th><code>patient[key]</code></th><th><code>patient.get(key)</code></th></tr>"
        "<tr><td>Missing key</td><td><b>KeyError</b></td><td><b>None</b> / default</td></tr>"
        "<tr><td>Use for</td><td>Required fields</td><td>Optional fields</td></tr>"
        "</table>"
        "<p>Do not invent a fake blood type with <code>get</code> — that can hide a real missing value.</p>"
    ),
    "Q1.11": (
        "<p>This checker is a <b>matching game</b>: compare a new medicine's known "
        "bad partners with the medicines already in the patient's bag.</p>"
        "<p>First <b>normalize</b> every name with <code>strip().lower()</code>, so "
        "<code>\" Aspirin \"</code> and <code>\"aspirin\"</code> mean the same thing.</p>"
        "<p>Look up the new medicine's partner set, then use <b>set intersection</b> "
        "(<code>current &amp; partners</code>) to find names in both sets.</p>"
        "<div class=\"step-pre\">db = {\"aspirin\": {\"warfarin\", \"heparin\"}}\n"
        "\n"
        "# INPUT — conflict\n"
        "current_meds = {\" Warfarin \", \"metformin\"}\n"
        "new_med = \"Aspirin\"\n"
        "check_drug_interactions(current_meds, new_med, db)\n"
        "\n"
        "# OUTPUT\n"
        "{\"safe\": False, \"interactions\": {\"warfarin\"},\n"
        " \"recommendations\": [\"Consult a clinician before prescribing.\"]}</div>"
        "<div class=\"step-pre\"># INPUT — no listed conflict\n"
        "current_meds = {\"metformin\"}\n"
        "new_med = \" aspirin \"\n"
        "check_drug_interactions(current_meds, new_med, db)\n"
        "\n"
        "# OUTPUT\n"
        "{\"safe\": True, \"interactions\": set(),\n"
        " \"recommendations\": [\"No listed interaction; still verify clinically.\"]}</div>"
        "<p>An empty intersection means <b>no match in this small database</b>, not proof "
        "that prescribing is safe. This is an <b>educational-only</b> example; real "
        "decisions need normalized drug codes, dose and route information, and clinician review.</p>"
    ),
    "Q1.12": (
        "<p>A <b>set</b> is like a magic attendance sheet: each name appears once.</p>"
        "<p>Python stores items using a <b>hash table</b> — like numbered cubbies. "
        "Hash picks a cubby; equality checks collisions.</p>"
        "<p>Asking “is this ID already here?” is usually <b>very fast (O(1))</b>.</p>"
        "<p>Hashes must stay stable. Weird / hostile inputs can slow things down.</p>"
        "<p>Sets are great for unique IDs in memory — not a replacement for a "
        "real database index.</p>"
    ),
    "Q2.1": (
        "<p>Type hints are like labels on clinic forms: they say what should arrive. "
        "An <b>Enum</b> gives blood types a fixed menu, and a <b>dataclass</b> gives "
        "each vital-sign reading a clear shape.</p>"
        "<div class=\"step-pre\">from dataclasses import dataclass\n"
        "from enum import Enum\n"
        "from typing import Optional\n"
        "\n"
        "class BloodType(Enum):\n"
        "    O_POS = \"O+\"\n"
        "\n"
        "@dataclass(frozen=True)\n"
        "class VitalSigns:\n"
        "    systolic: int\n"
        "    diastolic: int\n"
        "    temperature: float\n"
        "    heart_rate: int\n"
        "\n"
        "emergency_contact: Optional[dict[str, str]] = None</div>"
        "<p><b>Runtime validation</b> still checks the real values: a non-blank ID, "
        "age and vital ranges, a real <code>BloodType</code>, at least one vital reading, "
        "and both <code>name</code> and <code>phone</code> when an emergency contact is provided.</p>"
        "<div class=\"step-pre\"># INPUT — valid\n"
        "validate_patient_data(\n"
        "    \"P1\", 42, BloodType.O_POS,\n"
        "    [VitalSigns(120, 80, 98.6, 72)],\n"
        "    {\"name\": \"Ravi\", \"phone\": \"555-0100\"},\n"
        ")\n"
        "\n"
        "# OUTPUT\n"
        "True\n"
        "\n"
        "# INPUT — invalid systolic range\n"
        "validate_patient_data(\"P2\", 42, BloodType.O_POS, [VitalSigns(10, 80, 98.6, 72)])\n"
        "\n"
        "# OUTPUT\n"
        "False</div>"
        "<p>Hints help humans and tools, but <b>type hints do not enforce anything at runtime</b>. "
        "The validation code is what rejects missing or out-of-range data.</p>"
    ),
    "Q2.2": (
        "<p><b>Java</b> is like a gate that checks declared types before the program runs. "
        "<b>Python hints</b> are labels that optional checkers can read.</p>"
        "<table class=\"data-tbl\">"
        "<tr><th></th><th>Java static types</th><th>Python type hints</th></tr>"
        "<tr><td>When checked</td><td><b>Compile time</b> by the compiler</td><td>By optional tools such as <b>mypy</b> / <b>pyright</b></td></tr>"
        "<tr><td>At normal runtime</td><td>Declared types are enforced by the language model</td><td>Hints alone do not block wrong values</td></tr>"
        "<tr><td>Example</td><td><code>String name</code></td><td><code>name: str</code></td></tr>"
        "</table>"
        "<p>In a multi-developer healthcare codebase, hints make <b>contracts</b> visible: "
        "a function can clearly promise a <code>Patient</code> and return a report.</p>"
        "<p>They support <b>safer refactors</b> because a checker can find callers that no longer "
        "fit the changed contract. They also make <b>Optional clarity</b> explicit: "
        "<code>str | None</code> tells teammates to handle a missing emergency phone.</p>"
        "<p>Still validate JSON, database rows, and user input at <b>runtime</b>. "
        "A hint is helpful documentation and a tool-checkable promise, not a safety barrier by itself.</p>"
    ),
    "Q3.1": (
        "<p><b>BMI</b> is a quick number made from weight and height: "
        "<b>weight kg ÷ (height m × height m)</b>. Height must be positive.</p>"
        "<p>Start with the normal dose. If age is <b>over 65</b>, give "
        "<b>10% less</b> (multiply by <code>0.9</code>). A BMI from <b>18.5 to 24.9</b> "
        "counts as healthy in this exercise.</p>"
        "<p>For a 1000 mg bottle, <b>days supply</b> is "
        "<code>floor(1000 ÷ adjusted dose)</code>: only complete daily doses count.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "weight_kg, height_m = 70, 1.75\n"
        "base_dosage_mg, age = 50, 70\n\n"
        "# BMI = 70 / (1.75 * 1.75) = 22.86\n"
        "# Age over 65: 50 mg * 0.9 = 45 mg\n"
        "# floor(1000 / 45) = 22 days\n\n"
        "# OUTPUT\n"
        "{'bmi': 22.86, 'adjusted_dosage_mg': 45.0,\n"
        " 'days_supply': 22, 'healthy_bmi': True}</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Check</th><th>Rule</th></tr>"
        "<tr><td>BMI healthy?</td><td><code>18.5 &lt;= bmi &lt;= 24.9</code></td></tr>"
        "<tr><td>Age over 65?</td><td>Use <code>base_dosage * 0.9</code></td></tr>"
        "<tr><td>Bottle lasts</td><td><code>floor(1000 / dosage)</code></td></tr>"
        "</table>"
    ),
    "Q3.2": (
        "<p>Triage is a <b>traffic light</b>: check <b>Critical</b> first, then "
        "<b>Urgent</b>, otherwise choose <b>Standard</b>. The first matching level wins.</p>"
        "<table class=\"data-tbl\">"
        "<tr><th>Priority</th><th>Any one of these simplified rules</th><th>Example</th></tr>"
        "<tr><td><b>Critical</b></td><td>temp &gt; 104; systolic &gt; 180; diastolic &gt; 120; "
        "heart rate &gt; 120; or unconscious</td><td>105°F, 130 bpm → Critical</td></tr>"
        "<tr><td><b>Urgent</b></td><td>temp &gt; 101; systolic &gt; 140; diastolic &gt; 90; "
        "or pain &gt; 7</td><td>102°F with pain 4 → Urgent</td></tr>"
        "<tr><td><b>Standard</b></td><td>No Critical or Urgent rule matches</td>"
        "<td>99°F, (120, 80), pain 3 → Standard</td></tr>"
        "</table>"
        "<p>Unpack blood pressure into <b>systolic</b> and <b>diastolic</b>; test each number "
        "instead of comparing the whole pair.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "triage_patient(105, (150, 95), 130, True, 4)\n\n"
        "# OUTPUT\n"
        "Critical  # critical temperature / heart rate wins before urgent BP</div>"
        "<p><b>Educational only:</b> these are simplified programming thresholds, "
        "not a real medical triage protocol or medical advice.</p>"
    ),
    "Q3.3": (
        "<p>Permissions are three tiny <b>on/off switches</b> packed into one number: "
        "<b>READ = 1</b> (<code>001</code>), <b>WRITE = 2</b> (<code>010</code>), and "
        "<b>DELETE = 4</b> (<code>100</code>).</p>"
        "<p><b>Add</b> a switch with OR (<code>|</code>). <b>Remove</b> one with AND NOT "
        "(<code>&amp; ~</code>). <b>Check</b> one with AND (<code>&amp;</code>).</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "permissions = 0             # 000\n"
        "permissions |= 1 | 2        # add READ and WRITE → 011 (3)\n"
        "permissions &amp;= ~2          # remove WRITE → 001 (1)\n"
        "can_read = (permissions &amp; 1) == 1\n"
        "can_write = (permissions &amp; 2) == 2\n\n"
        "# OUTPUT\n"
        "1\n"
        "True\n"
        "False</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Job</th><th>Code idea</th></tr>"
        "<tr><td>Add a right</td><td><code>permissions |= flag</code></td></tr>"
        "<tr><td>Remove a right</td><td><code>permissions &amp;= ~flag</code></td></tr>"
        "<tr><td>Check a right</td><td><code>(permissions &amp; flag) == flag</code></td></tr>"
        "</table>"
        "<p>Flags are compact, but they are <b>not full security</b>: real systems also need "
        "identity checks, server-side enforcement, ownership rules, and audit logs.</p>"
    ),
    "Q3.4": (
        "<p>Eligibility is a set of small <b>decision facts</b>, not one mysterious "
        "yes/no answer. Convert lists to sets, then use <b>intersection</b> "
        "(<code>&amp;</code>) to ask “do any items overlap?”</p>"
        "<p>Critical symptoms are <code>chest_pain</code>, <code>difficulty_breathing</code>, "
        "or <code>severe_bleeding</code>. Accepted insurance includes <code>medicare</code>, "
        "<code>aetna</code>, <code>bcbs</code>, and <code>cigna</code>. History conflicts are "
        "<code>organ_transplant</code> or <code>active_bleeding</code>.</p>"
        "<p>Use <code>medical_history is None</code> to mean <b>missing</b>. An empty list "
        "<code>[]</code> is different: history was provided, but it has no items.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "check_patient_eligibility(\n"
        "    50, [\"cough\"], [\"aetna\"], [\"asthma\"]\n"
        ")\n\n"
        "# OUTPUT\n"
        "{'has_critical_symptoms': False, 'insurance_accepted': True,\n"
        " 'conflicting_history': False, 'history_provided': True}</div>"
        "<p>Returning this <b>result dictionary</b> keeps every decision fact visible, "
        "so a person can see why a rule did or did not match.</p>"
    ),
    "Q3.5": (
        "<p>The walrus <code>:=</code> means <b>save a value and use it right away</b>. "
        "Here, a loop checks each patient once and keeps only patients with flags.</p>"
        "<p><b>1. BMI filter:</b> calculate BMI once, then test whether it is over 30.<br>"
        "<b>2. Fever:</b> read temperature once, then test whether it is at least 100.4.<br>"
        "<b>3. Medication count:</b> count medicines once, then test whether the count is over 5.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "patient = {\"id\": \"P1\", \"weight_kg\": 95, \"height_m\": 1.7,\n"
        "           \"temperature\": 101, \"medications\": [\"a\"] * 6}\n\n"
        "if (bmi := patient[\"weight_kg\"] / patient[\"height_m\"] ** 2) &gt; 30:\n"
        "    print(f\"obesity BMI={bmi:.1f}\")\n"
        "if (temp := patient.get(\"temperature\", 0)) &gt;= 100.4:\n"
        "    print(f\"fever {temp}\")\n"
        "if (count := len(patient.get(\"medications\", []))) &gt; 5:\n"
        "    print(f\"polypharmacy {count}\")\n\n"
        "# OUTPUT\n"
        "obesity BMI=32.9\n"
        "fever 101\n"
        "polypharmacy 6</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Walrus use</th><th>Saved value</th><th>Test</th></tr>"
        "<tr><td>BMI filter</td><td><code>bmi</code></td><td><code>bmi &gt; 30</code></td></tr>"
        "<tr><td>Fever</td><td><code>temp</code></td><td><code>temp &gt;= 100.4</code></td></tr>"
        "<tr><td>Medication count</td><td><code>count</code></td><td><code>count &gt; 5</code></td></tr>"
        "</table>"
        "<p>Use <code>:=</code> only when the line stays <b>easy to read</b>. "
        "For a long medical rule, normal named steps are clearer to review.</p>"
    ),
    "Q4.1": (
        "<p>This is an <b>educational assessment workflow</b>, not a real diagnosis. "
        "Its rules are a checklist: <b>emergency → chronic → common → further testing</b>. "
        "Returning a dictionary makes the chosen action clear.</p>"
        "<div class=\"step-pre\"># INPUT — decision order\n"
        "diagnose_patient([\"cough\"], {\"temperature\": 101}, [], {})\n\n"
        "# OUTPUT\n"
        "{'priority': 'common', 'action': 'clinical assessment'}</div>"
        "<p>A monitoring loop needs <b>bounds</b>: check every <b>30 minutes</b>, add an "
        "alert for an abnormal reading, and <b>break</b> after 2 stable hours. "
        "That stop rule prevents endless checking.</p>"
        "<div class=\"step-pre\"># INPUT — bounded monitoring idea\n"
        "stable_minutes = 0\n"
        "for minute in range(0, 241, 30):\n"
        "    abnormal = False  # replace with this exercise's reading check\n"
        "    if abnormal:\n"
        "        print(f\"{minute}: alert\")\n"
        "        stable_minutes = 0\n"
        "    else:\n"
        "        stable_minutes += 30\n"
        "    if stable_minutes == 120:\n"
        "        break\n\n"
        "# OUTPUT\n"
        "Stops after 120 stable minutes</div>"
        "<p>A daily medicine plan uses a <b>for-loop</b> over each time and its medicines. "
        "Give meal and sleep times special wording when needed.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "schedule = {\"08:00 breakfast\": [\"Vitamin\"], \"22:00 bedtime\": [\"Tablet\"]}\n"
        "for time, medicines in schedule.items():\n"
        "    for medicine in medicines:\n"
        "        print(f\"{time}: take {medicine}\")\n\n"
        "# OUTPUT\n"
        "08:00 breakfast: take Vitamin\n"
        "22:00 bedtime: take Tablet</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Part</th><th>Purpose</th></tr>"
        "<tr><td>Ordered <code>if</code>/<code>elif</code></td><td>Highest-priority rule wins</td></tr>"
        "<tr><td>Bounded loop + <code>break</code></td><td>Monitoring cannot run forever</td></tr>"
        "<tr><td>Nested <code>for</code> loop</td><td>One instruction per scheduled medicine</td></tr>"
        "</table>"
    ),
    "Q5.1": (
        "<p>Comprehensions are <b>short collection recipes</b>. Pick the recipe by the "
        "shape you want back.</p>"
        "<p><b>1. List:</b> collect diabetes patient IDs. Result shape: "
        "<code>[\"P1\", \"P3\"]</code>.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "patients = [{\"id\": \"P1\", \"conditions\": [\"diabetes\"]}, {\"id\": \"P2\", \"conditions\": []}]\n"
        "diabetes_ids = [p[\"id\"] for p in patients if \"diabetes\" in p.get(\"conditions\", [])]\n"
        "\n# OUTPUT\n"
        "[\"P1\"]</div>"
        "<p><b>2. Dict:</b> map each ID to its latest vitals. Result shape: "
        "<code>{\"P1\": {\"bp\": 130}}</code>.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "latest = {p[\"id\"]: p[\"vitals\"][-1] for p in patients if p.get(\"vitals\")}\n"
        "\n# OUTPUT\n"
        "{\"P1\": {\"bp\": 130}}</div>"
        "<p><b>3. Set:</b> collect medicines without repeats. Result shape: "
        "<code>{\"aspirin\", \"insulin\"}</code>.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "unique_meds = {med for p in patients for med in p.get(\"medications\", [])}\n"
        "\n# OUTPUT\n"
        "{\"aspirin\", \"insulin\"}  # order can vary</div>"
        "<p><b>4. Generator:</b> stream high-risk IDs one at a time. Result shape: "
        "<b>generator object</b>, not a ready-made list.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "high_risk = (p[\"id\"] for p in patients if p.get(\"risk_score\", 0) >= 8)\n"
        "print(list(high_risk))\n"
        "\n# OUTPUT\n"
        "[\"P1\"]</div>"
        "<p>Extract a <b>named helper</b>, such as <code>is_high_risk(patient)</code>, "
        "when the rule has several checks. A clear helper is easier to test and audit than "
        "a long one-line recipe.</p>"
    ),
    "Q5.2": (
        "<p>A generator is a <b>paused worker with a bookmark</b>. Between iterations, "
        "Python keeps its frame: the next instruction and local values such as "
        "<code>patient</code>.</p>"
        "<p>A generator expression uses parentheses: "
        "<code>(p for p in records if p[\"risk\"] &gt;= 8)</code>.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "records = [{\"id\": \"P1\", \"risk\": 9}, {\"id\": \"P2\", \"risk\": 3}]\n"
        "high_risk = (p for p in records if p[\"risk\"] >= 8)\n"
        "print(next(high_risk))   # resumes, then pauses again\n"
        "for patient in high_risk:\n"
        "    print(patient)\n"
        "\n# OUTPUT\n"
        "{\"id\": \"P1\", \"risk\": 9}\n"
        "# no more records: P1 was already consumed</div>"
        "<p>This is useful for <b>millions of records</b>: it makes one result when asked "
        "instead of building millions of result objects first.</p>"
        "<table class=\"data-tbl\">"
        "<tr><th></th><th>List comprehension</th><th>Generator expression</th></tr>"
        "<tr><td>Memory</td><td>Stores all results now</td><td>Usually keeps one result at a time</td></tr>"
        "<tr><td>When made</td><td>Immediately</td><td>On <code>next</code> or a loop</td></tr>"
        "<tr><td>Reuse</td><td>Loop over it again</td><td>Usually <b>single-pass</b></td></tr>"
        "</table>"
        "<p>The tradeoff is <b>exhaustion</b>: once consumed, a generator is empty. "
        "Make a new generator if you need another pass.</p>"
    ),
    "Q6.1": (
        "<p>An appointment has required IDs, then flexible details. "
        "<code>*args</code> packs extra <b>positional</b> details into a tuple; "
        "<code>**kwargs</code> packs named options into a dict.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "def schedule(patient_id, doctor_id, *details, **options):\n"
        "    return {\"patient\": patient_id, \"doctor\": doctor_id,\n"
        "            \"details\": details, \"options\": options}\n"
        "print(schedule(\"P1\", \"D9\", \"2026-07-26\", \"10:00\", priority=\"urgent\"))\n"
        "\n# OUTPUT\n"
        "{\"patient\": \"P1\", \"doctor\": \"D9\", \"details\": (\"2026-07-26\", \"10:00\"),\n"
        " \"options\": {\"priority\": \"urgent\"}}</div>"
        "<p>Both calling patterns work: details can be positional, while options explain "
        "themselves with names such as <code>priority=\"urgent\"</code>.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "def update_patient_record(patient_id, /, name=None, age=None, *, blood_type=None):\n"
        "    return {\"id\": patient_id, \"name\": name, \"age\": age, \"blood_type\": blood_type}\n"
        "print(update_patient_record(\"P1\", \"Asha\", 10, blood_type=\"A+\"))\n"
        "update_patient_record(patient_id=\"P1\")\n"
        "\n# OUTPUT\n"
        "{\"id\": \"P1\", \"name\": \"Asha\", \"age\": 10, \"blood_type\": \"A+\"}\n"
        "TypeError: positional-only argument passed as keyword argument</div>"
        "<p>The <code>/</code> makes <code>patient_id</code> <b>positional-only</b>; "
        "the <code>*</code> makes medical fields such as <code>blood_type</code> "
        "<b>keyword-only</b>, so their meaning is visible at the call.</p>"
        "<table class=\"data-tbl\">"
        "<tr><th></th><th><code>*args</code></th><th><code>**kwargs</code></th></tr>"
        "<tr><td>Holds</td><td>tuple</td><td>dict</td></tr>"
        "<tr><td>From call</td><td>extra positional</td><td>extra <code>name=value</code></td></tr>"
        "</table>"
        "<p>Validate required IDs first, then return a tidy appointment record.</p>"
    ),
    "Q6.2": (
        "<p>Recursion means: check one person, then ask the same question about each "
        "parent. The score gets smaller farther up the family tree: <b>0.5</b> for a "
        "parent, <b>0.25</b> for a grandparent, and <b>0.125</b> for a great-grandparent.</p>"
        "<p>A <b>base case</b> stops safely when a person is missing or was already visited. "
        "The <code>visited</code> set prevents a cycle such as A → B → A from looping forever.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "# P1 has parents Mom and Dad; Mom has parent Gran\n"
        "# Dad and Gran have diabetes\n"
        "score = 0.5 + 0.25\n"
        "print(score)\n"
        "\n# OUTPUT\n"
        "0.75  # Dad is one generation away; Gran is two</div>"
        "<p>Medication interactions are a <b>different graph walk</b>. Start at one drug, "
        "visit its neighbors, and use another visited set to avoid repeating drugs.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "graph = {\"A\": {\"B\"}, \"B\": {\"A\", \"C\"}, \"C\": set()}\n"
        "# visit A, then B, then C; skip A when B points back to it\n"
        "\n# OUTPUT\n"
        "{\"B\", \"C\"}  # reachable interactions; order can vary</div>"
        "<p>For real health decisions, this is only a programming exercise—not a clinical risk model.</p>"
    ),
    "Q6.3": (
        "<p>Each lab has a normal window. Values on the <b>boundary are normal</b>: "
        "for glucose <code>(70, 100)</code>, both 70 and 100 are in range.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "labs = [{\"test\": \"glucose\", \"value\": 95, \"normal_range\": (70, 100)},\n"
        "        {\"test\": \"glucose\", \"value\": 120, \"normal_range\": (70, 100)}]\n"
        "severity = lambda r: max(r[\"normal_range\"][0] - r[\"value\"],\n"
        "                         r[\"value\"] - r[\"normal_range\"][1], 0)\n"
        "abnormal = list(filter(lambda r: severity(r) > 0, labs))\n"
        "scores = list(map(lambda r: {\"test\": r[\"test\"], \"severity\": severity(r)}, labs))\n"
        "priority = sorted(labs, key=severity, reverse=True)\n"
        "\n# OUTPUT\n"
        "abnormal: [{\"test\": \"glucose\", \"value\": 120, \"normal_range\": (70, 100)}]\n"
        "scores: [{\"test\": \"glucose\", \"severity\": 0}, {\"test\": \"glucose\", \"severity\": 20}]\n"
        "priority: 120 first, then 95</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Tool</th><th>Job</th></tr>"
        "<tr><td><code>filter</code></td><td>Keep abnormal lab rows</td></tr>"
        "<tr><td><code>map</code></td><td>Create severity information</td></tr>"
        "<tr><td><code>sorted</code></td><td>Put the highest severity first</td></tr>"
        "</table>"
        "<p>Keep a <b>lambda</b> tiny. If severity needs units, exceptions, or several "
        "clinical rules, use a named <code>calculate_severity</code> helper instead.</p>"
    ),
    "Q6.4": (
        "<p>Scope means <b>where Python can find a name</b>. Reading a global setting is OK. "
        "Rebinding the global name needs <code>global</code>; changing a value inside its "
        "dictionary does not.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "HOSPITAL_CONFIG = {\"capacity\": 50}\n"
        "def assign_doctor():\n"
        "    return HOSPITAL_CONFIG[\"capacity\"]   # read global: OK\n"
        "def update_capacity(limit):\n"
        "    HOSPITAL_CONFIG[\"capacity\"] = limit # mutate dict: no global needed\n"
        "\n# OUTPUT\n"
        "assign_doctor()  # 50\n"
        "update_capacity(40)\n"
        "assign_doctor()  # 40</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Action inside a function</th><th><code>global</code>?</th></tr>"
        "<tr><td>Read <code>HOSPITAL_CONFIG</code></td><td>No</td></tr>"
        "<tr><td>Mutate <code>HOSPITAL_CONFIG[\"capacity\"]</code></td><td>No</td></tr>"
        "<tr><td>Rebind <code>HOSPITAL_CONFIG = {...}</code></td><td>Yes</td></tr>"
        "</table>"
        "<p>Shared mutable settings can make tests and concurrent requests confusing. Prefer "
        "passing configuration into functions or keeping it on an object when practical.</p>"
    ),
    "Q6.5": (
        "<p>Python searches names in this order: <b>L → E → G → B</b>: "
        "<b>Local</b>, <b>Enclosing</b>, <b>Global</b>, then <b>Builtins</b> "
        "(such as <code>len</code>).</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "threshold = \"global\"\n"
        "def hospital_config():\n"
        "    threshold = \"enclosing\"\n"
        "    def check_patient():\n"
        "        threshold = \"local\"\n"
        "        return threshold\n"
        "    return check_patient()\n"
        "print(hospital_config())\n"
        "\n# OUTPUT\n"
        "local  # Local wins before Enclosing and Global</div>"
        "<p>Use <code>nonlocal</code> to <b>rebind</b> a name in the enclosing function. "
        "Use <code>global</code> to rebind a name in the module.</p>"
        "<p>Java is also statically scoped, but a method usually reads a field through "
        "<code>this.field</code> (or a class field) and a local variable can shadow it. "
        "Python nested functions can also close over enclosing values directly.</p>"
    ),
    "Q7.1": (
        "<p>Built-ins are <b>ready-made tools</b>. Think: pick ages, keep matching "
        "records, pair two lists, then make a small report. These examples are "
        "<b>educational data handling</b>, not clinical advice.</p>"
        "<table class=\"data-tbl\">"
        "<tr><th>Tool</th><th>Medical-data task</th><th>What it makes</th></tr>"
        "<tr><td><code>map</code></td><td>Pull each patient's age</td><td>Changed values</td></tr>"
        "<tr><td><code>filter</code></td><td>Keep records matching a rule</td><td>Selected records</td></tr>"
        "<tr><td><code>zip</code></td><td>Pair patients with lab rows</td><td>Pairs; stops at shortest input</td></tr>"
        "<tr><td><code>enumerate</code></td><td>Number a report row</td><td><code>(index, value)</code> pairs</td></tr>"
        "<tr><td><code>reduce</code></td><td>Fold many records into one result</td><td>One accumulated value</td></tr>"
        "<tr><td><code>sorted</code></td><td>Order by age / medicine count</td><td>A new ordered list</td></tr>"
        "<tr><td><code>min</code> / <code>max</code></td><td>Find smallest age / highest temperature</td><td>One extreme value</td></tr>"
        "<tr><td><code>type</code> / <code>id</code></td><td>Debug unexpected data</td><td>Type / temporary object identity</td></tr>"
        "<tr><td><code>range</code></td><td>Make appointment-hour numbers</td><td>A number sequence</td></tr>"
        "</table>"
        "<div class=\"step-pre\"># INPUT\n"
        "patients = [{\"id\": \"P1\", \"age\": 67}, {\"id\": \"P2\", \"age\": 42}]\n"
        "ages = list(map(lambda p: p[\"age\"], patients))\n"
        "older = list(filter(lambda p: p[\"age\"] &gt; 65, patients))\n"
        "paired = list(zip([\"P1\", \"P2\"], [98.6, 99.1]))\n"
        "\n"
        "# OUTPUT\n"
        "# ages   → [67, 42]\n"
        "# older  → [{\"id\": \"P1\", \"age\": 67}]\n"
        "# paired → [(\"P1\", 98.6), (\"P2\", 99.1)]</div>"
        "<div class=\"step-pre\"># INPUT\n"
        "print(list(enumerate([\"P1\", \"P2\"], start=1)))\n"
        "print(min(ages), max([98.6, 99.1]))\n"
        "print(type(patients[0]).__name__)\n"
        "print(list(range(8, 11)))\n"
        "\n"
        "# OUTPUT\n"
        "[(1, \"P1\"), (2, \"P2\")]\n"
        "42 99.1\n"
        "dict\n"
        "[8, 9, 10]</div>"
        "<p><code>reduce</code> can choose the record with most medicines, but give it an "
        "<b>empty-input plan</b>. <code>sorted</code> returns a new list; it does not "
        "change the original. <code>id()</code> helps debug one running program only — "
        "it is <b>not</b> a patient ID.</p>"
    ),
    "Q7.2": (
        "<p><code>reduce</code> is a <b>fold</b>: carry one running answer "
        "(the <b>accumulator</b>) across many items.</p>"
        "<div class=\"step-pre\"># INPUT — patient counts from three departments\n"
        "from functools import reduce\n"
        "counts = [12, 8, 15]\n"
        "total = reduce(lambda running, count: running + count, counts, 0)\n"
        "\n"
        "# OUTPUT\n"
        "# 0 → 12 → 20 → 35\n"
        "print(total)  # 35</div>"
        "<p>The final <code>0</code> is the <b>identity</b>: adding zero changes "
        "nothing, and an empty list safely produces <code>0</code>.</p>"
        "<table class=\"data-tbl\">"
        "<tr><th>Python</th><th>Java Stream</th></tr>"
        "<tr><td><code>reduce(function, values, 0)</code></td><td><code>reduce(0, operation)</code></td></tr>"
        "<tr><td>Folds left-to-right for this example</td><td>May split work for parallel streams</td></tr>"
        "<tr><td>Use a clear accumulator</td><td>Operation must be <b>associative</b> and have a correct identity</td></tr>"
        "</table>"
        "<p><b>Associative</b> means regrouping does not change the answer: "
        "<code>(12 + 8) + 15</code> equals <code>12 + (8 + 15)</code>. That makes "
        "parallel Java reduction safe. For a simple total, "
        "<code>sum(counts)</code> or a comprehension is usually clearer than "
        "<code>reduce</code>.</p>"
    ),
    "R1": (
        "<p>The <b>comma</b> makes a tuple; parentheses only group an expression.</p>"
        "<div class=\"step-pre\"># INPUT\n"
        "one_value = (42)\n"
        "one_reading = (42,)\n"
        "print(type(one_value).__name__)\n"
        "print(type(one_reading).__name__)\n"
        "\n"
        "# OUTPUT\n"
        "int\n"
        "tuple</div>"
        "<p>An API that loops through readings needs a <b>sequence</b>. A scalar "
        "does not have items to loop over.</p>"
        "<div class=\"step-pre\">def average(readings):\n"
        "    return sum(readings) / len(readings)\n"
        "\n"
        "# average(42)     → TypeError: int is not iterable\n"
        "print(average((42,)))\n"
        "# OUTPUT → 42.0</div>"
        "<p>Use <code>42</code> for one number; use <code>(42,)</code> only when "
        "the function expects a one-item sequence.</p>"
    ),
    "R2": (
        "<p>Dict/set keys must be <b>hashable</b> — their hash cannot change.</p>"
        "<p>A <b>list</b> of symptoms can change → not allowed as a key.</p>"
        "<p>A <b>tuple</b> of symptom strings is safe if every part is immutable.</p>"
        "<p>If order should not matter, sort the symptoms first to make a "
        "canonical key.</p>"
    ),
    "R3": (
        "<p>Python <b>may</b> reuse identical string objects (called <b>interning</b>) "
        "to save memory. It is an optimization, <b>not a guarantee</b>.</p>"
        "<div class=\"step-pre\">label_a = \"Type 2 Diabetes\"\n"
        "label_b = \"Type 2 Diabetes\"\n"
        "print(label_a == label_b)  # True — same text\n"
        "print(label_a is label_b)  # may be True or False — do not depend on it</div>"
        "<p>For diagnosis text, always use <code>==</code>. <code>is</code> asks "
        "whether two names point to the same object, not whether their words match.</p>"
        "<p>For thousands of repeated labels, use a controlled code such as "
        "<code>\"E11\"</code> with a separate label table. That is a reliable storage "
        "design; interning is not.</p>"
    ),
    "R4": (
        "<p><code>==</code> asks: “Do these have the <b>same value</b>?”</p>"
        "<p><code>is</code> asks: “Are these the <b>exact same object</b> in memory?”</p>"
        "<div class=\"step-pre\">a = [1, 2]\n"
        "b = [1, 2]\n"
        "c = a\n\n"
        "print(a == b)   # True  — same values\n"
        "print(a is b)   # False — different list objects\n"
        "print(a is c)   # True  — same object\n\n"
        "x = None\n"
        "print(x is None)    # True — correct way\n"
        "# print(x == None)  # works, but style guide says use `is`</div>"
        "<table class=\"data-tbl\">"
        "<tr><th></th><th><code>==</code></th><th><code>is</code></th></tr>"
        "<tr><td>Means</td><td>Equal values</td><td>Same object identity</td></tr>"
        "<tr><td>Use for</td><td>IDs, names, numbers, strings</td>"
        "<td><code>None</code> (and rare singletons)</td></tr>"
        "</table>"
        "<p>Compare patient IDs and names with <b>==</b>. Use <code>is None</code> "
        "for missing values — not <code>is</code> for ordinary strings.</p>"
    ),
    "R5": (
        "<p>A list is a <b>dynamic array</b>: a row of patient cards with room to "
        "grow. Adding at the front makes every existing card slide over.</p>"
        "<table class=\"data-tbl\">"
        "<tr><th>List action</th><th>Typical cost</th><th>Why</th></tr>"
        "<tr><td><code>append(record)</code></td><td>Amortized <b>O(1)</b></td><td>Uses the next slot; occasional resize</td></tr>"
        "<tr><td><code>insert(0, record)</code></td><td><b>O(n)</b></td><td>All cards shift right</td></tr>"
        "<tr><td><code>insert(middle, record)</code></td><td><b>O(n)</b></td><td>Cards after that spot shift</td></tr>"
        "<tr><td><code>insert(len(records), record)</code></td><td>Amortized <b>O(1)</b></td><td>Same idea as append</td></tr>"
        "</table>"
        "<div class=\"step-pre\">from collections import deque\n"
        "queue = deque([\"P1\", \"P2\"])\n"
        "queue.append(\"P3\")      # fast at end\n"
        "next_patient = queue.popleft()  # fast at front</div>"
        "<p>A tuple is <b>immutable</b>: <code>snapshot + (\"P3\",)</code> builds a "
        "<b>new object</b>, copying the old items. Choose <code>deque</code> for queues, "
        "a list for end-heavy edits, and a tuple for fixed snapshots.</p>"
    ),
    "R6": (
        "<p>An empty tuple <code>()</code> is usually smaller than an empty list "
        "<code>[]</code>. A list needs mutable-container bookkeeping so it can grow.</p>"
        "<div class=\"step-pre\"># INPUT — run on your own Python\n"
        "import sys\n"
        "print(sys.getsizeof([]))\n"
        "print(sys.getsizeof(()))\n"
        "\n"
        "# OUTPUT — example only; sizes vary by Python build\n"
        "56\n"
        "40</div>"
        "<p><code>sys.getsizeof</code> reports the <b>shallow size</b>: it does not "
        "include items nested inside the collection. CPython may also share its empty "
        "tuple, but do not assume every Python implementation does.</p>"
        "<p>A few bytes are tiny once, but millions of empty records multiply that "
        "cost. <b>Measure locally</b> before choosing a representation.</p>"
    ),
    "R7": (
        "<p>CPython normally frees an object when its <b>reference count</b> becomes "
        "zero. A circle is different: each object keeps the other one's count above zero.</p>"
        "<div class=\"step-pre\"># Patient ↔ Doctor cycle\n"
        "patient.doctor = doctor\n"
        "doctor.patient = patient\n"
        "del patient\n"
        "del doctor\n"
        "# The two unreachable objects still point to each other.</div>"
        "<p>Python's <b>cyclic garbage collector (GC)</b> later finds and reclaims "
        "these unreachable islands. It is not a leak as long as nothing else can reach them.</p>"
        "<p>If a back-link should not keep an object alive, use <code>weakref</code> "
        "(a reference that does not own the object), or design one-way ownership.</p>"
    ),
    "R8": (
        "<p>A generator keeps a bookmark: locals + “what to run next.”</p>"
        "<p>Each <code>next</code> continues from the pause (<code>yield</code>).</p>"
        "<div class=\"step-pre\">def patient_ids(n):\n"
        "    for i in range(1, n + 1):\n"
        "        yield f\"P{i:03d}\"   # pause after each id\n\n"
        "stream = patient_ids(3)\n"
        "print(next(stream))   # P001\n"
        "print(next(stream))   # P002\n"
        "print(list(stream))   # ['P003'] — rest of the stream</div>"
        "<table class=\"data-tbl\">"
        "<tr><th></th><th>Build a full list</th><th>Generator stream</th></tr>"
        "<tr><td>Memory</td><td>Holds everyone</td><td>One (or a few) at a time</td></tr>"
        "<tr><td>Reuse</td><td>Can loop again</td><td>Usually consume once</td></tr>"
        "</table>"
        "<p>Great for streaming patient batches without building a giant list. "
        "Values are produced lazily and usually consumed once.</p>"
    ),
    "R9": (
        "<p>Python searches names in this order: <b>L</b>ocal → <b>E</b>nclosing → "
        "<b>G</b>lobal → <b>B</b>uiltins (LEGB).</p>"
        "<div class=\"step-pre\">threshold = 90  # Global\n"
        "\n"
        "def diagnose(patient_value):\n"
        "    threshold = 100  # Enclosing\n"
        "    def is_high_risk():\n"
        "        return patient_value &gt; threshold\n"
        "    return is_high_risk()\n"
        "\n"
        "# INPUT: diagnose(105)\n"
        "# OUTPUT: True — uses enclosing threshold 100, not global 90</div>"
        "<p>If <code>is_high_risk</code> creates its own <code>threshold</code>, its "
        "<b>local</b> name wins. To <b>rebind</b> the enclosing threshold, write "
        "<code>nonlocal threshold</code>; merely reading it needs no <code>nonlocal</code>.</p>"
    ),
    "R10": (
        "<p>Both forms look up the same dictionary key. They differ only when the "
        "key is <b>missing</b>.</p>"
        "<div class=\"step-pre\">patient = {\"name\": \"Asha\", \"blood_type\": \"A+\"}\n"
        "missing = {\"name\": \"Ben\"}\n"
        "\n"
        "# Existing key: both return \"A+\"\n"
        "print(patient[\"blood_type\"])\n"
        "print(patient.get(\"blood_type\"))\n"
        "\n"
        "# Missing key\n"
        "print(missing.get(\"blood_type\"))  # None\n"
        "# missing[\"blood_type\"]            # KeyError</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Access</th><th>Existing blood type</th><th>Missing blood type</th><th>Use for</th></tr>"
        "<tr><td><code>patient[\"blood_type\"]</code></td><td><code>\"A+\"</code></td><td><b>KeyError</b></td><td>Required, validated field</td></tr>"
        "<tr><td><code>patient.get(\"blood_type\")</code></td><td><code>\"A+\"</code></td><td><code>None</code> / chosen default</td><td>Truly optional field</td></tr>"
        "</table>"
        "<p>Do not replace an unknown blood type with a fake value. Treat missing required "
        "data as a data-quality problem.</p>"
    ),
    "Q8.1": (
        "<p>Build a small system like a tidy clinic desk: one class owns its records, "
        "checks incoming data, and offers small, testable actions. This is an "
        "<b>educational example</b>, not clinical software.</p>"
        "<table class=\"data-tbl\">"
        "<tr><th>Part</th><th>What it demonstrates</th></tr>"
        "<tr><td><code>patients: dict[str, dict]</code></td><td>Useful data types and type hints</td></tr>"
        "<tr><td><code>add_patient(**patient_data)</code></td><td>Named flexible input, validation, duplicate checks</td></tr>"
        "<tr><td><code>update_vitals(id, *vitals, **metadata)</code></td><td>Extra values, named metadata, immutable tuple snapshot</td></tr>"
        "<tr><td>Comprehension / <code>filter</code></td><td>Select matching report records</td></tr>"
        "<tr><td><code>map</code> / <code>reduce</code></td><td>Run a batch / combine a clear summary</td></tr>"
        "<tr><td><code>generate_report()</code></td><td>Generator: yield records one at a time</td></tr>"
        "<tr><td><code>batch_process(operations)</code></td><td>Apply several operations and collect results</td></tr>"
        "</table>"
        "<div class=\"step-pre\"># INPUT — tiny end-to-end flow\n"
        "system.add_patient(id=\"P1\", name=\"Asha\", age=42)\n"
        "system.update_vitals(\"P1\", 120, 80, 98.6, at=\"09:00\")\n"
        "report = list(system.generate_report(lambda p: p[\"age\"] &gt;= 40))\n"
        "\n"
        "# OUTPUT — one lazily produced record\n"
        "# [{\"id\": \"P1\", \"name\": \"Asha\", \"age\": 42,\n"
        "#   \"vitals\": [{\"values\": (120, 80, 98.6), \"at\": \"09:00\"}]}]</div>"
        "<p>Store vitals as a <b>tuple</b> inside each snapshot so the values cannot be "
        "edited accidentally after capture. Validate IDs and basic shape at the boundary; "
        "keep any real medical rules outside this learning demo.</p>"
    ),
}


def apply_kid_answers(questions: list[dict]) -> None:
    """Overlay kid-friendly HTML answers onto question dicts in place."""
    for q in questions:
        html = KID_ANSWERS.get(q.get("id", ""))
        if html:
            q["answer"] = html
