"""Real-life workplace examples for every slide — indented code blocks."""

from slide_csharp_popups import csharp_compare_btn
from slide_io import io_split

REAL_LIFE: dict[int, str] = {
    1: (
        "<b>Order automation bot:</b> A logistics team runs a nightly sync — "
        "no Visual Studio build; CPython executes the <code>.py</code> directly — "
        "each step with <b>input → output</b>."
        "<p><b>1) Run the script directly</b><br>"
        "Python reads <code>.py</code> line by line — no compile step like C#. "
        "The <code>if __name__ == \"__main__\"</code> guard runs "
        "<code>sync_orders()</code> only when you execute this file.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'if __name__ == "__main__":\n'
        "    sync_orders()\n"
        "\n"
        "# OUTPUT\n"
        "(terminal) → sync starts; orders fetched and saved"
        "</div>"
        "<p><b>2) Fetch orders from the API</b><br>"
        "Imagine a function that returns a list of order dicts — "
        "that list is what the loop walks through.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "orders = fetch_from_api()\n"
        "\n"
        "# OUTPUT\n"
        "orders → [{'id': 1, 'status': 'NEW'}, {'id': 2, 'status': 'DONE'}]"
        "</div>"
        "<p><b>3) Branch on status — save or skip</b><br>"
        "Only <code>NEW</code> orders go to the database; others are skipped.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "for order in orders:\n"
        '    if order["status"] == "NEW":\n'
        "        save_to_db(order)\n"
        "    else:\n"
        "        skip(order)\n"
        "\n"
        "# OUTPUT\n"
        "saved → order 1; skipped → order 2"
        "</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Step</th><th>Job</th><th>Output here</th></tr>"
        "<tr><td>Direct run</td><td>Execute <code>.py</code> without build</td>"
        "<td>Sync starts</td></tr>"
        "<tr><td>Fetch</td><td>Get orders from API</td>"
        "<td>List of order dicts</td></tr>"
        "<tr><td>Branch</td><td><code>NEW</code> → save, else skip</td>"
        "<td>1 saved, 1 skipped</td></tr>"
        "</table>"
    ),
    2: (
        "<b>New laptop day-1:</b> Install Python, verify tools, then run the setup check — "
        "each command with <b>input → output</b>."
        "<p><b>1) Check Python version</b><br>"
        "Confirms CPython is on your PATH before you open any project.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "python --version\n"
        "\n"
        "# OUTPUT\n"
        "Python 3.12.x"
        "</div>"
        "<p><b>2) Check pip</b><br>"
        "Package installer must work so you can install project dependencies.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "pip --version\n"
        "\n"
        "# OUTPUT\n"
        "pip 24.x from ... (python 3.12)"
        "</div>"
        "<p><b>3) Run the setup check script</b><br>"
        "In Cursor: Select Interpreter → Python 3.12, then run the team setup script.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "python Projects/00_windows_setup.py\n"
        "\n"
        "# OUTPUT\n"
        "Setup OK — interpreter and paths verified"
        "</div>"
    ),
    3: (
        "<b>Training week plan:</b> Same flow a team uses — docs → kata → real repo — "
        "each stage with <b>input → output</b>."
        "<p><b>1) Theory — read the slides</b><br>"
        "Open the training deck in a browser before touching code.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "# open PythonTraining.html in browser\n"
        "\n"
        "# OUTPUT\n"
        "Slides loaded — concepts for the week"
        "</div>"
        "<p><b>2) Short practice script</b><br>"
        "Run a small kata to cement datatypes from slide 5.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "python Projects/01_datatypes.py\n"
        "\n"
        "# OUTPUT\n"
        "list / tuple / dict examples printed"
        "</div>"
        "<p><b>3) Deeper practice — real repo file</b><br>"
        "Move into the full codebase and run a collections module.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "python Python-Set2/pythonBasics/MyCollections/mylist.py\n"
        "\n"
        "# OUTPUT\n"
        "List methods demo — append, pop, slice"
        "</div>"
    ),
    4: (
        "<b>PR review gate:</b> CI enforces PEP 8 / docstrings before merge — "
        "each check with <b>input → output</b>."
        "<p><b>1) Function with docstring (PEP 257)</b><br>"
        "Every public function gets a one-line docstring so reviewers and tools know what it does.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def calc_gst(amount):\n"
        '    """Return 18% GST for the given amount."""\n'
        "    return amount * 0.18\n"
        "\n"
        "calc_gst(1000)\n"
        "\n"
        "# OUTPUT\n"
        "180.0"
        "</div>"
        "<p><b>2) CI lint — <code>ruff check</code> (PEP 8)</b><br>"
        "Automated style check runs on every pull request before merge.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "ruff check .\n"
        "\n"
        "# OUTPUT\n"
        "All checks passed!  (or line numbers for fixes)"
        "</div>"
        "<p><b>3) Version pins in <code>pyproject.toml</code> (PEP 621)</b><br>"
        "Dependencies and tool versions live in one config file — not scattered README notes.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "# pyproject.toml lists python &gt;=3.12, ruff, mypy\n"
        "\n"
        "# OUTPUT\n"
        "CI installs same versions on every build"
        "</div>"
    ),
    5: (
        "<b>E-commerce checkout:</b> List grows; GPS pin is a fixed tuple; order can mix types — "
        "each datatype with <b>input → output</b>."
        "<p><b>1) Cart list — grows with <code>append</code></b><br>"
        "A shopping cart is a list of dicts; you can add items after checkout starts.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'cart = [{"sku": "A1", "qty": 2}, {"sku": "B2", "qty": 1}]\n'
        'cart.append({"sku": "C3", "qty": 3})\n'
        "\n"
        "# OUTPUT\n"
        "cart → [{'sku': 'A1', 'qty': 2}, {'sku': 'B2', 'qty': 1}, {'sku': 'C3', 'qty': 3}]"
        "</div>"
        "<p><b>2) Delivery GPS — fixed tuple</b><br>"
        "Coordinates should not change accidentally — a tuple has no <code>append</code>.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "delivery_pin = (12.97, 80.22)\n"
        "\n"
        "# OUTPUT\n"
        "delivery_pin → (12.97, 80.22)  # immutable"
        "</div>"
        "<p><b>3) Heterogeneous order record</b><br>"
        "One list can hold an int id, a string status, and a nested list of vendors.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'order = [101, "SHIPPED", ["Google", "Amazon"]]\n'
        "\n"
        "# OUTPUT\n"
        "order[0] → 101\n"
        'order[1] → "SHIPPED"\n'
        "order[2] → ['Google', 'Amazon']"
        "</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Type</th><th>Real-life use</th><th>Output here</th></tr>"
        "<tr><td><code>list</code></td><td>Cart — grows</td>"
        "<td>3 items after append</td></tr>"
        "<tr><td><code>tuple</code></td><td>GPS pin — fixed</td>"
        "<td><code>(12.97, 80.22)</code></td></tr>"
        "<tr><td>Mixed list</td><td>Order id + status + vendors</td>"
        "<td><code>[101, 'SHIPPED', [...]]</code></td></tr>"
        "</table>"
    ),
    6: (
        "<b>Payment API contract:</b> Type hints + mypy catch bad calls before production — "
        "each case with <b>input → output</b>."
        "<p><b>1) Typed function — the contract</b><br>"
        "Annotations say <code>amount</code> must be a <code>Decimal</code> and "
        "<code>currency</code> a <code>str</code>; mypy checks callers match.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from decimal import Decimal\n"
        "\n"
        "def charge(amount: Decimal, currency: str) -> str:\n"
        '    return f"Charged {amount} {currency}"\n'
        "\n"
        "# OUTPUT\n"
        "(function defined — ready for mypy and runtime)"
        "</div>"
        "<p><b>2) Bad call — wrong types</b><br>"
        "Passing a string and an int swaps the expected types; Python still runs, mypy does not.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'result = charge("100", 91)\n'
        "print(result)\n"
        "\n"
        "# OUTPUT (python app.py — hints ignored)\n"
        "Charged 100 91"
        "</div>"
        '<div class="step-pre">'
        "# INPUT\n"
        "mypy app.py\n"
        "\n"
        "# OUTPUT (mypy — not executed)\n"
        'error: Argument 1 … expected "Decimal"\n'
        'error: Argument 2 … expected "str"\n'
        "Found 2 errors in 1 file"
        "</div>"
        "<p><b>3) Correct call — both happy</b><br>"
        "Use <code>Decimal(\"100.00\")</code> for money; mypy passes and Python prints the receipt.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'charge(Decimal("100.00"), "INR")\n'
        "\n"
        "# OUTPUT\n"
        "Charged 100.00 INR  — OK for mypy and Python"
        "</div>"
        '<table class="data-tbl">'
        "<tr><th>Case</th><th>Input (what you type)</th><th>Output (what you see)</th></tr>"
        "<tr>"
        "<td><b>Without mypy</b></td>"
        "<td><code>python app.py</code></td>"
        "<td>Hints ignored — program <b>runs</b>. Example print:<br>"
        "<code>Charged 100 91</code><br>"
        "(no type error from Python itself)</td>"
        "</tr>"
        "<tr>"
        "<td><b>With mypy</b></td>"
        "<td><code>mypy app.py</code></td>"
        "<td>Type errors reported — program is <b>not</b> executed. Example:<br>"
        "<code>error: Argument 1 … expected \"Decimal\"</code><br>"
        "<code>error: Argument 2 … expected \"str\"</code><br>"
        "<code>Found 2 errors in 1 file</code></td>"
        "</tr>"
        "<tr>"
        "<td><b>Correct call</b></td>"
        "<td><code>charge(Decimal(\"100.00\"), \"INR\")</code><br>"
        "then <code>python app.py</code></td>"
        "<td><code>Charged 100.00 INR</code> — OK for mypy and Python</td>"
        "</tr>"
        "</table>"
        '<p class="step-result">'
        "<b>Remember:</b> mypy does <b>not</b> run automatically with Python. "
        "You run it separately (or in CI)."
        "</p>"
    ),
    7: (
        "<b>Invoice math:</b> Arithmetic, floor division, identity, membership, walrus — "
        "each operator with <b>input → output</b>."
        "<p><b>1) Multiply and floor divide</b><br>"
        "<code>*</code> gives the line total; <code>//</code> gives whole pages when packing items.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "qty = 3\n"
        "price = 250\n"
        "total = qty * price\n"
        "pages = 25 // 10\n"
        "\n"
        "# OUTPUT\n"
        "total → 750\n"
        "pages → 2"
        "</div>"
        "<p><b>2) <code>is None</code> / <code>is not None</code></b><br>"
        "Check whether a value is empty (<code>None</code>) or has a real customer name.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "status = None\n"
        "if status is None:\n"
        '    print("pending")\n'
        "\n"
        'customer = "Ravi"\n'
        "if customer is not None:\n"
        '    print("bill to", customer)\n'
        "\n"
        "# OUTPUT\n"
        "pending\n"
        "bill to Ravi"
        "</div>"
        "<p><b>3) Membership — <code>in</code></b><br>"
        "See if a tax code is in the allowed list before applying it.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'tax_codes = ["GST", "CGST"]\n'
        'if "GST" in tax_codes:\n'
        '    print("apply GST")\n'
        "\n"
        "# OUTPUT\n"
        "apply GST"
        "</div>"
        "<p><b>4) Walrus <code>:=</code> — assign inside <code>if</code></b><br>"
        "Count items once and use the count in the same condition — no double <code>len()</code>.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'items = ["Pen", "Notebook", "Bag"]\n'
        "if (count := len(items)) >= 3:\n"
        '    print(f"Bulk order: {count} lines")\n'
        "\n"
        "# OUTPUT\n"
        "Bulk order: 3 lines"
        "</div>"
        '<p class="step-result">'
        "<b>None:</b> <code>is None</code> = empty; <code>is not None</code> = has a value.<br>"
        "<b>Walrus <code>:=</code>:</b> assign inside <code>if</code>/<code>while</code> so you do not call "
        "<code>len()</code> (or <code>input()</code>) twice. Use when the value is needed in the condition "
        "<b>and</b> in the body. Do not use for every assignment — normal <code>=</code> is clearer then."
        "</p>"
    ),
    8: (
        "<b>CSV import job:</b> Branch, skip bad rows, stop early, stub unfinished work — "
        "each control flow with <b>input → output</b>."
        "<p><b>1) <code>continue</code> — skip bad rows</b><br>"
        "If a row has no <code>id</code>, jump to the next row without processing.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'rows = [{"id": "", "country": "IN"}, {"id": "42", "country": "IN"}]\n'
        "processed = []\n"
        "for row in rows:\n"
        '    if not row.get("id"):\n'
        "        continue\n"
        "    processed.append(row)\n"
        "\n"
        "# OUTPUT\n"
        "processed → [{'id': '42', 'country': 'IN'}]"
        "</div>"
        "<p><b>2) <code>break</code> — stop after 10,000 rows</b><br>"
        "Protect the job from running forever on a huge file.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "for i, row in enumerate(reader):\n"
        "    if i >= 10000:\n"
        "        break\n"
        "    process(row)\n"
        "\n"
        "# OUTPUT\n"
        "processed → rows 0 … 9999 only"
        "</div>"
        "<p><b>3) <code>if</code> / <code>elif</code> / <code>else</code> — country tax</b><br>"
        "Pick the right tax function based on the country column.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'row = {"country": "IN"}\n'
        'if row["country"] == "IN":\n'
        "    apply_in_tax(row)\n"
        'elif row["country"] == "US":\n'
        "    apply_us_tax(row)\n"
        "else:\n"
        "    apply_default_tax(row)\n"
        "\n"
        "# OUTPUT\n"
        "apply_in_tax(row) called → IN GST applied"
        "</div>"
        "<p><b>4) <code>pass</code> — stub for later</b><br>"
        "Placeholder so the file parses while the coupon logic is still being written.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def apply_coupon():\n"
        "    pass\n"
        "\n"
        "# OUTPUT\n"
        "(no error — function exists, does nothing yet)"
        "</div>"
    ),
    9: (
        "<b>Salary sheet transform:</b> Comprehension vs loop; generator for huge files — "
        "each pattern with <b>input → output</b>."
        "<p><b>1) Loop — build net pay list</b><br>"
        "Classic four-line loop: zip gross and tax, keep positive gross only.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "gross = [50000, 0, 60000]\n"
        "taxes = [5000, 0, 6000]\n"
        "net = []\n"
        "for g, tax in zip(gross, taxes):\n"
        "    if g > 0:\n"
        "        net.append(g - tax)\n"
        "\n"
        "# OUTPUT\n"
        "net → [45000, 54000]"
        "</div>"
        "<p><b>2) List comprehension — same result, one line</b><br>"
        "Reads like a formula: subtract tax for each pair where gross &gt; 0.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "net = [g - tax for g, tax in zip(gross, taxes) if g > 0]\n"
        "\n"
        "# OUTPUT\n"
        "net → [45000, 54000]"
        "</div>"
        "<p><b>3) Generator with <code>yield</code> — one row at a time</b><br>"
        "For a million-line CSV, build results lazily — only one row in memory at a time.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def parse_lines(f):\n"
        "    for line in f:\n"
        "        yield parse(line)\n"
        "\n"
        "# use:\n"
        "# for row in parse_lines(open('huge.csv')):\n"
        "#     process(row)\n"
        "\n"
        "# OUTPUT\n"
        "one parsed row per loop turn — RAM stays low"
        "</div>"
        '<p class="step-result"><b>Rule:</b> if the function body uses <b>yield</b> → it is a <b>GENERATOR</b> function.</p>'
    ),
    10: (
        "<b>Invoice tax helper:</b> Pure function + higher-order use in a report — "
        "each layer with <b>input → output</b>."
        "<p><b>1) Pure function — <code>calc_gst</code></b><br>"
        "Same amount in always gives the same GST out — no hidden state.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def calc_gst(amount):\n"
        "    return amount * 0.18\n"
        "\n"
        "calc_gst(1000)\n"
        "\n"
        "# OUTPUT\n"
        "180.0"
        "</div>"
        "<p><b>2) Higher-order — pass <code>tax_fn</code> into <code>build_report</code></b><br>"
        "The report builder does not hard-code GST — it calls whatever tax function you give it.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def build_report(amounts, tax_fn):\n"
        "    rows = []\n"
        "    for amount in amounts:\n"
        "        rows.append({\"amount\": amount, \"gst\": tax_fn(amount)})\n"
        "    return rows\n"
        "\n"
        "build_report([100, 200], calc_gst)\n"
        "\n"
        "# OUTPUT\n"
        "rows → [{'amount': 100, 'gst': 18.0}, {'amount': 200, 'gst': 36.0}]"
        "</div>"
        "<p><b>3) Full pipeline</b><br>"
        "Two invoice lines → one report list ready for PDF or email.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "report = build_report([100, 200], calc_gst)\n"
        "\n"
        "# OUTPUT\n"
        "report → [{'amount': 100, 'gst': 18.0}, {'amount': 200, 'gst': 36.0}]"
        "</div>"
    ),
    11: (
        "<b>Report pipeline:</b> Clean lines, drop empties, find max sale, zip headers — "
        "each tool explained separately with <b>input → output</b>."
        "<p><b>1) <code>map</code> — transform every item</b><br>"
        "Calls a function on each value. Here <code>str.strip</code> removes spaces. "
        "<code>map</code> is lazy, so wrap with <code>list(...)</code>. "
        "Empty <code>''</code> stays — strip only cleans spaces, it does not drop items.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "lines = [\"  A  \", \"\", \"  B  \"]\n"
        "cleaned = list(map(str.strip, lines))\n"
        "\n"
        "# OUTPUT\n"
        "cleaned → ['A', '', 'B']"
        "</div>"
        "<p><b>2) <code>filter</code> — keep only items that pass a test</b><br>"
        "Think of a <b>bouncer at a door</b>: walk through a list, and keep only the items "
        "where your test says <b>True</b>. Skip the rest.</p>"
        '<div class="step-pre">'
        "# INPUT — keep even numbers\n"
        "def is_even(n):\n"
        "    return n % 2 == 0   # True for 2, 4, 6...\n"
        "\n"
        "nums = [1, 2, 3, 4, 5, 6]\n"
        "evens = list(filter(is_even, nums))\n"
        "\n"
        "# OUTPUT\n"
        "evens → [2, 4, 6]"
        "</div>"
        "<p><b>2b) Same idea — keep fever temperatures</b><br>"
        "The test can be any rule. Here: keep only readings above 100.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def has_fever(temp):\n"
        "    return temp > 100\n"
        "\n"
        "temps = [98.6, 99.1, 101.2, 100.5]\n"
        "fever = list(filter(has_fever, temps))\n"
        "\n"
        "# OUTPUT\n"
        "fever → [101.2, 100.5]"
        "</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Step</th><th>What happens</th></tr>"
        "<tr><td>1</td><td>Take one item from the list</td></tr>"
        "<tr><td>2</td><td>Run your test function → True or False</td></tr>"
        "<tr><td>3</td><td>True → keep it; False → skip it</td></tr>"
        "</table>"
        "<p><b>Rule:</b> <code>filter(test_function, items)</code> — "
        "not every item changes; only matching items are kept.</p>"
        "<p><b>3) <code>max(sales, key=…)</code> — pick the best dict</b><br>"
        "<code>sales</code> is the list <code>max</code> walks through. "
        "Whole dicts cannot usefully be compared with <code>&gt;</code>, so you need "
        "<code>key=</code>. "
        "<code>lambda r: r[\"amount\"]</code> means: for each dict <code>r</code>, use its "
        "<code>amount</code>. <code>max</code> compares <code>50000</code> vs <code>800</code> "
        "and returns the <b>original dict</b> (not just the number).</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "sales = [\n"
        '    {"item": "Laptop", "amount": 50000},\n'
        '    {"item": "Mouse", "amount": 800},\n'
        "]\n"
        "top = max(sales, key=lambda r: r[\"amount\"])\n"
        "\n"
        "# OUTPUT\n"
        "top → {'item': 'Laptop', 'amount': 50000}"
        "</div>"
        "<p><b>4) <code>dict(zip(...))</code> — headers + row → record</b><br>"
        "<code>zip</code> pairs by position (1st with 1st, 2nd with 2nd; stops at shortest). "
        "<code>dict</code> turns those <code>(key, value)</code> pairs into a dictionary "
        "(common CSV-style pattern).</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'headers = ["name", "qty"]\n'
        'row = ["Pen", "12"]\n'
        "pairs = list(zip(headers, row))\n"
        "record = dict(zip(headers, row))\n"
        "\n"
        "# OUTPUT\n"
        "pairs  → [('name', 'Pen'), ('qty', '12')]\n"
        "record → {'name': 'Pen', 'qty': '12'}"
        "</div>"
        "<p><b>5) <code>zip(*rows)</code> — unpack rows into columns</b><br>"
        "<code>*</code> opens the list so <code>zip</code> gets each row as its own argument. "
        "That turns rows into columns (handy for averages per field).</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "readings = [\n"
        "    (120, 80, 98.6),\n"
        "    (115, 75, 99.1),\n"
        "]\n"
        "sys_list, dia_list, temps = zip(*readings)\n"
        "\n"
        "# OUTPUT\n"
        "sys_list → (120, 115)\n"
        "dia_list → (80, 75)\n"
        "temps    → (98.6, 99.1)\n"
        "# zip(*readings) == zip(row1, row2)"
        "</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Tool</th><th>Job</th><th>Output here</th></tr>"
        "<tr><td><code>map</code></td><td>Transform every item</td><td><code>['A', '', 'B']</code></td></tr>"
        "<tr><td><code>filter</code></td><td>Keep items that pass a test</td>"
        "<td><code>[2, 4, 6]</code> or fever temps</td></tr>"
        "<tr><td><code>max(..., key=…)</code></td><td>Best item by a field</td>"
        "<td><code>{'item': 'Laptop', 'amount': 50000}</code></td></tr>"
        "<tr><td><code>dict(zip(...))</code></td><td>Headers + row → record</td>"
        "<td><code>{'name': 'Pen', 'qty': '12'}</code></td></tr>"
        "<tr><td><code>zip(*rows)</code></td><td>Rows → columns</td>"
        "<td><code>(120, 115)</code>, <code>(80, 75)</code>, …</td></tr>"
        "</table>"
    ),
    12: (
        "<b>Support dashboard:</b> Count statuses, group by assignee, chat buffer, light record — "
        "each collection with <b>input → output</b>."
        "<p><b>1) <code>Counter</code> — status pie chart</b><br>"
        "Pass a list of statuses to <code>Counter</code> — it tallies how many times each value "
        "appears (like counting colored chips for a pie chart). Use <code>print</code> to see the result.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from collections import Counter\n"
        'statuses = ["open", "open", "closed", "open"]\n'
        "pie = Counter(statuses)\n"
        "print(pie)\n"
        "\n"
        "# OUTPUT\n"
        "Counter({'open': 3, 'closed': 1})"
        "</div>"
        "<p><b>2) <code>defaultdict(list)</code> — group by assignee</b><br>"
        "Append ticket ids per person — if the key is missing, "
        "<code>defaultdict(list)</code> auto-creates an empty list (no <code>KeyError</code>, "
        "no manual <code>if key not in dict</code>). "
        "See <b>Common mistakes</b> below for without vs with comparison and the <b>one trap</b>.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from collections import defaultdict\n"
        "by_assignee = defaultdict(list)\n"
        'by_assignee["Ravi"].append(101)   # first touch → creates []\n'
        'by_assignee["Anu"].append(102)\n'
        "print(dict(by_assignee))\n"
        "\n"
        "# OUTPUT\n"
        "{'Ravi': [101], 'Anu': [102]}"
        "</div>"
        "<p><b>3) <code>deque()</code> first — then optional <code>maxlen</code></b><br>"
        "<code>maxlen</code> is <b>not required</b>. Use plain <code>deque()</code> for a normal queue. "
        "Add <code>maxlen</code> only when you want a rolling buffer that drops the oldest item.</p>"
        '<div class="mc-row">'
        '<div class="mc-col mc-good"><span class="mc-lbl">1) deque() — no max</span>'
        '<div class="step-pre">'
        "# INPUT\n"
        "from collections import deque\n"
        "chat = deque()            # grows freely\n"
        'chat.append("hi")\n'
        'chat.append("ticket #42")\n'
        "print(list(chat))\n"
        "\n"
        "# OUTPUT\n"
        "['hi', 'ticket #42']"
        "</div></div>"
        '<div class="mc-col mc-good"><span class="mc-lbl">2) deque(maxlen=…) — rolling</span>'
        '<div class="step-pre">'
        "# INPUT\n"
        "from collections import deque\n"
        "chat = deque(maxlen=2)    # keep last 2 only\n"
        'chat.append("hi")\n'
        'chat.append("ticket #42")\n'
        'chat.append("bye")      # "hi" dropped\n'
        "print(list(chat))\n"
        "\n"
        "# OUTPUT\n"
        "['ticket #42', 'bye']"
        "</div></div></div>"
        '<p class="step-result"><b>Rule:</b> <code>deque()</code> = unlimited. '
        '<code>deque(maxlen=n)</code> = keep last <code>n</code> items only.</p>'
        "<p><b>4) <code>namedtuple</code> — light ticket record</b><br>"
        "Fixed fields like a mini struct — access with <code>t.id</code> and <code>t.status</code>.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from collections import namedtuple\n"
        'Ticket = namedtuple("Ticket", "id status")\n'
        't = Ticket(101, "open")\n'
        "print(t)\n"
        "\n"
        "# OUTPUT\n"
        "Ticket(id=101, status='open')"
        "</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>Tool</th><th>Job</th><th>Output here</th></tr>"
        "<tr><td><code>Counter</code></td><td>Count statuses</td>"
        "<td><code>{'open': 3, 'closed': 1}</code></td></tr>"
        "<tr><td><code>defaultdict</code></td><td>Group by assignee</td>"
        "<td><code>{'Ravi': [101], 'Anu': [102]}</code></td></tr>"
        "<tr><td><code>deque</code></td><td>Fast both ends; optional maxlen buffer</td>"
        "<td><code>deque()</code> or <code>deque(maxlen=2)</code></td></tr>"
        "<tr><td><code>namedtuple</code></td><td>Light record</td>"
        "<td><code>Ticket(id=101, status='open')</code></td></tr>"
        "</table>"
    ),
    13: (
        "<b>Overnight batch:</b> Global cache grows forever — fix with cleanup / weakref / <code>with</code> — "
        "each pattern with <b>input → output</b>."
        "<p><b>1) Problem — cache never clears</b><br>"
        "Storing every parsed JSON in a global dict makes RAM climb all night.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "cache = {}\n"
        "\n"
        "def process(order_id, huge_json):\n"
        "    cache[order_id] = huge_json\n"
        "\n"
        "process(1, {\"lines\": 5000})\n"
        "process(2, {\"lines\": 5000})\n"
        "\n"
        "# OUTPUT\n"
        "len(cache) → 2  (grows forever — memory leak risk)"
        "</div>"
        "<p><b>2) Fix — stream file with <code>with</code> + <code>yield</code></b><br>"
        "Read one line at a time; file closes when the block exits — no waiting for garbage collection.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def export_orders(path):\n"
        "    with open(path, encoding=\"utf-8\") as f:\n"
        "        for line in f:\n"
        "            yield line\n"
        "\n"
        "# OUTPUT\n"
        "one line per ask; file closed after block — RAM stays flat"
        "</div>"
    ),
    14: (
        "<b>Create-user API:</b> Pydantic coerces and validates — no hand-written if-checks — "
        "each step with <b>input → output</b>."
        "<p><b>1) Model — fields and validator</b><br>"
        "Declare types once. <code>Field(ge=18)</code> = age must be ≥ 18. "
        "<code>@field_validator(\"email\")</code> = custom rule that runs on the email value "
        "<b>before</b> it is stored — here we <b>normalize</b> it to lowercase so "
        "<code>Anu@Co.COM</code> and <code>anu@co.com</code> become the same stored value.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from pydantic import BaseModel, Field, field_validator\n"
        "\n"
        "class UserCreate(BaseModel):\n"
        "    email: str\n"
        "    age: int = Field(ge=18)   # built-in rule: age &gt;= 18\n"
        "\n"
        "    @field_validator(\"email\")   # custom rule for email only\n"
        "    @classmethod\n"
        "    def lower_email(cls, v):\n"
        "        # PURPOSE: clean / normalize the value (not reject it)\n"
        "        # v = raw email from the client; return what to store\n"
        "        return v.lower()\n"
        "\n"
        "# OUTPUT\n"
        "(model ready — validates on model_validate)"
        "</div>"
        "<p style=\"font-size:12px;color:#334155;margin:6px 0 0;line-height:1.45\">"
        "<b>Why <code>@classmethod</code>?</b> Pydantic calls the validator on the class "
        "(no instance yet). <code>v</code> is the incoming field value; what you "
        "<code>return</code> becomes the final field value on the model."
        "</p>"
        "<p><b>1b) Does <code>lower_email</code> run automatically?</b><br>"
        "<b>Yes.</b> You never call <code>lower_email(...)</code> yourself. "
        "It runs when Pydantic validates — "
        "<code>model_validate(...)</code>, <code>UserCreate(...)</code>, or FastAPI parsing a JSON body. "
        "The decorator <code>@field_validator(\"email\")</code> <b>registers</b> the method; "
        "Pydantic invokes it for you.</p>"
        "<p><b>1c) More than one email rule</b><br>"
        "Add another method with the same <code>@field_validator(\"email\")</code>. "
        "They run in <b>definition order</b> (top → bottom). "
        "Each receives the value returned by the previous one. "
        "To <b>reject</b>, <code>raise ValueError(\"...\")</code>.</p>"
        '<div class="step-pre">'
        "# INPUT — two validators on the same field\n"
        "class UserCreate(BaseModel):\n"
        "    email: str\n"
        "    age: int = Field(ge=18)\n"
        "\n"
        "    @field_validator(\"email\")\n"
        "    @classmethod\n"
        "    def must_have_at(cls, v):\n"
        "        if \"@\" not in v:\n"
        "            raise ValueError(\"email must contain @\")\n"
        "        return v\n"
        "\n"
        "    @field_validator(\"email\")\n"
        "    @classmethod\n"
        "    def lower_email(cls, v):\n"
        "        return v.lower()     # runs after must_have_at\n"
        "\n"
        'ok = UserCreate.model_validate({"email": "Anu@Co.COM", "age": 25})\n'
        "print(ok.email)           # anu@co.com  (auto: both validators)\n"
        "\n"
        "try:\n"
        '    UserCreate.model_validate({"email": "bad", "age": 25})\n'
        "except ValidationError as e:\n"
        "    print(e.errors())      # must_have_at failed → 422 in FastAPI\n"
        "\n"
        "# OUTPUT\n"
        "anu@co.com\n"
        "[{'type': 'value_error', 'loc': ('email',), ...}]"
        "</div>"
        "<p style=\"font-size:12px;color:#334155;margin:6px 0 0;line-height:1.45\">"
        "<b>Tip:</b> You can also put both checks in <b>one</b> method "
        "(reject + lowercase). Two methods are clearer when rules are separate."
        "</p>"
        "<p><b>2) Valid body — coercion works</b><br>"
        "String <code>\"25\"</code> becomes int <code>25</code>; email is lowercased by the validator.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'body = {"email": "Anu@Co.COM", "age": "25"}\n'
        "user = UserCreate.model_validate(body)\n"
        "print(user.email)\n"
        "print(user.age)\n"
        "print(user)                 # full model\n"
        "\n"
        "# OUTPUT\n"
        "anu@co.com                  # lower_email ran → lowercased\n"
        "25                          # \"25\" coerced to int\n"
        "email='anu@co.com' age=25"
        "</div>"
        "<p><b>3) Invalid age — why HTTP 422?</b><br>"
        "Age <code>15</code> fails <mark class=\"hl-key\">Field(ge=18)</mark>. Pydantic raises "
        "<mark class=\"hl-key\">ValidationError</mark> <mark class=\"hl-key\">before</mark> your route body runs. "
        "FastAPI catches that and returns <mark class=\"hl-key\">HTTP 422 Unprocessable Entity</mark> "
        "(= “your JSON was understood, but the data breaks the rules”). "
        "This is <mark class=\"hl-key\">not</mark> 400 from your own <code>if</code> checks — the framework does it for you.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from pydantic import ValidationError\n"
        "\n"
        'bad = {"email": "x@y.com", "age": 15}\n'
        "try:\n"
        "    UserCreate.model_validate(bad)\n"
        "    print(\"ok\")\n"
        "except ValidationError as e:\n"
        "    print(e.error_count(), \"error(s)\")\n"
        "    print(e.errors())          # which field + why\n"
        "\n"
        "# OUTPUT (console)\n"
        "1 error(s)\n"
        "[{'type': 'greater_than_equal', 'loc': ('age',), ...}]\n"
        "\n"
        "# In FastAPI API response\n"
        "HTTP 422 Unprocessable Entity\n"
        '# {"detail": [{"loc": ["body", "age"], "msg": "...", ...}]}'
        "</div>"
        "<p style=\"font-size:12px;color:#334155;margin:6px 0 0;line-height:1.45\">"
        "<b>Takeaway:</b> "
        "<mark class=\"hl-key\">Field(ge=18)</mark> = door rule (reject under 18). "
        "<code>@field_validator(\"email\")</code> = cleaning station (lowercase before save). "
        "<mark class=\"hl-key\">422</mark> = “form filled wrong” — not a crash in your business logic."
        "</p>"
    ),
    15: (
        "<b>Bank / wallet domain:</b> Inheritance + polymorphism at month-end — "
        "each OOP idea with <b>input → output</b>."
        "<p><b>1) Base <code>Account</code> — shared behaviour</b><br>"
        "Think of <code>Account</code> as the <b>common blueprint</b> for every bank account. "
        "Every account needs a <b>balance</b>, a way to <b>add money</b> (<code>deposit</code>), "
        "and a way to <b>take money out</b> (<code>withdraw</code>). "
        "We write those once in the base class so children (Savings, Checking, …) "
        "<b>reuse</b> them — that is inheritance.</p>"
        "<p style=\"font-size:12px;color:#334155;margin:6px 0 8px;line-height:1.45\">"
        "<b>Why <code>month_end</code> does nothing?</b> "
        "Month-end rules differ by account type (savings may add interest; a plain wallet may do nothing). "
        "The base method is a <b>safe default</b>: <code>pass</code> means "
        "“no special month-end action.” Child classes <b>override</b> it when they need real logic. "
        "That way a loop can call <code>a.month_end()</code> on <i>every</i> account without crashing "
        "— polymorphism. Without a base <code>month_end</code>, a plain <code>Account</code> "
        "would raise <code>AttributeError</code> when you call it."
        "</p>"
        + io_split(
            "class Account:\n"
            "    def __init__(self, balance):\n"
            "        self.balance = balance   # shared state for all accounts\n"
            "\n"
            "    def deposit(self, amount):    # shared: add money\n"
            "        self.balance += amount\n"
            "\n"
            "    def withdraw(self, amount):   # shared: remove money\n"
            "        if amount &gt; self.balance:\n"
            '            raise ValueError("not enough balance")\n'
            "        self.balance -= amount\n"
            "\n"
            "    def month_end(self):\n"
            "        pass   # default: do nothing (safe for plain accounts)\n"
            "\n"
            "a = Account(100)\n"
            "a.deposit(50)      # 100 → 150\n"
            "a.withdraw(20)     # 150 → 130\n"
            "a.month_end()      # still 130 — pass did nothing\n"
            "print(a.balance)",
            {20: "130"},
        )
        + "<p style=\"font-size:12px;color:#334155;margin:6px 0 0;line-height:1.45\">"
        "<b>Line by line:</b> "
        "<code>__init__</code> stores starting money. "
        "<code>deposit</code> / <code>withdraw</code> change that shared <code>balance</code>. "
        "<code>month_end</code> + <code>pass</code> = empty action on purpose — a hook for children."
        "</p>"
        "<p><b>2) <code>SavingsAccount</code> — override <code>month_end</code></b><br>"
        "Child keeps deposit/withdraw from the parent, but replaces month-end with +4% interest.</p>"
        + io_split(
            "class SavingsAccount(Account):\n"
            "    def month_end(self):\n"
            "        self.balance *= 1.04   # overrides Account.month_end (base was pass) — apply +4% interest\n"
            "\n"
            "s = SavingsAccount(200)\n"
            "s.deposit(0)       # still works — inherited from Account\n"
            "s.month_end()      # updates balance; returns None (no return)\n"
            "print(s.balance)   # print the balance — NOT print(s.month_end())",
            {8: "208.0"},
        )
        + "<p style=\"font-size:12px;color:#334155;margin:6px 0 0;line-height:1.45\">"
        "<b>Why not <code>print(s.month_end())</code>?</b> "
        "<code>month_end</code> changes <code>self.balance</code> but has no <code>return</code> → returns "
        "<code>None</code>, so that print would show <code>None</code>."
        "</p>"
        "<p><b>3) Polymorphism — one loop, different behaviour</b><br>"
        "Call <code>month_end()</code> on every account; Python picks the right version "
        "(base <code>pass</code> vs savings interest).</p>"
        + io_split(
            "accounts = [Account(100), SavingsAccount(200)]\n"
            "for a in accounts:\n"
            "    a.month_end()\n"
            "    print(type(a).__name__, a.balance)   # runs twice",
            {4: "Account 100\nSavingsAccount 208.0"},
        )
    ),
    16: (
        "<b>Start with <code>@property</code>, then reuse the same rules with <code>__get__</code> / <code>__set__</code>.</b> "
        "Both reject negatives — like a C# property setter."
        "<p><b>1) One field with <code>@property</code></b><br>"
        "<code>p.price</code> reads the getter; <code>p.price = …</code> runs the setter. "
        "<b>Naming convention:</b> public name <code>price</code> → backing store "
        "<code>self._price</code> → getter <code>def price</code> → "
        "<code>@price.setter</code> (same name).</p>"
        + io_split(
            "class Product:\n"
            "    def __init__(self):\n"
            "        self._price = 0\n"
            "\n"
            "    @property\n"
            "    def price(self):                 # getter\n"
            "        return self._price\n"
            "\n"
            "    @price.setter\n"
            "    def price(self, value):          # setter\n"
            "        if value < 0:\n"
            '            raise ValueError("must be >= 0")\n'
            "        self._price = value\n"
            "\n"
            "p = Product()\n"
            "p.price = 99\n"
            "print(p.price)",
            {15: "99"},
        )
        + "<p><b>2) Two fields — <code>@property</code> vs descriptor (side by side)</b> "
        + csharp_compare_btn("property-vs-descriptor")
        + "<br>"
        "<code>@property</code> is <b>per field</b> (copy getter/setter again). "
        "A descriptor is defined <b>once at class level</b>, then plugged into every field that needs it.</p>"
        "<div class=\"mc-row\">"
        "<div class=\"mc-col mc-bad\">"
        "<span class=\"mc-lbl\">@property × 2 (repeat code)</span>"
        + io_split(
            "class Product:\n"
            "    def __init__(self):\n"
            "        self._price = 0\n"
            "        self._qty = 0\n"
            "\n"
            "    @property\n"
            "    def price(self):\n"
            "        return self._price\n"
            "    @price.setter\n"
            "    def price(self, value):\n"
            "        if value < 0:\n"
            '            raise ValueError("must be >= 0")\n'
            "        self._price = value\n"
            "\n"
            "    @property\n"
            "    def qty(self):                   # same rules again!\n"
            "        return self._qty\n"
            "    @qty.setter\n"
            "    def qty(self, value):\n"
            "        if value < 0:\n"
            '            raise ValueError("must be >= 0")\n'
            "        self._qty = value\n"
            "\n"
            "p = Product()\n"
            "p.price = 10\n"
            "p.qty = 3\n"
            "print(p.price, p.qty)",
            {27: "10 3"},
        )
        + "</div>"
        "<div class=\"mc-col mc-good\">"
        "<span class=\"mc-lbl\">Descriptor once → many fields</span>"
        + io_split(
            "class Positive:                     # define ONCE\n"
            "    def __set_name__(self, owner, name):\n"
            "        # NOT the constructor — runs AFTER class Product is created\n"
            "        # owner = the CLASS (Product), name = 'price' / 'qty'\n"
            "        self.name = name\n"
            "    def __get__(self, obj, owner):\n"
            "        # obj = instance p (or None if Product.price)\n"
            "        # owner = class Product\n"
            "        return obj.__dict__.get(self.name)\n"
            "    def __set__(self, obj, value):\n"
            "        # obj = instance p; value = what you assign\n"
            "        if value < 0:\n"
            '            raise ValueError("must be >= 0")\n'
            "        obj.__dict__[self.name] = value\n"
            "\n"
            "class Product:                      # plug in where needed\n"
            "    price = Positive()              # class-level field\n"
            "    qty = Positive()                # same helper again\n"
            "\n"
            "class Order:\n"
            "    total = Positive()              # reuse on another class!\n"
            "\n"
            "p = Product()\n"
            "p.price = 10\n"
            "p.qty = 3\n"
            "print(p.price, p.qty)\n"
            "try:\n"
            "    p.qty = -1\n"
            "except ValueError as e:\n"
            "    print(type(e).__name__)",
            {26: "10 3", 30: "ValueError"},
        )
        + "</div></div>"
        + '<table class="data-tbl" style="margin:8px 0">'
        "<tr><th>Parameter</th><th>Meaning (for <code>price = Positive()</code> on <code>Product</code>)</th></tr>"
        "<tr><td><code>self</code></td><td>The descriptor object (<code>Positive</code> instance)</td></tr>"
        "<tr><td><code>owner</code></td><td>The <b>class</b> that owns the field — here <code>Product</code> "
        "(not the instance <code>p</code>)</td></tr>"
        "<tr><td><code>name</code></td><td>Attribute name as a string — <code>'price'</code> or <code>'qty'</code></td></tr>"
        "<tr><td><code>obj</code></td><td>The <b>instance</b> — here <code>p</code> "
        "(or <code>None</code> if you access <code>Product.price</code> on the class)</td></tr>"
        "<tr><td><code>value</code></td><td>What you assign — <code>p.price = 10</code> → <code>value</code> is <code>10</code></td></tr>"
        "</table>"
        "<p><b>2b) <code>__init__</code> vs <code>__set_name__</code> — when each runs</b><br>"
        "<code>__init__</code> = constructor of the helper. "
        "<code>__set_name__</code> = later, when the owning class finishes.</p>"
        "<div class=\"mc-row\">"
        "<div class=\"mc-col mc-good\">"
        "<span class=\"mc-lbl\">Code + live OUTPUT</span>"
        + io_split(
            "class Positive:\n"
            "    def __init__(self):\n"
            '        print("1) __init__ — Positive() created")\n'
            "\n"
            "    def __set_name__(self, owner, name):\n"
            '        print(f"2) __set_name__ — {owner.__name__}.{name}")\n'
            "        self.name = name\n"
            "\n"
            "    def __get__(self, obj, owner):\n"
            "        return obj.__dict__.get(self.name)\n"
            "    def __set__(self, obj, value):\n"
            "        obj.__dict__[self.name] = value\n"
            "\n"
            'print("--- defining Product ---")\n'
            "class Product:\n"
            "    price = Positive()   # ← __init__ HERE\n"
            "    qty = Positive()     # ← __init__ again\n"
            "    # class ends → __set_name__ for price, then qty\n"
            "\n"
            'print("--- creating instance ---")\n'
            "p = Product()           # ← neither method\n"
            "p.price = 10            # ← __set__ only\n"
            'print("stored", p.price)  # ← __get__ only',
            {
                14: "--- defining Product ---\n"
                "1) __init__ — Positive() created\n"
                "1) __init__ — Positive() created\n"
                "2) __set_name__ — Product.price\n"
                "2) __set_name__ — Product.qty",
                20: "--- creating instance ---",
                23: "stored 10",
            },
            out_label="# OUTPUT (call order)",
        )
        + "</div>"
        "<div class=\"mc-col mc-bad\">"
        "<span class=\"mc-lbl\">Explanation (same moments)</span>"
        '<div class="step-pre" style="margin:0;border:none;border-radius:0;border-top:1px solid #e2e8f0">'
        "A) price = Positive()\n"
        "   → __init__     constructor\n"
        "\n"
        "B) qty = Positive()\n"
        "   → __init__     constructor again\n"
        "\n"
        "C) class Product finishes\n"
        "   → __set_name__(Product, 'price')\n"
        "   → __set_name__(Product, 'qty')\n"
        "\n"
        "D) p = Product()\n"
        "   → no __init__ / no __set_name__\n"
        "\n"
        "E) p.price = 10 / read\n"
        "   → __set__ / __get__ only\n"
        "\n"
        "Remember:\n"
        "__init__      = make helper\n"
        "__set_name__  = learn field name\n"
        "p = Product()  = neither again"
        "</div>"
        "</div></div>"
        + '<table class="data-tbl" style="margin-top:8px">'
        "<tr><th></th><th><code>@property</code></th><th>Descriptor (<code>__get__</code>/<code>__set__</code>)</th></tr>"
        "<tr><td><b>Where defined</b></td>"
        "<td>Inside each model, <b>per field</b></td>"
        "<td>Helper class once, then <code>field = Helper()</code></td></tr>"
        "<tr><td><b>Two fields</b></td>"
        "<td>Copy getter + setter twice</td>"
        "<td><code>price = Positive()</code> · <code>qty = Positive()</code></td></tr>"
        "<tr><td><b>Reuse on other classes</b></td>"
        "<td>Hard — paste again</td>"
        "<td>Easy — same <code>Positive()</code> on <code>Order.total</code></td></tr>"
        "<tr><td><b>Applied at</b></td>"
        "<td>Instance attribute access</td>"
        "<td><b>Class level</b> assignment of the helper object</td></tr>"
        "</table>"
        "<p><b>3) Remember</b><br>"
        "<code>@property</code> = fine for one-off fields. "
        "Need the <b>same check on many fields/classes</b>? "
        "Define a descriptor and attach it where needed — "
        "<code>get</code>/<code>set</code> logic lives in the helper, not copied.</p>"
    ),
    17: (
        "<b>Export 50M+ CSV rows:</b> Stream with yield — avoid MemoryError from read().split() — "
        "each approach with <b>input → output</b>."
        "<p><b>1) Without <code>yield</code> vs with <code>yield</code> — same job, different memory</b><br>"
        "Both parse rows. Left builds a <b>full list in RAM</b>. Right hands back "
        "<b>one row at a time</b>.</p>"
        '<div class="mc-row">'
        '<div class="mc-col mc-bad"><span class="mc-lbl">Without yield — list in RAM</span>'
        '<div class="step-pre">'
        "# INPUT\n"
        "def csv_reader(path):\n"
        "    rows = []\n"
        "    with open(path, encoding=\"utf-8\") as f:\n"
        "        for line in f:\n"
        "            rows.append(line.strip().split(\",\"))\n"
        "    return rows          # ALL rows at once\n"
        "\n"
        "data = csv_reader(\"big.csv\")\n"
        "print(len(data))\n"
        "\n"
        "# OUTPUT\n"
        "50000000\n"
        "# then often → MemoryError on huge files"
        "</div></div>"
        '<div class="mc-col mc-good"><span class="mc-lbl">With yield — one row at a time</span>'
        '<div class="step-pre">'
        "# INPUT\n"
        "def csv_reader(path):\n"
        "    with open(path, encoding=\"utf-8\") as f:\n"
        "        for line in f:\n"
        "            yield line.strip().split(\",\")\n"
        "\n"
        "# first row only\n"
        "row = next(csv_reader(\"big.csv\"))\n"
        "print(row)                 # ['id', 'name', 'amount']\n"
        "\n"
        "# ALL rows — one per loop (still lazy)\n"
        "for row in csv_reader(\"big.csv\"):\n"
        "    print(row)             # each line, one at a time\n"
        "\n"
        "# OUTPUT (first next)\n"
        "['id', 'name', 'amount']\n"
        "# then for-loop prints every remaining row\n"
        "# memory: still ONE row at a time — safe for 50M+"
        "</div></div>"
        "</div>"
        "<p style=\"font-size:12px;margin:6px 0;line-height:1.45\">"
        "<b>Does the <code>for</code> need <code>next</code>?</b> No — "
        "<code>for</code> calls <code>next()</code> for you on each lap until the generator is done. "
        "Use <code>next(gen)</code> only when you want <b>one</b> row by hand."
        "<br>"
        "<b>Takeaway:</b> <code>return rows</code> waits until the whole file is loaded. "
        "<code>yield</code> pauses after each row — caller decides when to ask for the next."
        "</p>"
        "<p><b>2) <code>range(5)</code> vs <code>list(range(5))</code> — lazy vs eager</b><br>"
        "Same idea as <code>yield</code> vs <code>return</code>: left is a lazy iterator "
        "(one value at a time); right builds everything in memory.</p>"
        '<div class="mc-row">'
        '<div class="mc-col mc-good"><span class="mc-lbl"><code>range(5)</code> — lazy (O(1))</span>'
        '<div class="step-pre">'
        "r = range(5)          # r = range object (not a function pointer)\n"
        "# stores only three fields: start=0, stop=5, step=1\n"
        "# NOT [0,1,2,3,4] in memory yet\n"
        "\n"
        "for x in r:\n"
        "    print(x)  # iter()/next() one at a time\n"
        "\n"
        "# Memory: tiny (same for range(1_000_000))\n"
        "# Lazy iterator — like yield"
        "</div></div>"
        '<div class="mc-col mc-bad"><span class="mc-lbl"><code>list(range(5))</code> — eager (O(n))</span>'
        '<div class="step-pre">'
        "nums = list(range(5))  # nums = Python list (like Java ArrayList)\n"
        "# list() does NOT change the range — it READS it via iter()/next()\n"
        "# What list(iterable) does (simplified):\n"
        "result = []\n"
        "it = iter(range(5))      # start iteration\n"
        "while True:\n"
        "    try:\n"
        "        value = next(it)   # 0, then 1, then 2, ...\n"
        "        result.append(value)\n"
        "    except StopIteration:\n"
        "        break\n"
        "# result → [0, 1, 2, 3, 4]  (same as nums)\n"
        "\n"
        "print(nums[2])  # 2 — indexing works\n"
        "for x in nums:     # can loop again\n"
        "    print(x)\n"
        "\n"
        "# Memory: grows with count\n"
        "# Like return [0,1,2,3,4] — all values at once"
        "</div></div>"
        "</div>"
        "<p style=\"font-size:12px;margin:6px 0;line-height:1.45\">"
        "<b>Link to generators:</b> <code>range(5)</code> is a built-in lazy iterator — "
        "same as <code>yield</code> one value at a time. "
        "<code>list(range(5))</code> is eager — like <code>return [0,1,2,3,4]</code>."
        "</p>"
        "<p><b>3) Export — without <code>yield</code> vs with <code>yield</code></b><br>"
        "Same transform + write. Left loads <b>all rows first</b>. Right "
        "<b>writes each row as it arrives</b>.</p>"
        '<div class="mc-row">'
        '<div class="mc-col mc-bad"><span class="mc-lbl">Without yield — load all, then write</span>'
        '<div class="step-pre">'
        "# INPUT\n"
        "def export(path, out):\n"
        "    rows = csv_reader(path)   # list version — ALL in RAM\n"
        "    with open(out, \"w\", encoding=\"utf-8\") as dest:\n"
        "        for row in rows:\n"
        "            t = transform(row)\n"
        "            dest.write(\",\".join(t) + \"\\n\")\n"
        "\n"
        "export(\"big.csv\", \"out.csv\")\n"
        "\n"
        "# OUTPUT\n"
        "# may finish… or MemoryError before any write\n"
        "# peak RAM ≈ whole file"
        "</div></div>"
        '<div class="mc-col mc-good"><span class="mc-lbl">With yield — write as you read</span>'
        '<div class="step-pre">'
        "# INPUT\n"
        "def export(path, out):\n"
        "    with open(out, \"w\", encoding=\"utf-8\") as dest:\n"
        "        for row in csv_reader(path):  # yield version\n"
        "            t = transform(row)\n"
        "            dest.write(\",\".join(t) + \"\\n\")\n"
        "\n"
        "export(\"big.csv\", \"out.csv\")\n"
        "\n"
        "# OUTPUT\n"
        "out file grows line by line\n"
        "# peak RAM ≈ one row — safe for 50M+"
        "</div></div>"
        "</div>"
        "<p style=\"font-size:12px;margin:6px 0;line-height:1.45\">"
        "<b>Compare:</b> without yield you must hold the full list before writing. "
        "With yield, each <code>for</code> lap = one <code>next()</code> → transform → write → discard."
        "</p>"
        "<p><b>4) At scale — without <code>yield</code> vs with <code>yield</code></b><br>"
        "Same file. Left loads <b>everything into RAM</b>. Right keeps "
        "<b>one line</b> in memory.</p>"
        '<div class="mc-row">'
        '<div class="mc-col mc-bad"><span class="mc-lbl">Without yield — fails at scale</span>'
        '<div class="step-pre">'
        "# INPUT\n"
        "data = open(path).read().split()   # whole file\n"
        "# or: rows = list(csv_reader(path))  # force full list\n"
        "\n"
        "print(len(data))\n"
        "\n"
        "# OUTPUT\n"
        "MemoryError on huge files\n"
        "# (or machine thrashes / freezes)"
        "</div></div>"
        '<div class="mc-col mc-good"><span class="mc-lbl">With yield — stays flat</span>'
        '<div class="step-pre">'
        "# INPUT\n"
        "def csv_reader(path):\n"
        "    with open(path, encoding=\"utf-8\") as f:\n"
        "        for line in f:\n"
        "            yield line.strip().split(\",\")\n"
        "\n"
        "count = 0\n"
        "for row in csv_reader(path):\n"
        "    count += 1\n"
        "print(count)\n"
        "\n"
        "# OUTPUT\n"
        "50000000\n"
        "# peak RAM ≈ one row — no MemoryError"
        "</div></div>"
        "</div>"
        "<p style=\"font-size:12px;margin:6px 0;line-height:1.45\">"
        "<b>Why:</b> <code>read().split()</code> / <code>list(...)</code> needs space for "
        "<b>all</b> rows at once. <code>yield</code> + <code>for</code> never builds that list."
        "</p>"
    ),
    18: (
        "<b>Cross-cutting concerns:</b> Decorators wrap once — retry, auth, timing — "
        "each layer with <b>input → output</b>."
        "<p><b>1) <code>timer</code> decorator — measure runtime</b><br>"
        "Wraps any function: record start, call original, print elapsed seconds.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "import time\n"
        "from functools import wraps\n"
        "\n"
        "def timer(fn):\n"
        "    @wraps(fn)\n"
        "    def wrapper(*args, **kwargs):\n"
        "        start = time.time()\n"
        "        result = fn(*args, **kwargs)\n"
        "        print(f\"{fn.__name__} took {time.time() - start:.2f}s\")\n"
        "        return result\n"
        "    return wrapper\n"
        "\n"
        "# OUTPUT\n"
        "(wrapper ready — can decorate any function)"
        "</div>"
        "<p><b>2) Apply <code>@timer</code> to <code>run_query</code></b><br>"
        "Same function body; decorator adds timing without changing business logic.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "@timer\n"
        "def run_query():\n"
        "    time.sleep(0.1)\n"
        "    return \"ok\"\n"
        "\n"
        "result = run_query()\n"
        "\n"
        "# OUTPUT\n"
        "run_query took 0.10s\n"
        "result → 'ok'"
        "</div>"
    ),
    19: (
        "<b>File upload API:</b> Specific excepts + finally for cleanup — "
        "each path with <b>input → output</b>."
        "<p><b>1) Success — return 200</b><br>"
        "Save the file and return OK when nothing goes wrong.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def upload(file, temp):\n"
        "    try:\n"
        "        save(file)\n"
        "        return {\"status\": 200}\n"
        "    except PermissionError:\n"
        "        return {\"status\": 403}\n"
        "    except OSError:\n"
        "        return {\"status\": 500}\n"
        "    finally:\n"
        "        temp.cleanup()\n"
        "\n"
        "upload(valid_file, temp)\n"
        "\n"
        "# OUTPUT\n"
        "return → {'status': 200}; temp cleaned up"
        "</div>"
        "<p><b>2) Permission denied — return 403</b><br>"
        "Catch the specific error instead of one giant <code>except Exception</code>.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "# save() raises PermissionError\n"
        "upload(locked_file, temp)\n"
        "\n"
        "# OUTPUT\n"
        "return → {'status': 403}; temp cleaned up in finally"
        "</div>"
        "<p><b>3) Disk error — return 500</b><br>"
        "<code>OSError</code> covers disk full, network drive gone, etc.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "# save() raises OSError\n"
        "upload(file, temp)\n"
        "\n"
        "# OUTPUT\n"
        "return → {'status': 500}; temp cleaned up in finally"
        "</div>"
    ),
    20: (
        "<b>Image resize service:</b> Threads for download (I/O); processes for CPU work — "
        "each pool with <b>input → output</b>."
        "<p><b>1) <code>ThreadPoolExecutor</code> — parallel downloads</b><br>"
        "Network waits release the GIL — threads are fine for I/O-bound fetch.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from concurrent.futures import ThreadPoolExecutor\n"
        "\n"
        "urls = [\"http://a/img1.jpg\", \"http://b/img2.jpg\"]\n"
        "\n"
        "with ThreadPoolExecutor() as pool:\n"
        "    images = list(pool.map(download, urls))\n"
        "\n"
        "# OUTPUT\n"
        "images → [bytes1, bytes2]  (downloaded concurrently)"
        "</div>"
        "<p><b>2) <code>ProcessPoolExecutor</code> — CPU resize</b><br>"
        "Pixel crunching needs real parallel cores — separate processes bypass the GIL.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from concurrent.futures import ProcessPoolExecutor\n"
        "\n"
        "with ProcessPoolExecutor() as pool:\n"
        "    out = list(pool.map(heavy_resize, images))\n"
        "\n"
        "# OUTPUT\n"
        "out → [resized1, resized2]  (CPU work on multiple cores)"
        "</div>"
    ),
    21: (
        "<b>Notification fan-out:</b> Three network calls concurrently with gather — "
        "each async step with <b>input → output</b>."
        "<p><b>1) Individual async senders</b><br>"
        "Each channel awaits a short sleep (stand-in for a real HTTP call).</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "import asyncio\n"
        "\n"
        "async def send_email():\n"
        "    await asyncio.sleep(0.2)\n"
        '    return "email ok"\n'
        "\n"
        "async def send_sms():\n"
        "    await asyncio.sleep(0.2)\n"
        '    return "sms ok"\n'
        "\n"
        "# OUTPUT\n"
        "(coroutines defined — not run until awaited)"
        "</div>"
        "<p><b>2) <code>asyncio.gather</code> — run all three together</b><br>"
        "Total wait ≈ 0.2s (longest task), not 0.6s sequential.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "async def notify():\n"
        "    results = await asyncio.gather(\n"
        "        send_email(),\n"
        "        send_sms(),\n"
        "        push(),\n"
        "    )\n"
        "    return results\n"
        "\n"
        "asyncio.run(notify())\n"
        "\n"
        "# OUTPUT\n"
        "results → ['email ok', 'sms ok', 'push ok']"
        "</div>"
    ),
    22: (
        "<b>Production order service:</b> Structured logs + exception traceback + rotation — "
        "each logging piece with <b>input → output</b>."
        "<p><b>1) Rotating file handler — setup</b><br>"
        "Log to <code>app.log</code>; rotate at 1 MB, keep 7 backup files.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "import logging\n"
        "from logging.handlers import RotatingFileHandler\n"
        "\n"
        "logger = logging.getLogger(__name__)\n"
        "handler = RotatingFileHandler(\n"
        '    "app.log", maxBytes=1_000_000, backupCount=7\n'
        ")\n"
        "logger.addHandler(handler)\n"
        "logger.setLevel(logging.INFO)\n"
        "\n"
        "# OUTPUT\n"
        "logger ready → writes to app.log (rotates at 1 MB)"
        "</div>"
        "<p><b>2) Info on success</b><br>"
        "Structured message with order id — searchable in log tools.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'logger.info("order %s paid", 9001)\n'
        "\n"
        "# OUTPUT\n"
        "app.log → INFO … order 9001 paid"
        "</div>"
        "<p><b>3) <code>logger.exception</code> on failure</b><br>"
        "Inside an <code>except</code> block — logs message plus full traceback.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "try:\n"
        "    raise RuntimeError(\"gateway timeout\")\n"
        "except Exception:\n"
        '    logger.exception("payment failed")\n'
        "\n"
        "# OUTPUT\n"
        "app.log → ERROR payment failed\n"
        "           Traceback … RuntimeError: gateway timeout"
        "</div>"
    ),
    23: (
        "<b>Discount engine CI:</b> Named test + mock so PRs never hit real payment APIs — "
        "each test style with <b>input → output</b>."
        "<p><b>1) Plain unit test — assert expected discount</b><br>"
        "Descriptive name tells reviewers what behaviour is locked in.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def senior_discount(age, amount):\n"
        "    if age &gt;= 60:\n"
        "        return amount * 0.90\n"
        "    return amount\n"
        "\n"
        "def test_senior_citizen_gets_10_percent():\n"
        "    assert senior_discount(65, 1000) == 900\n"
        "\n"
        "# OUTPUT\n"
        "pytest → 1 passed"
        "</div>"
        "<p><b>2) Mock — fake the payment gateway</b><br>"
        "<code>@patch</code> replaces <code>payments.charge</code> so CI never calls the real API.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from unittest.mock import patch\n"
        "\n"
        "@patch(\"payments.charge\")\n"
        "def test_checkout_mocks_gateway(mock_charge):\n"
        "    mock_charge.return_value = \"ok\"\n"
        "    assert checkout(100) == \"ok\"\n"
        "\n"
        "# OUTPUT\n"
        "pytest → 1 passed (no real HTTP call)"
        "</div>"
    ),
    24: (
        "<b>Log cleanup:</b> Find SSN-like patterns and redact before shipping to SIEM — "
        "each regex step with <b>input → output</b>."
        "<p><b>1) <code>re.findall</code> — spot SSN patterns</b><br>"
        "Pattern <code>\\d{3}-\\d{2}-\\d{4}</code> matches US-style social security numbers.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "import re\n"
        "\n"
        'pattern = r"\\d{3}-\\d{2}-\\d{4}"\n'
        'text = "user 123-45-6789 logged in"\n'
        "matches = re.findall(pattern, text)\n"
        "\n"
        "# OUTPUT\n"
        "matches → ['123-45-6789']"
        "</div>"
        "<p><b>2) Redact — replace before export</b><br>"
        "Swap each match with stars so SIEM never stores real SSNs.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def redact(text):\n"
        "    matches = re.findall(pattern, text)\n"
        "    clean = text\n"
        "    for m in matches:\n"
        '        clean = clean.replace(m, "***-**-****")\n'
        "    return clean\n"
        "\n"
        'print(redact("user 123-45-6789 logged in"))\n'
        "\n"
        "# OUTPUT\n"
        "user ***-**-**** logged in"
        "</div>"
    ),
    25: (
        "<b>Daily sales export:</b> Read CSV, write JSON, make archive folder — auto-close — "
        "each file step with <b>input → output</b>."
        "<p><b>1) Read CSV with <code>with</code></b><br>"
        "<code>DictReader</code> gives each row as a dict; file closes when block exits.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "import csv\n"
        "\n"
        'with open("sales.csv", encoding="utf-8") as f:\n'
        "    rows = list(csv.DictReader(f))\n"
        "\n"
        "# OUTPUT\n"
        "rows → [{'sku': 'A1', 'qty': '2'}, …]"
        "</div>"
        "<p><b>2) Write JSON summary</b><br>"
        "One small summary file for dashboards — count of rows exported.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "import json\n"
        "\n"
        'summary = {"count": len(rows)}\n'
        'with open("summary.json", "w", encoding="utf-8") as out:\n'
        "    json.dump(summary, out, indent=2)\n"
        "\n"
        "# OUTPUT\n"
        'summary.json → {"count": 42}'
        "</div>"
        "<p><b>3) Create archive folder</b><br>"
        "<code>Path.mkdir(exist_ok=True)</code> — safe to run every night.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from pathlib import Path\n"
        "\n"
        'Path("archive").mkdir(exist_ok=True)\n'
        "\n"
        "# OUTPUT\n"
        "archive/ folder exists (created if missing)"
        "</div>"
    ),
    26: (
        "<b>DB transaction helper:</b> Commit on success, rollback on error — like C# using — "
        "each phase with <b>input → output</b>."
        "<p><b>1) <code>@contextmanager</code> — session lifecycle</b><br>"
        "Open session, yield it, commit on success, rollback on error, always close.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "from contextlib import contextmanager\n"
        "\n"
        "@contextmanager\n"
        "def session_scope():\n"
        "    session = Session()\n"
        "    try:\n"
        "        yield session\n"
        "        session.commit()\n"
        "    except Exception:\n"
        "        session.rollback()\n"
        "        raise\n"
        "    finally:\n"
        "        session.close()\n"
        "\n"
        "# OUTPUT\n"
        "(context manager ready — like C# <code>using</code>)"
        "</div>"
        "<p><b>2) Use with <code>with</code> — add order</b><br>"
        "If <code>db.add</code> succeeds, commit runs; if it raises, rollback runs.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "with session_scope() as db:\n"
        "    db.add(order)\n"
        "\n"
        "# OUTPUT\n"
        "commit → order saved; session closed"
        "</div>"
        "<p><b>3) Error path — rollback</b><br>"
        "Exception inside the block triggers rollback before re-raise.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "with session_scope() as db:\n"
        "    db.add(bad_order)  # raises IntegrityError\n"
        "\n"
        "# OUTPUT\n"
        "rollback → no partial save; session closed; exception propagates"
        "</div>"
    ),
    27: (
        "<b>Two client projects:</b> Separate venvs so Django versions never clash — "
        "each client with <b>input → output</b>."
        "<p><b>1) Client A — Django 4.2 venv</b><br>"
        "Create and activate an isolated environment before installing requirements.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "cd client_a\n"
        "python -m venv .venv\n"
        ".venv\\Scripts\\activate\n"
        "pip install -r requirements.txt\n"
        "\n"
        "# OUTPUT\n"
        "pip → Django 4.2.x installed in client_a/.venv"
        "</div>"
        "<p><b>2) Client B — Django 5 venv</b><br>"
        "Switch folder, new venv — versions never bleed between projects.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "cd client_b\n"
        "python -m venv .venv\n"
        ".venv\\Scripts\\activate\n"
        "pip install -r requirements.txt\n"
        "\n"
        "# OUTPUT\n"
        "pip → Django 5.x installed in client_b/.venv"
        "</div>"
    ),
    28: (
        "<b>Internal HR API:</b> Route → Pydantic → service → SQLAlchemy → response schema — "
        "each layer with <b>input → output</b>."
        "<p><b>1) Request body — Pydantic validates</b><br>"
        "FastAPI parses JSON into <code>EmployeeCreate</code> before your code runs.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'POST /employees  body={"name": "Ravi", "dept": "Eng"}\n'
        "\n"
        "# OUTPUT\n"
        "body → EmployeeCreate(name='Ravi', dept='Eng')"
        "</div>"
        "<p><b>2) Route — save and return via response model</b><br>"
        "ORM object is serialized through <code>EmployeeRead</code>, not raw SQL rows.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "@app.post(\"/employees\", response_model=EmployeeRead)\n"
        "def create_employee(\n"
        "    body: EmployeeCreate,\n"
        "    db: Session = Depends(get_db),\n"
        "):\n"
        "    emp = Employee(**body.model_dump())\n"
        "    db.add(emp)\n"
        "    db.commit()\n"
        "    db.refresh(emp)\n"
        "    return emp\n"
        "\n"
        "# OUTPUT\n"
        "HTTP 201 → {\"id\": 7, \"name\": \"Ravi\", \"dept\": \"Eng\"}"
        "</div>"
    ),
    29: (
        "<b>Interview demo path:</b> One story from basics → regex → web API → voice AI — "
        "each demo with <b>input → output</b>."
        "<p><b>1) OOP basics — <code>car.py</code></b><br>"
        "Show classes and methods in under a minute.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "python pythonBasics/MyClass/car.py\n"
        "\n"
        "# OUTPUT\n"
        "Car started / drove — class demo printed"
        "</div>"
        "<p><b>2) Regex exercise — baby names</b><br>"
        "Parse text files — shows string processing beyond toy examples.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "python google-python-exercises/babynames/babynames.py\n"
        "\n"
        "# OUTPUT\n"
        "Ranked name counts printed"
        "</div>"
        "<p><b>3) Web API and voice POC</b><br>"
        "Finish with Django/DRF JSON endpoint, then Pipecat voice pipeline slide.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "# show Django / DRF API in browser\n"
        "# then show Pipecat voice POC\n"
        "\n"
        "# OUTPUT\n"
        "JSON from API → voice bot responds on mic input"
        "</div>"
    ),
    30: (
        "<b>Team onboarding:</b> New joiners open topic folders that map to slides — "
        "each module with <b>input → output</b>."
        "<p><b>1) OOP inheritance — maps to slide 15</b><br>"
        "Run the bank account example so new hires see polymorphism in code.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "cd Python-Set2/pythonBasics\n"
        "python MyClass/oops_inheritance_BankAccount.py\n"
        "\n"
        "# OUTPUT\n"
        "Savings vs current account month-end balances printed"
        "</div>"
        "<p><b>2) Unit tests — maps to slide 23</b><br>"
        "Show how CI runs assertions before merge.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "python MyUnitTesting/calculator_unittest.py\n"
        "\n"
        "# OUTPUT\n"
        "Ran N tests … OK"
        "</div>"
    ),
    31: (
        "<b>Data analyst task:</b> Clean Titanic CSV, group, present to stakeholders — "
        "each pandas step with <b>input → output</b>."
        "<p><b>1) Load and drop missing ages</b><br>"
        "Remove rows with no age so averages are not skewed by NaN.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "import pandas as pd\n"
        "\n"
        'df = pd.read_csv("titanic.csv")\n'
        'df = df.dropna(subset=["Age"])\n'
        "\n"
        "# OUTPUT\n"
        "df.shape → (714, 12)  (rows without Age removed)"
        "</div>"
        "<p><b>2) Group by survival — mean age</b><br>"
        "Answer: did survivors tend to be younger or older?</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "summary = (\n"
        "    df.groupby(\"Survived\")[\"Age\"]\n"
        "      .mean()\n"
        ")\n"
        "print(summary)\n"
        "\n"
        "# OUTPUT\n"
        "Survived\n"
        "0    30.1\n"
        "1    28.3"
        "</div>"
        "<p><b>3) Present in Jupyter</b><br>"
        "Chart the summary for stakeholders — same numbers, visual story.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "summary.plot(kind=\"bar\")\n"
        "\n"
        "# OUTPUT\n"
        "Bar chart — survived vs not, mean age side by side"
        "</div>"
    ),
    32: (
        "<b>Meeting planner product:</b> Django site + DRF JSON + later async microservice — "
        "each layer with <b>input → output</b>."
        "<p><b>1) Django view (MVT) — HTML for browser</b><br>"
        "Filter available rooms and render a template.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def room_list(request):\n"
        "    rooms = Room.objects.filter(available=True)\n"
        '    return render(request, "rooms.html", {"rooms": rooms})\n'
        "\n"
        "# OUTPUT\n"
        "HTTP 200 → rooms.html with list of available rooms"
        "</div>"
        "<p><b>2) DRF ViewSet — JSON for mobile app</b><br>"
        "Same <code>Room</code> model, serialized through <code>RoomSerializer</code>.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "class RoomViewSet(viewsets.ModelViewSet):\n"
        "    queryset = Room.objects.all()\n"
        "    serializer_class = RoomSerializer\n"
        "\n"
        "GET /api/rooms/\n"
        "\n"
        "# OUTPUT\n"
        "JSON → [{\"id\": 1, \"name\": \"Board A\", \"available\": true}, …]"
        "</div>"
    ),
    33: (
        "<b>Clinic phone bot:</b> STT → LLM → TTS chain (Pipecat-style processors) — "
        "each stage with <b>input → output</b>."
        "<p><b>1) STT — audio to text</b><br>"
        "Transcribe the caller's speech chunk into words.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "audio_chunk = b\"…wav bytes…\"\n"
        "text = await stt.transcribe(audio_chunk)\n"
        "\n"
        "# OUTPUT\n"
        'text → "I need my member ID validated"'
        "</div>"
        "<p><b>2) LLM branch — decide reply</b><br>"
        "If they said \"member\", ask the LLM to validate; else prompt for ID.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'if "member" in text.lower():\n'
        '    reply = await llm.ask("Validate member ID")\n'
        "else:\n"
        '    reply = "Please say your member ID"\n'
        "\n"
        "# OUTPUT\n"
        'reply → "What is your member ID number?"'
        "</div>"
        "<p><b>3) TTS — text back to speech</b><br>"
        "Send reply audio to the phone line.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "speech = await tts.speak(reply)\n"
        "\n"
        "# OUTPUT\n"
        "speech → audio bytes played to caller"
        "</div>"
    ),
    34: (
        "<b>Greenfield microservice:</b> Controllers / Services / DTOs style layout — "
        "each layer with <b>input → output</b>."
        "<p><b>1) Folder layout — separation of concerns</b><br>"
        "Routes stay thin; business rules live in services; schemas define API shapes.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "# project tree:\n"
        "app/\n"
        "  routes/          # thin HTTP handlers\n"
        "  services/        # business rules\n"
        "  schemas/         # Pydantic DTOs\n"
        "  models/          # DB / ORM\n"
        "tests/              # at repo root\n"
        "\n"
        "# OUTPUT\n"
        "(structure ready — each folder has one job)"
        "</div>"
        "<p><b>2) Route calls service — not raw SQL</b><br>"
        "HTTP handler validates input, delegates to service, returns DTO.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "@router.post(\"/orders\")\n"
        "def create_order(body: OrderCreate, svc: OrderService = Depends()):\n"
        "    order = svc.create(body)\n"
        "    return OrderRead.model_validate(order)\n"
        "\n"
        "# OUTPUT\n"
        "HTTP 201 → {\"id\": 42, \"status\": \"NEW\"}"
        "</div>"
    ),
    35: (
        "<b>C# shop adopting Python:</b> Map familiar ideas so .NET devs ramp fast — "
        "each mapping with <b>input → output</b>."
        "<p><b>1) Null check — C# <code>null</code> → Python <code>None</code></b><br>"
        "Use <code>is None</code>, not <code>== None</code>.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "value = None\n"
        "if value is None:\n"
        '    print("no data")\n'
        "\n"
        "# OUTPUT\n"
        "no data"
        "</div>"
        "<p><b>2) Empty method — C# <code>{ }</code> → <code>pass</code></b><br>"
        "Stub until the report logic is written.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        "def save_report():\n"
        "    pass\n"
        "\n"
        "# OUTPUT\n"
        "(function exists — no SyntaxError)"
        "</div>"
        "<p><b>3) File scope — C# <code>using</code> → <code>with open</code></b><br>"
        "File closes automatically when the block ends.</p>"
        '<div class="step-pre">'
        "# INPUT\n"
        'with open("report.txt", "w") as f:\n'
        '    f.write("done")\n'
        "\n"
        "# OUTPUT\n"
        "report.txt created; file handle closed"
        "</div>"
        "<table class=\"data-tbl\">"
        "<tr><th>C# idea</th><th>Python</th><th>Output here</th></tr>"
        "<tr><td><code>null</code></td><td><code>None</code> + <code>is None</code></td>"
        "<td><code>no data</code></td></tr>"
        "<tr><td>Empty method <code>{ }</code></td><td><code>pass</code></td>"
        "<td>No SyntaxError</td></tr>"
        "<tr><td><code>using (...)</code></td><td><code>with open(...) as f:</code></td>"
        "<td>File auto-closed</td></tr>"
        "<tr><td><code>async Task</code></td><td><code>async def</code></td>"
        "<td>Same await pattern</td></tr>"
        "<tr><td>NuGet</td><td><code>pip</code> + venv</td>"
        "<td>Isolated packages</td></tr>"
        "</table>"
    ),
}


def real_life_for(n: int) -> str:
    text = REAL_LIFE.get(n)
    if not text:
        return ""
    return f'<div class="real-life"><b>Real-life example:</b> {text}</div>'
