"""Per-slide process boxes for visual guides.

Each id has its own 4-step picture so posters do not reuse a keyword stencil
(e.g. DI's Interface→Register must not appear on 'change unfamiliar code').
"""

from __future__ import annotations

# id → four boxes named in interview order
FLOW_BY_ID: dict[str, list[str]] = {
    # .NET
    "D01": ["Value bits", "On the stack", "Reference arrow", "On the heap"],
    "D02": ["Write query", "Compose", "Enumerate", "SQL or memory"],
    "D03": ["T placeholder", "IFoo<out T>", "IFoo<in T>", "Compile check"],
    "D04": ["Throw", "Boundary catch", "Log + map", "Client contract"],
    "D05": ["Alloc", "Gen0/1/2", "LOH if large", "Dispose natives"],
    "D06": ["Call async", "await I/O", "Thread free", "Resume callback"],
    "D07": ["I/O → Task", "CPU → Parallel", "Shared state?", "lock / Interlocked"],
    "D08": ["Producer", "Bounded channel", "Consumer", "Backpressure"],
    "D09": ["Delegate", "Event subscribe", "Expression tree", "Provider SQL"],
    "D10": ["Attribute", "Reflection read", "Framework hook", "Keep off hot path"],
    "D11": ["Hot path", "Measure alloc", "Span / pool", "Benchmark"],
    "D12": ["Inventory", "Modernize slice", "Validate tests", "Rollout"],
    "D13": ["Counters", "Trace", "Dump", "One hypothesis"],
    "D14": ["Restore graph", "Conflict", "Pin version", "Repeatable build"],
    "D15": ["HTTP in", "AuthZ", "Action", "Unwind out"],
    "D16": ["Interface", "Register lifetime", "Constructor", "Use / dispose"],
    "D17": ["Bind", "Validate", "Version", "ProblemDetails"],
    "D18": ["LINQ", "Translate SQL", "Track or not", "Materialize"],
    "D19": ["Login", "Issue tokens", "Validate API", "Refresh / expire"],
    "D20": ["Providers", "Options bind", "Validate", "Secrets out of repo"],
    "D21": ["Miss", "Load store", "Set cache", "Invalidate"],
    "D22": ["Queue work", "BackgroundService", "Retry / poison", "Drain on stop"],
    "D23": ["Unit", "Test double", "Integration", "WebApplicationFactory"],
    "D24": ["Log event", "Metric", "Trace span", "Alert"],
    "D25": ["Receive", "Process", "Ack or retry", "DLQ if poison"],
    "D26": ["Kestrel", "Proxy / ALB", "N replicas", "Health check"],
    "D27": ["ON key", "INNER or LEFT", "GROUP / window", "Check grain"],
    "D28": ["Equality cols", "Range col last", "Cover includes", "Seek vs scan"],
    "D29": ["Actual plan", "Operator cost", "Seek or scan", "Before vs after"],
    "D30": ["BEGIN TRAN", "Take locks", "Commit / roll back", "Deadlock victim"],
    "D31": ["Normalize", "Constraint", "Denormalize read", "Name the tradeoff"],
    "D32": ["CRUD via EF", "Set-based SQL", "Batch", "Keep params"],
    "D33": ["Open", "Use from pool", "Dispose", "Watch wait / timeout"],
    "D34": ["Access pattern", "Pick model", "Consistency", "Own the query"],
    "D35": ["Expand schema", "Deploy app", "Contract old", "Rollback plan"],
    "D36": ["Keyset page", "Stream / chunk", "Bound memory", "Archive old"],
    "D37": ["Clarify input", "Pick structure", "State complexity", "Test edge"],
    "D38": ["Restate", "Plan aloud", "Code", "Self-test"],
    "D39": ["Reproduce", "Isolate", "Prove cause", "Regression test"],
    "D40": ["Map callers", "Characterize", "Small diff", "Staged rollout"],
    "D41": ["Read intent", "Blocker vs nit", "Design question", "Expected action"],
    "D42": ["Safety net", "Extract seam", "Small steps", "Keep shipping"],
    "D43": ["Build", "Test gate", "Same artifact", "Deploy / rollback"],
    "D44": ["Detect", "Mitigate", "Preserve evidence", "Prevent"],
    "D45": ["Idempotent POST?", "Page / cursor", "Error shape", "Compatibility"],
    "D46": ["API edge", "Domain rules", "Infrastructure", "Keep inward"],
    "D47": ["No in-memory session", "ALB", "N instances", "Watch the DB"],
    "D48": ["Read path", "Cache-aside", "Invalidate event", "TTL as backup"],
    "D49": ["Publish", "At-least-once", "Idempotent handler", "DLQ"],
    "D50": ["Timeout", "Retry budget", "Circuit break", "Shed load"],
    "D51": ["Name NFR", "Number + window", "Measure", "Budget in design"],
    "D52": ["Peak QPS", "Work per request", "Headroom", "Scale trigger"],
    "D53": ["Asset", "Threat", "Control", "Evidence"],
    "D54": ["User action", "Trace id", "RED metrics", "Where it broke"],
    "D55": ["Context", "Options", "Tradeoff", "What you would revisit"],
    "D56": ["Claim", "Metric / log", "Counter-option", "Decision"],
    "D57": ["Situation", "Task", "Action", "Result"],
    "D58": ["Own it", "Restore", "Root cause", "Change the system"],
    "D59": ["Problem", "Options", "Why this", "What we monitor"],
    "D60": ["Baseline", "Change", "p95 / cost / tickets", "What moved"],
    "D61": ["Abstract", "Encapsulate", "Interface", "Virtual vs abstract"],
    "D62": ["Old design", "Change request", "OCP / DIP move", "What stayed closed"],
    "D63": ["Repo query", "UoW / SaveChanges", "One transaction", "When skip repo"],
    "D64": ["Command", "Write model", "Event", "Read model"],
    "D65": ["Order", "Payment", "Inventory", "Ship / compensate"],
    "D66": ["Model", "Fluent map", "Migrate", "SP only if needed"],
    "D67": ["Store blob", "Keep the key", "Publish reference", "Consumer pulls"],
    "D68": ["IdP login", "JWT", "API validate", "IAM ≠ user token"],
    "D69": ["Users / flow", "Boxes / data", "Failure / scale", "Tradeoff + next"],
    "D70": ["Sync REST", "Async event", "Failure mode", "Size → reference"],
    "D71": ["Middleware in", "Action", "Unwind catch", "ProblemDetails + trace"],
    "D72": ["What", "Where", "Why", "How / evidence"],
    # Angular
    "A01": ["ctor (DI only)", "ngOnInit", "View ready", "ngOnDestroy"],
    "A02": ["Parent", "@Input down", "Child", "@Output up"],
    "A03": ["provideIn root", "Inject in ctor", "One instance?", "HTTP in service"],
    "A04": ["Login API", "Store tokens", "Interceptor Bearer", "Refresh on 401"],
    "A05": ["Need after tab close?", "localStorage", "sessionStorage", "Memory if secret"],
    "A06": ["Clone request", "Add Bearer", "401?", "Refresh once / fail"],
    "A07": ["URL", "CanActivate", "Component", "API still authorizes"],
    "A08": ["Hide the route", "Call API", "401 vs 403", "Never trust SPA"],
    "A09": ["Observable", "map / catchError", "UI subscribe", "unsubscribe"],
    "A10": ["Event", "Reducer", "New state", "Select in view"],
    "A11": ["Emulated default", "ShadowDom", "None = leak", "Avoid ::ng-deep"],
    "A12": ["environment.*", "Build config", "CI pipeline", "Same artifact"],
    "A13": ["HTTP error", "Friendly text", "Trace id", "Retry only safe"],
    "A14": ["What / where", "Interceptor", "Guard vs API", "Honesty"],
    # AWS
    "W01": ["Angular", "API Gateway", ".NET on ECS", "SQL"],
    "W02": ["Human user", "Task role", "Policy", "No keys in SPA"],
    "W03": ["User pool", "JWT", "Gateway / API", "Or name real IdP"],
    "W04": ["WAF", "TLS / Gateway", "[Authorize]", "IAM on AWS APIs"],
    "W05": ["Dockerfile", "Image", "Push ECR", "Run container"],
    "W06": ["SDK stage", "Publish", "Runtime image", "Secrets at run"],
    "W07": ["Git / CI", "ECR image", "Task definition", "Service + ALB"],
    "W08": ["Env / secrets", "New revision", "Health fail?", "Stopped reason"],
    "W09": ["Pod ≈ task", "Deploy ≈ service", "K8s Service ≈ LB", "Don't overclaim"],
    "W10": ["Spike", "ALB", "More tasks", "DB / pool next"],
    "W11": ["Measure", "Idle / size", "Autoscale", "Then storage / logs"],
    "W12": ["Event + short", "Lambda OK", "Long API", "Stay on ECS"],
    "W13": ["App emit", "Logs", "Metrics", "Traces → alert"],
    "W14": ["Commit", "Build / test", "Push ECR", "ECS rolling"],
    "W15": ["SPA", "Gateway", "ECS API", "SQL + observe"],
    "W16": ["What", "Where", "Why", "How / evidence"],
    # SQL
    "S01": ["Table A", "ON key", "INNER or LEFT", "Result set"],
    "S02": ["Nested subquery", "Name CTE", "Join the CTE", "Read as steps"],
    "S03": ["#temp (stats)", "table var", "Recompile?", "Pick for cardinality"],
    "S04": ["Params", "Proc body", "Set-based", "Caller gets contract"],
    "S05": ["Scalar / TVF", "Use in SELECT", "No side effects", "Not a proc"],
    "S06": ["Clustered PK", "Nonclustered", "Key order", "Seek vs scan"],
    "S07": ["View = saved SELECT", "Query the view", "Index if needed", "Not a security wall"],
    "S08": ["BEGIN TRAN", "Work", "COMMIT", "or ROLLBACK"],
    "S09": ["Reproduce", "Actual plan", "One change", "Measure"],
    "S10": ["Parameter", "Sniffed plan", "Seek or scan", "OPTIMIZE FOR / recompile"],
    "S11": ["Isolation", "Locks", "Cycle wait", "Victim + retry"],
    "S12": ["Expand", "Deploy", "Verify", "Rollback script"],
    "S13": ["Primary writes", "Replica reads", "Lag", "DB per service?"],
    "S14": ["What", "Where", "Why", "How / evidence"],
}

# Full-page layout (not a shared 6-panel grid). Neighbours use different kinds.
LAYOUT_BY_ID: dict[str, str] = {
    "D01": "vs_split",
    "D02": "code_callout",
    "D03": "cards",
    "D04": "before_after",
    "D05": "layers",
    "D06": "loop",
    "D07": "fork",
    "D08": "containment",
    "D09": "hub",
    "D10": "matrix",
    "D11": "cards",
    "D12": "timeline",
    "D13": "hub",
    "D14": "matrix",
    "D15": "hero_flow",
    "D16": "layers",
    "D17": "matrix",
    "D18": "vs_split",
    "D19": "swimlane",
    "D20": "containment",
    "D21": "loop",
    "D22": "timeline",
    "D23": "cards",
    "D24": "hub",
    "D25": "loop",
    "D26": "layers",
    "D27": "vs_split",
    "D28": "matrix",
    "D29": "fork",
    "D30": "loop",
    "D31": "vs_split",
    "D32": "fork",
    "D33": "containment",
    "D34": "vs_split",
    "D35": "timeline",
    "D36": "zigzag",
    "D37": "cards",
    "D38": "star_story",
    "D39": "timeline",
    "D40": "zigzag",
    "D41": "before_after",
    "D42": "zigzag",
    "D43": "hero_flow",
    "D44": "timeline",
    "D45": "matrix",
    "D46": "layers",
    "D47": "swimlane",
    "D48": "vs_split",
    "D49": "loop",
    "D50": "before_after",
    "D51": "cards",
    "D52": "hub",
    "D53": "hub",
    "D54": "swimlane",
    "D55": "star_story",
    "D56": "fork",
    "D57": "star_story",
    "D58": "before_after",
    "D59": "star_story",
    "D60": "cards",
    "D61": "vs_split",
    "D62": "timeline",
    "D63": "containment",
    "D64": "vs_split",
    "D65": "hero_flow",
    "D66": "code_callout",
    "D67": "containment",
    "D68": "swimlane",
    "D69": "star_story",
    "D70": "vs_split",
    "D71": "layers",
    "D72": "drill",
    "A01": "layers",
    "A02": "vs_split",
    "A03": "containment",
    "A04": "swimlane",
    "A05": "vs_split",
    "A06": "loop",
    "A07": "hero_flow",
    "A08": "fork",
    "A09": "loop",
    "A10": "cards",
    "A11": "vs_split",
    "A12": "hero_flow",
    "A13": "before_after",
    "A14": "drill",
    "W01": "swimlane",
    "W02": "vs_split",
    "W03": "swimlane",
    "W04": "layers",
    "W05": "hero_flow",
    "W06": "code_callout",
    "W07": "layers",
    "W08": "fork",
    "W09": "vs_split",
    "W10": "zigzag",
    "W11": "timeline",
    "W12": "vs_split",
    "W13": "hub",
    "W14": "hero_flow",
    "W15": "swimlane",
    "W16": "drill",
    "S01": "vs_split",
    "S02": "code_callout",
    "S03": "vs_split",
    "S04": "code_callout",
    "S05": "cards",
    "S06": "matrix",
    "S07": "containment",
    "S08": "loop",
    "S09": "timeline",
    "S10": "fork",
    "S11": "loop",
    "S12": "timeline",
    "S13": "layers",
    "S14": "drill",
}

COMPARE_PAIR: dict[str, tuple[str, str, str, str]] = {
    "D01": ("Value type", "Bits live in the variable (int, struct).", "Reference type", "Variable holds an arrow to the heap."),
    "D03": ("out (covariant)", "Producer — IEnumerable<out T>.", "in (contravariant)", "Consumer — IComparer<in T>."),
    "D18": ("Tracking", "SaveChanges can update these rows.", "AsNoTracking", "Read-only; cheaper; no sneak writes."),
    "D32": ("EF / ORM", "CRUD, change tracker, navigations.", "Native SQL", "Set-based reports, hints, TVPs."),
    "D34": ("SQL model", "Joins, constraints, transactions.", "NoSQL model", "Access pattern first, then store."),
    "D48": ("TTL only", "Stale until the clock expires.", "Event invalidate", "Drop the key when the write happens."),
    "D61": ("Interface", "Can do — no shared code required.", "Abstract class", "Is a — shared implementation."),
    "D64": ("Command", "Change state; may emit events.", "Query", "Read model; no side effects."),
    "D70": ("REST", "Request/response, easier debugging.", "Events", "Decouple; at-least-once; size matters."),
    "A02": ("@Input", "Parent → child data.", "@Output", "Child → parent events."),
    "A05": ("localStorage", "Survives tab close; XSS risk.", "sessionStorage", "Dies with the tab."),
    "A08": ("CanActivate", "Hides a route in the SPA.", "[Authorize]", "The API is the real gate."),
    "A11": ("Emulated", "Default; unique attributes.", "None", "Styles leak globally — avoid."),
    "S01": ("INNER JOIN", "Only rows that match both sides.", "LEFT JOIN", "Keep left rows; nulls on the right."),
    "S02": ("Subquery", "Fine when short and local.", "CTE", "Named step you can read and reuse."),
    "S03": ("#temp table", "Statistics; better for many rows.", "table variable", "Often underestimated cardinality."),
    "W02": ("IAM user / key", "A person or a leftover secret.", "Task role", "ECS/Lambda assumes; temporary creds."),
    "W09": ("ECS task/service", "What this project actually ran.", "K8s pod/deploy", "Awareness names only unless you operated it."),
    "W12": ("Lambda", "Short event: S3 → thumbnail.", "ECS API", "Request/response, long-lived."),
}


def layout_kind(skill_id: str) -> str:
    return LAYOUT_BY_ID.get(skill_id, "hero_flow")


def picture_kind(skill_id: str) -> str:
    return layout_kind(skill_id)


def compare_pair(skill_id: str) -> tuple[str, str, str, str] | None:
    return COMPARE_PAIR.get(skill_id)
