"""Core .NET, ASP.NET Core, and data skill catalog entries D01-D36."""


def _entry(
    skill_id,
    area,
    title,
    skill_item,
    level3,
    subtopics,
    def_intro,
    concepts,
    interview,
    mistake,
    code=None,
    expected="",
):
    """Build one consistently structured teaching entry."""
    return {
        "id": skill_id,
        "area": area,
        "title": title,
        "skill_item": skill_item,
        "level3": level3,
        "subtopics": subtopics,
        "def_intro": def_intro,
        "def_bullets": [
            f"<b>{label}:</b> {detail}" for label, detail in concepts
        ],
        "interview": interview,
        "table_headers": ["Idea", "Remember"],
        "table_rows": [[f"<code>{label}</code>", detail] for label, detail in concepts],
        "mistakes": [mistake],
        "quiz": [
            (
                f"What is the practical purpose of <code>{concepts[0][0]}</code>?",
                concepts[0][1],
            ),
            (
                f"When does <code>{concepts[1][0]}</code> matter?",
                concepts[1][1],
            ),
            (
                "What evidence demonstrates Level-3 skill here?",
                level3,
            ),
        ],
        "practice": [
            f"Explain <code>{concepts[0][0]}</code> with a project example.",
            f"Compare <code>{concepts[1][0]}</code> with an alternative.",
            f"Prepare evidence for: {level3}",
        ],
        "code": code,
        "expected": expected,
        "steps": None,
    }


SKILLS_PART1 = [
    _entry(
        "D01",
        "D1",
        "C# Type System",
        "C# type system: value vs reference types, boxing, structs vs classes",
        "Names a place boxing or struct choice affected performance",
        ["Value types", "References", "Boxing", "Struct design"],
        "A telemetry loop became expensive because each tiny value crossed an <code>object</code> boundary and was silently <b>boxed</b>.",
        [
            ("Value type", "Stores its value directly; assignment normally copies the value."),
            ("Reference type", "Variables hold references to objects, so assignments can share mutable state."),
            ("Boxing", "Converting a value type to <code>object</code> or an interface may allocate an object."),
            ("Struct choice", "Prefer small, immutable structs with value semantics; use classes for identity or shared mutation."),
        ],
        "I choose a struct only when value semantics and its size make copying reasonable. In a hot path I verify boxing and allocation claims with a profiler or benchmark rather than relying on intuition.",
        (
            "Box every measurement in List<object>",
            "List<object> values = new(); values.Add(42);",
            "List<int> values = new(); values.Add(42);",
        ),
    ),
    _entry(
        "D02",
        "D1",
        "LINQ Execution Internals",
        "LINQ internals: deferred execution, IEnumerable vs IQueryable",
        "Explains a bug caused by deferred execution or multiple enumeration",
        ["Deferred execution", "Enumeration", "IEnumerable", "IQueryable"],
        "A query looked frozen in time, but every enumeration reran it against changed data because LINQ had stored a <b>recipe</b>, not results.",
        [
            ("Deferred", "Most LINQ operators execute when the sequence is enumerated, not when the query is declared."),
            ("IEnumerable", "Runs .NET delegates in the process over objects the application can enumerate."),
            ("IQueryable", "Builds an expression tree that a provider translates, often into SQL."),
            ("Materialize", "Use <code>ToList()</code> deliberately when a stable snapshot or single execution is required."),
        ],
        "I first identify where execution occurs: in memory for IEnumerable or at the provider for IQueryable. I also watch for logging, counting, and iteration accidentally enumerating an expensive query more than once.",
        (
            "Enumerate an expensive query twice",
            "if (query.Any()) foreach (var x in query) { /* use x */ }",
            "var items = query.ToList(); if (items.Count > 0) foreach (var x in items) { /* use x */ }",
        ),
        """var numbers = new List<int> { 1, 2, 3 };
var evens = numbers.Where(n => n % 2 == 0);
numbers.Add(4);
Console.WriteLine(string.Join(",", evens));""",
        "2,4",
    ),
    _entry(
        "D03",
        "D1",
        "Generics and Variance",
        "Generics and variance (in/out)",
        "Explains covariance with a practical example, not just definitions",
        ["Generic safety", "Covariance", "Contravariance", "Invariance"],
        "A report API could return dogs as animals without copying because its producer contract was safely marked <code>out</code>.",
        [
            ("Generics", "Provide compile-time type safety and reusable algorithms without routine casts."),
            ("out", "Covariance permits a producer such as <code>IEnumerable<Dog></code> where <code>IEnumerable<Animal></code> is expected."),
            ("in", "Contravariance permits a consumer of a broader type where a narrower consumer is expected."),
            ("Invariant", "Mutable types such as <code>List<T></code> stay invariant because both reading and writing T must be safe."),
        ],
        "I explain variance by direction: producers can be covariant and consumers can be contravariant. List<T> cannot be covariant because adding a Cat through a List<Animal> view would corrupt a List<Dog>.",
        (
            "Assume List<T> is covariant",
            "List<Dog> dogs = new(); List<Animal> animals = dogs; // unsafe and rejected",
            "IEnumerable<Animal> animals = new List<Dog>(); // safe producer view",
        ),
        """IEnumerable<string> words = new[] { "safe", "variance" };
IEnumerable<object> objects = words;
Console.WriteLine(objects.Count());""",
        "2",
    ),
    _entry(
        "D04",
        "D1",
        "Exception Handling Strategy",
        "Exception handling strategy and custom exceptions",
        "Defends their project's exception strategy incl. global handling",
        ["Exception boundaries", "Custom exceptions", "Global handling", "Preserved stacks"],
        "A failed order should become one consistent API error at the <b>boundary</b>, while its original stack remains available to operations.",
        [
            ("Throw", "Use exceptions for exceptional failures, not ordinary branching or validation flow."),
            ("Custom type", "Add a domain exception when callers need stable semantic meaning or structured data."),
            ("Global handler", "Map known exceptions to controlled responses and log unexpected failures once."),
            ("Rethrow", "Use bare <code>throw;</code> to preserve the original stack trace."),
        ],
        "My services throw meaningful domain or infrastructure exceptions and a global handler maps known cases to ProblemDetails. Unexpected exceptions receive a correlation ID, are logged once, and return no sensitive details.",
        (
            "Destroy the original stack",
            "catch (Exception ex) { throw ex; }",
            "catch { throw; }",
        ),
        """try
{
    throw new InvalidOperationException("order closed");
}
catch (InvalidOperationException ex)
{
    Console.WriteLine($"Handled: {ex.Message}");
}""",
        "Handled: order closed",
    ),
    _entry(
        "D05",
        "D1",
        "CLR Memory Management",
        "CLR memory and resource management: allocations, GC generations, LOH, IDisposable, finalizers and memory-pressure diagnosis",
        "Explains a real memory or resource-pressure issue, identifies whether it was caused by allocations, retained references or undisposed resources, and describes how it was verified.",
        ["GC generations", "Large Object Heap", "IDisposable", "Retention diagnosis"],
        "Memory kept climbing after traffic fell, so the team separated <b>allocation rate</b> from retained objects and leaked native resources.",
        [
            ("Generations", "The GC promotes surviving objects; long-lived references can move objects into older generations."),
            ("LOH", "Large allocations generally land on the Large Object Heap and can increase pause and fragmentation pressure."),
            ("IDisposable", "Dispose deterministic resources promptly with <code>using</code>; GC timing is not resource cleanup."),
            ("Diagnosis", "Use counters and dumps to distinguish high churn, rooted retention, and undisposed handles."),
        ],
        "I compare allocation rate, heap size after collections, object roots, and handle counts. That evidence tells me whether to reduce allocations, remove a retaining reference, or fix deterministic disposal.",
        (
            "Use a finalizer as normal cleanup",
            "Wait for GC to close streams and database handles.",
            "Use using/await using; reserve finalizers for owned unmanaged resources.",
        ),
    ),
    _entry(
        "D06",
        "D1",
        "Async Await Mechanics",
        "Async/await: state machine, sync-over-async, cancellation, timeouts and exception propagation",
        "Explains a real async issue involving blocking, cancellation, timeout, parallel calls or exception handling, and how it was fixed",
        ["State machine", "No blocking", "Cancellation", "Timeouts"],
        "A fast endpoint stalled under load because each request blocked on <code>.Result</code>, tying up workers that its continuation needed.",
        [
            ("State machine", "The compiler transforms <code>async</code> methods so work can suspend and resume around awaits."),
            ("Async all way", "Await asynchronous work instead of blocking with <code>.Result</code> or <code>.Wait()</code>."),
            ("Cancellation", "Accept and pass <code>CancellationToken</code>; cancellation is cooperative, not forced termination."),
            ("Timeout", "Define a time budget explicitly and distinguish timeout, cancellation, and dependency failure."),
        ],
        "I keep the call chain async, propagate the request cancellation token, and apply explicit dependency timeouts. For parallel calls I await Task.WhenAll and handle the resulting failure semantics deliberately.",
        (
            "Block an async operation",
            "var result = client.GetStringAsync(url).Result;",
            "var result = await client.GetStringAsync(url, cancellationToken);",
        ),
    ),
    _entry(
        "D07",
        "D1",
        "Threading and TPL",
        "Threading and TPL: Task vs Thread, parallelism, lock/Interlocked",
        "Picks the right construct for 3 scenario types with reasons",
        ["Task", "Thread", "Parallelism", "Synchronization"],
        "A counter lost updates even though every worker ran successfully; <code>++</code> was a read-modify-write race.",
        [
            ("Task", "Represents asynchronous work; use it for composition and thread-pool scheduling."),
            ("Thread", "Use a dedicated thread only for requirements such as affinity or a long-lived blocking loop."),
            ("Parallel", "Use bounded parallelism for independent CPU-bound work, not to make I/O artificially synchronous."),
            ("Interlocked", "Use atomic operations for simple shared counters and <code>lock</code> for multi-step invariants."),
        ],
        "For I/O I choose async Tasks, for independent CPU work I consider bounded parallelism, and for affinity I may choose a dedicated Thread. I minimize shared state and select Interlocked or lock based on the invariant.",
        (
            "Race on a shared counter",
            "Parallel.For(0, 1000, _ => count++);",
            "Parallel.For(0, 1000, _ => Interlocked.Increment(ref count));",
        ),
        """int count = 0;
Parallel.For(0, 1000, _ => Interlocked.Increment(ref count));
Console.WriteLine(count);""",
        "1000",
    ),
    _entry(
        "D08",
        "D1",
        "Channels and Backpressure",
        "Producer/consumer patterns: concurrent collections, System.Threading.Channels and backpressure",
        "Explains a producer/consumer flow they built, why they chose a concurrent collection or Channel, and how overload, completion and failure were handled",
        ["Producer consumer", "Channels", "Backpressure", "Completion"],
        "When producers outran workers, an unbounded queue turned a traffic spike into an outage; a <b>bounded channel</b> made overload explicit.",
        [
            ("Channel", "Provides async producer/consumer coordination with single- or multi-reader/writer options."),
            ("Bounded", "A bounded channel caps memory and defines whether writers wait, drop, or reject work."),
            ("Completion", "Complete the writer and let readers drain; propagate terminal errors deliberately."),
            ("Concurrent collection", "Choose a concurrent collection when its synchronous access pattern matches the workflow."),
        ],
        "I describe queue capacity, writer behavior at capacity, worker concurrency, and shutdown draining. I also explain how failed items are retried or quarantined without silently losing completion signals.",
        (
            "Hide overload in an unbounded queue",
            "Queue every item indefinitely.",
            "Set a measured capacity and define wait, reject, or drop behavior.",
        ),
    ),
    _entry(
        "D09",
        "D1",
        "Delegates Events Expressions",
        "Delegates, events and expression trees",
        "Gives a practical delegate or event example and explains how an expression tree used by IQueryable differs from an executable delegate",
        ["Delegates", "Events", "Expression trees", "Queryable"],
        "The same lambda can be executable behavior or inspectable data: a delegate runs it, while an <b>expression tree</b> lets a provider translate it.",
        [
            ("Delegate", "A type-safe reference to executable method behavior."),
            ("Event", "Restricts subscription and publication so only the declaring type raises notifications."),
            ("Expression", "<code>Expression&lt;Func&lt;T,bool&gt;&gt;</code> represents code as a traversable tree."),
            ("Provider", "IQueryable providers inspect expression trees and translate supported nodes into another language."),
        ],
        "I use delegates for callbacks and events for one-to-many notifications with controlled publication. IQueryable receives expression trees, so provider translation rules apply; an arbitrary compiled method may not translate to SQL.",
        (
            "Treat every method as SQL-translatable",
            "query.Where(x => MyLocalCheck(x.Name))",
            "Use provider-supported expressions or materialize intentionally before local evaluation.",
        ),
        """Func<int, int> square = x => x * x;
Action<int> print = value => Console.WriteLine(value);
print(square(5));""",
        "25",
    ),
    _entry(
        "D10",
        "D1",
        "Reflection and Attributes",
        "Reflection and attribute-based framework behaviour",
        "Explains how attributes are discovered and acted upon at runtime in a framework or feature they used",
        ["Metadata", "Discovery", "Activation", "Caching"],
        "A small attribute did nothing by itself; framework code used <b>reflection</b> to discover its metadata and apply behavior.",
        [
            ("Attribute", "Adds metadata to assemblies, types, members, or parameters."),
            ("Reflection", "Reads type metadata and can inspect or invoke members dynamically."),
            ("Framework action", "A scanner, filter provider, serializer, or DI component interprets discovered attributes."),
            ("Cost", "Cache repeated metadata lookups and avoid unconstrained scanning on hot paths."),
        ],
        "Attributes are passive metadata. I explain which framework component scans them, when that scan happens, how instances or policies are built, and whether the result is cached.",
        (
            "Assume an attribute executes itself",
            "[Audit] automatically runs auditing.",
            "A runtime component must discover [Audit] and invoke the audit behavior.",
        ),
    ),
    _entry(
        "D11",
        "D1",
        "Allocation Aware C#",
        "Performance-minded C#: Span<T>/Memory<T>, allocations, benchmarking",
        "Has measured with BenchmarkDotNet or similar on a real hot path",
        ["Span", "Memory", "Allocations", "Benchmarking"],
        "A parser became cheaper when it sliced existing buffers with <code>Span&lt;T&gt;</code> instead of creating a new string for every field.",
        [
            ("Span", "A stack-only view over contiguous memory, useful for synchronous parsing and slicing."),
            ("Memory", "A heap-storable memory view suitable across asynchronous boundaries."),
            ("Allocation", "Remove allocations only on measured hot paths; readability remains a design constraint."),
            ("Benchmark", "Use representative data, warmup, multiple runs, and allocation diagnostics."),
        ],
        "I profile first, isolate the hot path, then benchmark the smallest meaningful change. I report both time and allocation results and verify that Span-based code preserves correctness.",
        (
            "Optimize from intuition",
            "Rewrite all strings as spans before measuring.",
            "Profile, benchmark a representative case, then optimize the proven hot path.",
        ),
    ),
    _entry(
        "D12",
        "D1",
        "Modern .NET Migration",
        "Platform evolution: .NET Framework versus modern .NET and migration realities",
        "Explains what a .NET Framework or older .NET migration to a supported modern .NET version involves, including dependencies, configuration, hosting, authentication and deployment",
        ["Compatibility", "Dependencies", "Hosting", "Deployment"],
        "Changing the target framework was the smallest part of migration; unsupported libraries, configuration, authentication, and hosting carried the real risk.",
        [
            ("Inventory", "Map projects, APIs, NuGet packages, Windows-only dependencies, and deployment assumptions."),
            ("Modernize", "Replace unsupported framework features and move configuration and hosting to modern patterns."),
            ("Validate", "Test authentication, serialization, globalization, networking, and operational behavior."),
            ("Rollout", "Use staged deployment, telemetry, and a rollback path rather than a big-bang switch."),
        ],
        "I treat migration as a compatibility and operations program, not a project-file edit. I inventory dependencies first, create test seams, and validate hosting, auth, configuration, and deployment in production-like environments.",
        (
            "Retarget and declare success",
            "Only change TargetFramework.",
            "Inventory dependencies and validate runtime, hosting, auth, configuration, and rollout.",
        ),
    ),
    _entry(
        "D13",
        "D1",
        "Runtime Diagnostics Tools",
        "Diagnostics: dotnet-trace/counters, dump analysis",
        "Has diagnosed a real issue with runtime diagnostics tooling",
        ["Counters", "Tracing", "Dumps", "Evidence"],
        "CPU was high but logs were quiet, so runtime counters narrowed the symptom and a trace revealed the hot call stacks.",
        [
            ("Counters", "Observe live rates and gauges such as CPU, allocation rate, GC, exceptions, and thread-pool state."),
            ("Trace", "Capture time-based runtime events and stacks to locate expensive or blocked work."),
            ("Dump", "Inspect a process snapshot for heaps, roots, threads, locks, and exception state."),
            ("Method", "Start with a hypothesis, collect the least disruptive evidence, and compare before and after."),
        ],
        "I correlate service symptoms with runtime counters, then capture a focused trace or dump. I can explain the evidence, the hypothesis it ruled in or out, and the post-fix measurement.",
        (
            "Collect everything without a question",
            "Take large dumps repeatedly in production.",
            "Form a hypothesis and choose counters, trace, or dump with known operational cost.",
        ),
    ),
    _entry(
        "D14",
        "D1",
        "NuGet Dependency Resolution",
        "NuGet and dependency management: versioning, conflicts, transitive pins",
        "Has resolved a dependency conflict and explains the mechanism",
        ["Direct dependencies", "Transitive graph", "Version ranges", "Locking"],
        "A harmless package update changed a transitive version and broke runtime loading, so the team inspected the <b>resolved graph</b>, not just direct references.",
        [
            ("Graph", "Restore resolves direct and transitive package requirements into one dependency graph."),
            ("Conflict", "Incompatible constraints or runtime assets can cause restore warnings, compile failures, or runtime errors."),
            ("Pin", "A direct reference can intentionally constrain a transitive version, but ownership and upgrades must be documented."),
            ("Repeatability", "Central versions and lock files can make dependency resolution more consistent."),
        ],
        "I inspect the resolved graph and assets file to identify who requested each version. Then I align compatible package families, add a deliberate direct pin only when needed, and test runtime behavior.",
        (
            "Suppress a package warning blindly",
            "Ignore NU1605 and ship.",
            "Trace the dependency path, align constraints, and verify the resolved runtime assets.",
        ),
    ),
    _entry(
        "D15",
        "D2",
        "ASP.NET Core Pipeline",
        "ASP.NET Core pipeline: middleware order, filters, endpoint routing",
        "Traces a request end to end; explains why middleware order matters with a case",
        ["Middleware", "Routing", "Filters", "Endpoints"],
        "Authorization appeared configured but never protected an endpoint because pipeline order placed it before routing had selected endpoint metadata.",
        [
            ("Middleware", "Runs in registration order on the way in and unwinds in reverse on the way out."),
            ("Routing", "Matches an endpoint and exposes its metadata for later middleware."),
            ("Filters", "Wrap MVC or endpoint execution at framework-specific stages, not the entire server pipeline."),
            ("Order", "Exception handling, routing, authentication, authorization, and endpoints must be deliberately ordered."),
        ],
        "I trace a request from Kestrel through exception handling, routing, authentication, authorization, endpoint filters or MVC filters, and the response. Order matters because each component depends on context established earlier.",
        (
            "Place exception handling too late",
            "Register the exception handler after endpoints.",
            "Register boundary exception handling early enough to wrap downstream execution.",
        ),
    ),
    _entry(
        "D16",
        "D2",
        "DI Lifetimes and Captivity",
        "Built-in DI: lifetimes and the captive-dependency trap",
        "Explains a scoped-in-singleton bug and how lifetimes should be chosen",
        ["Transient", "Scoped", "Singleton", "Scopes"],
        "A singleton worker captured a scoped DbContext, turning per-operation state into a long-lived object shared far beyond its intended boundary.",
        [
            ("Transient", "Creates an instance at each resolution; suitable for lightweight stateless services."),
            ("Scoped", "Creates one instance per scope, commonly one web request or explicit background-work scope."),
            ("Singleton", "Creates one application-wide instance and therefore requires thread-safe state and dependencies."),
            ("Captive", "A longer-lived service must not directly retain a shorter-lived dependency."),
        ],
        "I choose lifetime from state ownership and concurrency, not habit. A singleton background service creates a scope per unit of work and resolves scoped services inside that scope.",
        (
            "Inject DbContext into a singleton",
            "SingletonWorker(AppDbContext db)",
            "Inject IServiceScopeFactory and resolve AppDbContext inside each work scope.",
        ),
    ),
    _entry(
        "D17",
        "D2",
        "Reliable Web API Contracts",
        "Web APIs: model binding, validation, versioning, ProblemDetails",
        "Shows their error-contract design and how validation failures reach clients",
        ["Model binding", "Validation", "Versioning", "ProblemDetails"],
        "Clients stopped parsing one-off error shapes when every failure—validation, domain conflict, or server error—used one stable <code>ProblemDetails</code> contract.",
        [
            ("Binding", "Converts route, query, header, form, and body inputs into endpoint parameters or models."),
            ("Validation", "Rejects invalid input at a clear boundary and returns field-level details where safe."),
            ("Versioning", "Evolves contracts with an explicit compatibility and retirement policy."),
            ("ProblemDetails", "Provides a standard machine-readable error shape with stable type and status semantics."),
        ],
        "I define successful and error contracts together. Validation failures are normalized centrally, domain exceptions map to documented statuses, and trace IDs help support without leaking internals.",
        (
            "Return arbitrary error strings",
            "return BadRequest(ex.Message);",
            "Return a documented ProblemDetails type with safe detail and trace ID.",
        ),
    ),
    _entry(
        "D18",
        "D2",
        "EF Core Query Behavior",
        "EF Core: change tracking, loading strategies, N+1, migrations",
        "Has found and fixed an N+1; explains tracking vs no-tracking choices",
        ["Tracking", "Loading", "N+1", "Migrations"],
        "A page issued one order query and then one customer query per row; projection replaced the hidden <b>N+1</b> round trips with one shaped query.",
        [
            ("Tracking", "Use tracking when entities will be changed and saved in the same unit of work."),
            ("No tracking", "Use <code>AsNoTracking</code> for read-only results to reduce tracking overhead."),
            ("Loading", "Choose projection, eager, explicit, or lazy loading with query count and payload in mind."),
            ("N+1", "Detect repeated per-row queries through SQL logs or tracing and reshape the query."),
        ],
        "I prove N+1 with command counts and SQL traces, then project only the required shape or eager-load deliberately. Tracking is a correctness feature for updates, not a default requirement for every read.",
        (
            "Lazy-load inside a loop",
            "foreach (var o in orders) Use(o.Customer.Name);",
            "Project order and customer fields in one database query.",
        ),
    ),
    _entry(
        "D19",
        "D2",
        "Authentication Flow Design",
        "Auth: ASP.NET Identity, JWT bearer, OAuth2/OIDC flows",
        "Draws their auth flow end to end incl. token validation and expiry",
        ["Identity", "OAuth2", "OIDC", "JWT validation"],
        "A JWT is not trusted because it can be decoded; the API trusts it only after validating its <b>signature, issuer, audience, and lifetime</b>.",
        [
            ("Identity", "ASP.NET Core Identity manages local users, credentials, tokens, and related account workflows."),
            ("OAuth2", "Delegates authorization and access to protected resources through defined flows."),
            ("OIDC", "Adds authentication and identity claims on top of OAuth 2.0."),
            ("Validation", "Validate signature, issuer, audience, lifetime, and required authorization claims."),
        ],
        "I trace browser or client redirection, authorization code exchange with PKCE where applicable, token issuance, API bearer validation, expiry, and refresh. Authentication establishes identity; authorization still decides access.",
        (
            "Trust decoded claims",
            "Read payload roles without signature validation.",
            "Use JWT bearer validation with trusted authority, audience, keys, and lifetime checks.",
        ),
    ),
    _entry(
        "D20",
        "D2",
        "Configuration and Options",
        "Configuration and options pattern; secrets management",
        "Explains IOptions usage and where secrets never appear",
        ["Providers", "Options", "Validation", "Secrets"],
        "The same service ran in every environment because providers supplied settings externally and strongly typed options failed fast when configuration was invalid.",
        [
            ("Providers", "Configuration composes sources with defined precedence, such as JSON, environment variables, and command line."),
            ("Options", "Bind related settings to typed classes and inject the appropriate options interface."),
            ("Validation", "Validate required values and ranges at startup when invalid configuration should block deployment."),
            ("Secrets", "Keep secrets out of source, images, logs, and client-delivered configuration; use a managed secret store."),
        ],
        "I use typed options and startup validation, and I choose IOptions, IOptionsSnapshot, or IOptionsMonitor based on lifetime and reload needs. Secrets enter through the deployment platform or vault and are never committed or logged.",
        (
            "Commit production secrets",
            "Store passwords in appsettings.json.",
            "Reference a secret provider and inject values at runtime with restricted access.",
        ),
    ),
    _entry(
        "D21",
        "D2",
        "Caching and Invalidation",
        "Caching: IMemoryCache vs distributed cache, invalidation",
        "Explains what they cached, why, and how staleness was bounded",
        ["Local cache", "Distributed cache", "Invalidation", "Stampedes"],
        "Caching made reads faster but introduced a second truth, so the design began with an explicit <b>staleness budget</b> and invalidation plan.",
        [
            ("Memory", "<code>IMemoryCache</code> is process-local, fast, and not shared across replicas."),
            ("Distributed", "A distributed cache shares data across instances but adds network and serialization costs."),
            ("Invalidation", "Bound staleness with expiration, versioned keys, events, or explicit removal."),
            ("Stampede", "Coalesce refreshes or add jitter so many misses do not overload the dependency."),
        ],
        "I cache a measured expensive read only when the consistency requirement permits it. I specify key shape, TTL, size policy, invalidation trigger, outage behavior, and stampede protection.",
        (
            "Cache forever",
            "Set entries with no expiry or invalidation.",
            "Define ownership, TTL, invalidation, capacity, and stale-data behavior.",
        ),
    ),
    _entry(
        "D22",
        "D2",
        "Reliable Background Work",
        "Background work: IHostedService/BackgroundService, queues",
        "Explains what happens when a background task fails mid-way",
        ["Hosted services", "Queues", "Retries", "Shutdown"],
        "A fire-and-forget request task vanished during deployment; durable work moved to a queue and a hosted consumer owned retries and shutdown.",
        [
            ("BackgroundService", "Runs application-managed work with a cancellation token tied to host shutdown."),
            ("Queue", "Separates request latency from work and makes capacity, persistence, and retry semantics explicit."),
            ("Failure", "Use idempotency, bounded retries, poison handling, and durable checkpoints as required."),
            ("Shutdown", "Stop accepting work, signal cancellation, and drain or persist safely within the shutdown budget."),
        ],
        "I explain whether work is durable, how it is acknowledged, and what happens after a mid-item crash. The worker creates dependency scopes, observes cancellation, logs correlated failures, and retries only safe operations.",
        (
            "Start unobserved request work",
            "_ = ProcessOrderAsync(order);",
            "Enqueue durable work and let a supervised background consumer process it.",
        ),
    ),
    _entry(
        "D23",
        "D2",
        "Layered .NET Testing",
        "Testing: xUnit, Moq/NSubstitute, WebApplicationFactory integration tests",
        "Defends what they test at each layer incl. one real integration test design",
        ["Unit tests", "Test doubles", "Integration tests", "WebApplicationFactory"],
        "A controller unit test passed while routing and serialization were broken, so one integration test exercised the application through its real HTTP boundary.",
        [
            ("Unit", "Test deterministic business behavior quickly with minimal infrastructure."),
            ("Double", "Mock external boundaries or nondeterminism, not every internal collaborator."),
            ("Integration", "Test components that must agree: routing, DI, middleware, persistence, and serialization."),
            ("Factory", "<code>WebApplicationFactory</code> hosts an ASP.NET Core app for realistic HTTP integration tests."),
        ],
        "I use unit tests for business rules, integration tests for infrastructure seams, and a smaller number of end-to-end checks. A real API integration test sends HTTP, uses isolated data, and asserts status plus contract.",
        (
            "Mock the implementation",
            "Verify every internal method call.",
            "Assert observable behavior; mock only meaningful external boundaries.",
        ),
    ),
    _entry(
        "D24",
        "D2",
        "Logs Metrics and Traces",
        "Logging and observability: ILogger, OpenTelemetry, health checks",
        "Names the dashboards/alerts their service had and one they'd add",
        ["Structured logs", "Metrics", "Traces", "Health checks"],
        "A single correlation ID connected a slow request's trace, dependency span, and structured error log, turning an alert into an explanation.",
        [
            ("Logs", "Use structured properties and scopes; avoid secrets and uncontrolled high-cardinality fields."),
            ("Metrics", "Track rates, errors, duration, saturation, and business signals suitable for dashboards and alerts."),
            ("Traces", "Propagate context across services and dependencies to explain individual request paths."),
            ("Health", "Separate liveness from readiness and keep checks cheap and meaningful."),
        ],
        "I name the service-level indicators, dashboards, and actionable alerts, then show how logs, metrics, and traces correlate. Health checks serve orchestrators and do not replace real telemetry.",
        (
            "Log only prose",
            "logger.LogInformation($\"Order {id} failed\");",
            "logger.LogInformation(\"Order {OrderId} failed\", id);",
        ),
    ),
    _entry(
        "D25",
        "D2",
        "Reliable Message Consumers",
        "Messaging integration (Service Bus/Kafka/RabbitMQ)",
        "Explains consumer failure handling: retry, DLQ, idempotency",
        ["Acknowledgement", "Retry", "Dead letters", "Idempotency"],
        "A consumer processed the same payment twice after crashing before acknowledgement, proving that <b>at-least-once</b> delivery requires idempotent effects.",
        [
            ("Ack", "Acknowledge only after required processing succeeds; understand each broker's delivery semantics."),
            ("Retry", "Retry transient failures with limits and backoff, not permanent validation failures."),
            ("DLQ", "Quarantine poison messages with reason, context, alerts, and a replay procedure."),
            ("Idempotency", "Use stable message IDs, deduplication records, or naturally idempotent writes."),
        ],
        "I explain the complete failure path: delivery, processing, commit, acknowledgement, redelivery, retry exhaustion, and DLQ. Idempotency protects the side effect when failure occurs between commit and ack.",
        (
            "Assume exactly-once end to end",
            "Apply the side effect on every delivery.",
            "Design idempotent handling and acknowledge only after durable success.",
        ),
    ),
    _entry(
        "D26",
        "D2",
        "Hosting and Scaling",
        "Hosting and deployment: Kestrel, IIS, containers, scaling",
        "Explains their deployment topology and one scaling decision",
        ["Kestrel", "Reverse proxy", "Containers", "Scaling"],
        "Adding replicas improved throughput only after session state and file storage stopped living inside one process.",
        [
            ("Kestrel", "The cross-platform ASP.NET Core web server handles application HTTP traffic."),
            ("Proxy", "IIS or another reverse proxy can terminate TLS, apply edge policy, and forward to Kestrel."),
            ("Container", "Package immutable application artifacts with explicit configuration, limits, and health probes."),
            ("Scale", "Scale stateless replicas from measured CPU, latency, concurrency, or queue pressure."),
        ],
        "I can draw load balancer, ingress or IIS, Kestrel processes, dependencies, state stores, probes, and telemetry. I justify replica count and autoscaling signals from bottlenecks rather than assuming horizontal scale fixes everything.",
        (
            "Store required state on local disk",
            "Each replica writes shared uploads locally.",
            "Use an external durable store so any healthy replica can serve the request.",
        ),
    ),
    _entry(
        "D27",
        "D3",
        "SQL Joins and Windows",
        "SQL joins, aggregation, GROUP BY, window functions",
        "Writes a 3-table join with aggregation live; explains a window function they actually used",
        ["Joins", "Aggregation", "GROUP BY", "Window functions"],
        "A sales report joined customers, orders, and lines, then used a window function to rank totals without collapsing each row's context.",
        [
            ("Join", "Choose join type from required row preservation and join on explicit relational keys."),
            ("GROUP BY", "Collapses rows into groups; every selected nonaggregate must belong to the grouping."),
            ("Window", "Computes across a partition while retaining individual rows."),
            ("Grain", "State the intended row grain before joining to avoid accidental multiplication."),
        ],
        "I state the grain first, join three tables on keys, aggregate at the required level, and verify counts. I use window functions for ranking, running totals, or previous-row comparisons without an extra self-join.",
        (
            "Join at the wrong grain",
            "SELECT c.Id, SUM(o.Total) FROM Customer c JOIN Orders o ON ... JOIN OrderLine l ON ... GROUP BY c.Id; -- Total repeats per line",
            "Aggregate line amounts or orders at the intended grain before combining totals.",
        ),
    ),
    _entry(
        "D28",
        "D3",
        "Composite Index Design",
        "Indexing: index types, composite index design, when an index hurts",
        "Names a real index they added, why column order mattered, and the write-cost tradeoff",
        ["B-tree indexes", "Column order", "Covering", "Write cost"],
        "An index on <code>(TenantId, CreatedAt)</code> transformed a tenant timeline query because its leading column matched the equality predicate and its suffix supported range ordering.",
        [
            ("Index", "An index trades storage and write work for faster qualifying reads."),
            ("Order", "Composite column order should reflect equality, range, sorting, selectivity, and engine behavior."),
            ("Covering", "Included columns may avoid base-table lookups but increase index size and maintenance."),
            ("Cost", "Every insert, update, and delete may maintain indexes; unused overlap hurts write throughput."),
        ],
        "I name the query, predicates, ordering, old plan, chosen key order, and measured result. I also quantify added storage and write cost and remove redundant indexes where appropriate.",
        (
            "Index every filter separately",
            "CREATE INDEX ix_a ON Orders(TenantId); CREATE INDEX ix_b ON Orders(CreatedAt);",
            "Design a composite index from the complete query and confirm it in the plan.",
        ),
    ),
    _entry(
        "D29",
        "D3",
        "Reading Query Plans",
        "Reading query plans (EXPLAIN) and tuning a slow query",
        "Walks through a real slow query they fixed: plan before/after",
        ["Plan operators", "Estimates", "Scans and seeks", "Measurements"],
        "The slow query was not fixed by guessing an index; its plan showed a cardinality error that drove an expensive join strategy.",
        [
            ("Plan", "Read operators, data flow, join algorithms, predicates, sorts, and memory behavior."),
            ("Estimate", "Large estimated-versus-actual row gaps can indicate stale statistics or correlated predicates."),
            ("Access", "A scan is not automatically bad and a seek is not automatically good; cost depends on rows and lookups."),
            ("Compare", "Capture duration, reads, rows, and plan before and after one controlled change."),
        ],
        "I begin with the exact query and representative parameters, then inspect actual rows, estimates, access paths, joins, spills, and waits. I validate the fix with before-and-after reads and latency, not plan appearance alone.",
        (
            "Treat every scan as the problem",
            "Add an index because EXPLAIN says Scan.",
            "Check table size, rows consumed, predicates, estimates, and measured I/O first.",
        ),
    ),
    _entry(
        "D30",
        "D3",
        "Transactions Locks Deadlocks",
        "Transactions, isolation levels, locking and deadlocks",
        "Describes a concurrency bug they hit and which isolation/locking choice fixed it",
        ["Atomicity", "Isolation", "Locking", "Deadlocks"],
        "Two valid requests oversold the last unit because each read availability before either committed; correctness required one atomic concurrency strategy.",
        [
            ("Transaction", "Groups operations into an atomic consistency boundary with commit or rollback."),
            ("Isolation", "Controls which concurrent effects are visible and which anomalies are prevented."),
            ("Lock", "Locks protect resources but can block; scope and access order shape contention."),
            ("Deadlock", "A cycle of waits causes one transaction to be chosen as victim; retry and remove the cycle's cause."),
        ],
        "I identify the anomaly first, then choose optimistic concurrency, an atomic statement, or stronger isolation with measured contention. For deadlocks I inspect the graph, normalize access order, shorten transactions, and retry victims safely.",
        (
            "Hold a transaction across remote I/O",
            "BEGIN; update row; call external API; COMMIT;",
            "Keep the database transaction short and coordinate external effects with an outbox or workflow.",
        ),
    ),
    _entry(
        "D31",
        "D3",
        "Schema Design Tradeoffs",
        "Schema design: normalization vs denormalization tradeoffs",
        "Defends a schema they designed, including what they denormalized and why",
        ["Normalization", "Denormalization", "Constraints", "Ownership"],
        "The write model stored each fact once, while a deliberate read model duplicated display data to serve a high-volume query cheaply.",
        [
            ("Normalize", "Separate facts to reduce update anomalies and express relationships clearly."),
            ("Denormalize", "Duplicate or precompute data for a measured read need with an explicit synchronization owner."),
            ("Constraint", "Use keys, foreign keys, uniqueness, and checks to preserve invariants where the database can enforce them."),
            ("Tradeoff", "Evaluate read shape, write rate, consistency tolerance, storage, and operational complexity."),
        ],
        "I describe entities, invariants, access patterns, and growth before presenting tables. If I denormalize, I name the duplicated fact, update mechanism, acceptable lag, repair process, and measured benefit.",
        (
            "Duplicate without ownership",
            "Copy CustomerName into many tables with no update policy.",
            "Document the source of truth, consistency mechanism, lag budget, and repair path.",
        ),
    ),
    _entry(
        "D32",
        "D3",
        "ORM or Native SQL",
        "ORM vs native SQL decisions; batch operations at volume",
        "Explains where they bypassed the ORM in a project and what it bought",
        ["ORM productivity", "Native SQL", "Batching", "Measurement"],
        "The ORM was ideal for ordinary updates, but a million-row reconciliation needed a set-based statement instead of a million tracked entities.",
        [
            ("ORM", "Provides mapping, composable queries, change tracking, and maintainable common data access."),
            ("SQL", "Use native SQL when a provider cannot express or efficiently execute a proven critical operation."),
            ("Batch", "Prefer set-based updates, bulk APIs, staging tables, or bounded batches at volume."),
            ("Safety", "Parameterize SQL, preserve transactions and observability, and isolate database-specific code."),
        ],
        "I choose from correctness, maintainability, generated SQL, volume, and measured performance. When bypassing the ORM, I quantify round trips, allocations, duration, and the extra testing and portability cost.",
        (
            "Load every row to update it",
            "foreach (var row in db.Rows) { row.Flag = true; } SaveChanges();",
            "Use a parameterized set-based update or a measured bulk operation.",
        ),
    ),
    _entry(
        "D33",
        "D3",
        "Connection Pool Sizing",
        "Connection pooling behavior and sizing",
        "Explains pool exhaustion symptoms and how they sized/tuned a pool",
        ["Pool reuse", "Exhaustion", "Sizing", "Leak prevention"],
        "Requests timed out while the database looked idle because all pooled connections were waiting inside long transactions.",
        [
            ("Pool", "Reuses physical connections; logical open and close usually borrow and return a pooled connection."),
            ("Exhaustion", "Appears as acquisition waits or timeouts, often caused by leaks, slow queries, long transactions, or excess concurrency."),
            ("Size", "Size from database capacity, replica count, workload concurrency, and connection hold time."),
            ("Disposal", "Open late, close early, and always dispose connections, commands, and readers."),
        ],
        "I correlate pool waits with active requests, database sessions, query latency, and connection hold time. Increasing the pool is safe only when the database has capacity and the root cause is legitimate concurrency rather than leaked or slow work.",
        (
            "Increase pool size first",
            "Double Max Pool Size whenever timeouts occur.",
            "Measure hold time and database capacity; fix leaks and slow transactions before tuning.",
        ),
    ),
    _entry(
        "D34",
        "D3",
        "Choosing NoSQL Models",
        "NoSQL: when and which (document / KV / columnar); consistency models",
        "Justifies a SQL-vs-NoSQL call with a concrete access pattern, not fashion",
        ["Document", "Key value", "Columnar", "Consistency"],
        "A session lookup needed one key and short-lived value, while financial posting needed relational constraints and transactions; the access pattern chose the store.",
        [
            ("Document", "Fits aggregate-shaped records retrieved and updated mainly as a unit."),
            ("Key-value", "Fits direct key lookup, caching, sessions, counters, and simple value access."),
            ("Columnar", "Column-family or analytical columnar systems serve different large-scale sparse or scan-heavy patterns."),
            ("Consistency", "Choose consistency guarantees from business invariants, conflict behavior, and latency needs."),
        ],
        "I begin with queries, writes, partition key, volume, growth, transaction boundary, and consistency requirement. I justify operational maturity and failure behavior as well as the attractive happy-path performance.",
        (
            "Choose by trend",
            "Use NoSQL because the system must scale.",
            "Prove the access pattern, partitioning, consistency, transactions, and operational tradeoffs.",
        ),
    ),
    _entry(
        "D35",
        "D3",
        "Team Schema Migrations",
        "Schema migrations and versioning in a team (Flyway/Liquibase/EF/Alembic)",
        "Describes their migration discipline incl. a rollback situation",
        ["Versioned changes", "Expand contract", "Deployment", "Rollback"],
        "A zero-downtime rename used two releases: first expand the schema and support both forms, then contract only after old code disappeared.",
        [
            ("Version", "Store ordered migration scripts or metadata in source control and apply each version once."),
            ("Review", "Review locking, duration, data movement, compatibility, and rollback before production."),
            ("Expand-contract", "Add compatible structures first, backfill, switch readers and writers, then remove old structures."),
            ("Rollback", "For destructive or data-changing migrations, forward-fix or restore may be safer than down scripts."),
        ],
        "My pipeline validates migrations on production-like data, records applied versions, and separates long backfills from blocking DDL. I can explain a rollback or forward-fix decision and how application compatibility was preserved.",
        (
            "Rename a live column in one release",
            "ALTER TABLE Customer RENAME COLUMN Name TO DisplayName;",
            "Expand with DisplayName, dual-write/backfill, switch reads, then contract later.",
        ),
    ),
    _entry(
        "D36",
        "D3",
        "Large Data Result Patterns",
        "Data at scale: pagination, streaming large results, archival strategy",
        "Explains how a real endpoint handled large result sets without OOM",
        ["Keyset pagination", "Streaming", "Backpressure", "Archival"],
        "An export endpoint stopped exhausting memory when it streamed bounded batches and stopped materializing the entire result before sending the first byte.",
        [
            ("Pagination", "Prefer stable keyset pagination for deep, changing datasets when offset cost or drift matters."),
            ("Streaming", "Read and write incrementally while keeping connections, cancellation, and partial failure explicit."),
            ("Bounded", "Limit page size and in-flight buffers so slow clients apply backpressure instead of growing memory."),
            ("Archive", "Move cold data under retention and retrieval policies while preserving compliance and query needs."),
        ],
        "I use deterministic ordering and keyset cursors for interactive pages, and bounded streaming for exports. I propagate cancellation, avoid tracking, monitor memory and connection duration, and send very large exports through asynchronous object storage workflows.",
        (
            "Materialize an unlimited query",
            "var rows = await query.ToListAsync(); return rows;",
            "Apply a hard page limit or stream bounded batches with cancellation.",
        ),
    ),
]
