"""Interview-ready .NET skill catalog entries D37-D60 for areas D4-D6."""

SKILLS_PART2 = [
    {
        "id": "D37",
        "area": "D4",
        "title": "Algorithms Under Time Pressure",
        "skill_item": "Data structures & algorithms working fluency (hashing, arrays/strings, complexity)",
        "level3": "Solves a medium problem in-time and states complexity unprompted",
        "subtopics": ["hash maps", "arrays and strings", "Big-O", "edge cases"],
        "def_intro": "A strong candidate turns an ambiguous data problem into a clear algorithm, then explains why its time and space costs fit.",
        "def_bullets": [
            "<b>Clarify:</b> confirm input shape, constraints, and expected output.",
            "<b>Choose:</b> match the access pattern to an array, set, stack, queue, or hash map.",
            "<b>Analyze:</b> state average and worst-case time and space complexity.",
            "<b>Prove:</b> test empty, duplicate, boundary, and representative inputs.",
        ],
        "interview": "I first restate the problem and constraints, then describe a simple baseline before optimizing it. After coding, I walk through edge cases and state the time and space complexity without waiting to be asked.",
        "table_headers": ["Signal", "Good evidence", "Why it matters"],
        "table_rows": [
            ["Constraint awareness", "Uses input size to guide design", "Avoids needless optimization"],
            ["Structure choice", "Explains why a hash map fits", "Shows practical fluency"],
            ["Complexity", "States O(n) time and O(n) space", "Makes cost explicit"],
        ],
        "mistakes": [
            ("Silent coding", "Starts typing immediately", "Clarifies, outlines, then codes"),
            ("Partial finish", "Stops when sample passes", "Tests boundaries and states complexity"),
        ],
        "quiz": [
            ("When is a hash set useful?", "When fast membership checks matter and duplicates are not needed."),
            ("What does O(n) space mean?", "Auxiliary memory grows linearly with input size."),
            ("Why mention a baseline?", "It demonstrates correctness-first reasoning and makes the optimization clear."),
        ],
        "practice": [
            "Solve one medium array or string problem in 30 minutes.",
            "Say time and space complexity aloud.",
            "Run at least four edge-case tests.",
        ],
        "code": None,
        "expected": "",
    },
    {
        "id": "D38",
        "area": "D4",
        "title": "Think Aloud Live Coding",
        "skill_item": "Timed live coding while thinking aloud",
        "level3": "Narrates approach, clarifies inputs, tests own code before declaring done",
        "subtopics": ["requirements", "narration", "incremental coding", "self-testing"],
        "def_intro": "In live coding, the interviewer evaluates the reasoning journey as much as the final <code>C#</code> solution.",
        "def_bullets": [
            "<b>Frame:</b> restate the task and ask focused questions.",
            "<b>Plan:</b> name the algorithm and data structures before typing.",
            "<b>Narrate:</b> explain decisions without describing every keystroke.",
            "<b>Verify:</b> trace examples and correct defects openly.",
        ],
        "interview": "I keep a short loop of clarify, plan, implement, and verify. If I discover an error, I explain the evidence, correct it, and rerun the relevant cases rather than hiding the change.",
        "table_headers": ["Phase", "What to say", "What to do"],
        "table_rows": [
            ["Clarify", "May input be null or empty?", "Record assumptions"],
            ["Plan", "I will use a dictionary for lookup", "Sketch the steps"],
            ["Verify", "Now I will test duplicates", "Trace or execute tests"],
        ],
        "mistakes": [("Narration gap", "Codes silently for ten minutes", "Explains meaningful decisions as they occur")],
        "quiz": [
            ("What should narration focus on?", "Assumptions, choices, tradeoffs, and verification."),
            ("Should every line be narrated?", "No; narrate reasoning, not keystrokes."),
            ("What should happen before declaring done?", "Run or trace representative and edge-case tests."),
        ],
        "practice": ["Record a 25-minute solution.", "Ask three clarifying questions.", "End with tests and complexity."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D39",
        "area": "D4",
        "title": "Prove the Bug Fix",
        "skill_item": "Debugging methodology: reproduce, isolate, fix, prove",
        "level3": "Tells a hard-bug story with the actual isolation steps, not just the fix",
        "subtopics": ["reproduction", "hypothesis testing", "isolation", "regression proof"],
        "def_intro": "A difficult bug becomes manageable when each observation narrows the fault until one testable cause remains.",
        "def_bullets": [
            "<b>Reproduce:</b> capture inputs, environment, timing, and symptoms.",
            "<b>Isolate:</b> compare healthy and failing paths and change one variable at a time.",
            "<b>Fix:</b> correct the root cause rather than masking the symptom.",
            "<b>Prove:</b> add a regression test and verify production signals.",
        ],
        "interview": "I describe the first reliable reproduction, the competing hypotheses, and the experiment that eliminated each one. I finish with the regression test and production evidence that proved both recovery and prevention.",
        "table_headers": ["Step", "Evidence", "Deliverable"],
        "table_rows": [
            ["Reproduce", "Same input fails consistently", "Minimal failing case"],
            ["Isolate", "One dependency changes outcome", "Confirmed cause"],
            ["Prove", "Regression test passes", "Durable safeguard"],
        ],
        "mistakes": [("Fix-only story", "Jumps directly to the code change", "Shows observations and isolation experiments")],
        "quiz": [
            ("Why create a minimal reproduction?", "It removes noise and makes hypotheses testable."),
            ("What distinguishes cause from correlation?", "A controlled experiment that changes the outcome."),
            ("How is a fix proved?", "With regression tests plus restored runtime signals."),
        ],
        "practice": ["Write a five-step hard-bug timeline.", "Name two rejected hypotheses.", "Identify the regression test."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D40",
        "area": "D4",
        "title": "Change Unfamiliar Code Safely",
        "skill_item": "Reading unfamiliar code and making safe changes",
        "level3": "Describes how they safely changed code they didn't write (tests, blast radius)",
        "subtopics": ["code archaeology", "characterization tests", "blast radius", "incremental delivery"],
        "def_intro": "When ownership history is missing, tests and runtime evidence become the map for a safe change.",
        "def_bullets": [
            "<b>Map:</b> trace entry points, dependencies, data flow, and callers.",
            "<b>Characterize:</b> lock current behavior with focused tests.",
            "<b>Limit:</b> keep the diff small and identify affected consumers.",
            "<b>Observe:</b> release gradually and watch relevant signals.",
        ],
        "interview": "I start by tracing the request path and finding tests, owners, and downstream consumers. I add characterization coverage, make the smallest coherent change, and use a staged rollout with a rollback path.",
        "table_headers": ["Risk", "Control", "Evidence"],
        "table_rows": [
            ["Unknown behavior", "Characterization test", "Current contract captured"],
            ["Wide impact", "Caller and dependency map", "Blast radius understood"],
            ["Release regression", "Feature flag or canary", "Fast rollback available"],
        ],
        "mistakes": [("Rewrite impulse", "Replaces code before understanding it", "Preserves behavior and changes incrementally")],
        "quiz": [
            ("What is a characterization test?", "A test that records existing behavior before modification."),
            ("What is blast radius?", "The users, components, and contracts a change can affect."),
            ("Why prefer a small diff?", "It is easier to review, test, diagnose, and roll back."),
        ],
        "practice": ["Trace one unfamiliar request end to end.", "List affected consumers.", "Design a rollback signal."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D41",
        "area": "D4",
        "title": "Reviews That Improve Design",
        "skill_item": "Git workflows, meaningful code review given and received",
        "level3": "Gives an example of review feedback they gave that changed a design",
        "subtopics": ["branch hygiene", "review intent", "design feedback", "feedback response"],
        "def_intro": "A valuable review protects correctness and maintainability while helping the author improve the design.",
        "def_bullets": [
            "<b>Prepare:</b> keep commits focused and explain intent and test evidence.",
            "<b>Review:</b> prioritize correctness, contracts, security, and operability.",
            "<b>Communicate:</b> label blockers, suggestions, and questions clearly.",
            "<b>Respond:</b> test feedback objectively and document the outcome.",
        ],
        "interview": "I once challenged a synchronous cross-service call because it coupled availability and latency across both services. We changed the design to publish an idempotent event, added failure handling, and validated the new operational tradeoffs.",
        "table_headers": ["Feedback type", "Example", "Expected action"],
        "table_rows": [
            ["Blocker", "Authorization can be bypassed", "Fix before merge"],
            ["Design question", "Could this dependency be inverted?", "Discuss with evidence"],
            ["Suggestion", "Rename for domain clarity", "Optional improvement"],
        ],
        "mistakes": [("Style-only review", "Comments only on formatting", "Prioritizes behavior, design, and risk")],
        "quiz": [
            ("What makes review feedback meaningful?", "It identifies impact and proposes or invites a better design."),
            ("Why label comment severity?", "The author knows what blocks approval."),
            ("How should received feedback be handled?", "Evaluate it with evidence, respond respectfully, and record the decision."),
        ],
        "practice": ["Prepare one design-changing review story.", "Explain the before and after.", "Quantify the risk reduced."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D42",
        "area": "D4",
        "title": "Refactor Without Missing Deadlines",
        "skill_item": "Refactoring patterns and keeping code clean under deadline pressure",
        "level3": "Names a refactor they drove and how they de-risked it",
        "subtopics": ["seams", "incremental refactoring", "test safety", "technical debt"],
        "def_intro": "Under deadline pressure, disciplined refactoring creates a narrow safe path instead of a risky rewrite.",
        "def_bullets": [
            "<b>Target:</b> tie the refactor to a concrete delivery or reliability need.",
            "<b>Protect:</b> add tests around behavior before moving structure.",
            "<b>Slice:</b> use small, independently releasable steps.",
            "<b>Measure:</b> confirm behavior, performance, and defect rates remain healthy.",
        ],
        "interview": "I extracted payment-provider logic behind an interface so a new provider could be added without branching through the core workflow. Characterization tests, adapter-by-adapter migration, and a feature flag kept the release reversible.",
        "table_headers": ["Pattern", "Use when", "Safety mechanism"],
        "table_rows": [
            ["Extract method", "Logic hides intent", "Unit tests"],
            ["Introduce interface", "Dependency blocks change", "Contract tests"],
            ["Strangler migration", "Large component must evolve", "Incremental routing"],
        ],
        "mistakes": [("Big-bang cleanup", "Mixes a rewrite with urgent delivery", "Creates tested seams and migrates in slices")],
        "quiz": [
            ("What makes refactoring different from feature work?", "It changes structure while preserving observable behavior."),
            ("Why create a seam?", "It isolates change and enables focused testing."),
            ("How can deadline pressure be handled?", "Limit scope to the refactor needed for safe delivery."),
        ],
        "practice": ["Choose one refactor story.", "Name its safety net.", "Explain why the chosen slice was reversible."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D43",
        "area": "D4",
        "title": "Build Trustworthy Delivery Pipelines",
        "skill_item": "CI/CD pipelines: stages, quality gates, what breaks builds",
        "level3": "Explains their project's pipeline and a gate they added or fixed",
        "subtopics": ["pipeline stages", "quality gates", "artifacts", "deployment controls"],
        "def_intro": "A delivery pipeline turns every commit into repeatable evidence that the same artifact is safe to release.",
        "def_bullets": [
            "<b>Build:</b> compile once and create an immutable versioned artifact.",
            "<b>Verify:</b> run tests, security scans, and policy checks.",
            "<b>Promote:</b> move the same artifact through environments.",
            "<b>Release:</b> use approvals, health checks, and rollback automation.",
        ],
        "interview": "Our pipeline restored and built the solution, ran unit and integration tests, scanned dependencies, published a container, and promoted it through environments. I added a contract-test gate after an incompatible API change reached staging, which shifted detection to pull requests.",
        "table_headers": ["Stage", "Gate", "Failure meaning"],
        "table_rows": [
            ["Build", "Warnings policy", "Code does not meet compile standard"],
            ["Test", "Required suites pass", "Behavior is not proven"],
            ["Deploy", "Health check succeeds", "New version is unhealthy"],
        ],
        "mistakes": [("Environment rebuild", "Builds a different artifact per stage", "Promotes one immutable artifact")],
        "quiz": [
            ("What should break a build?", "A failed mandatory check tied to an agreed quality standard."),
            ("Why promote the same artifact?", "It removes build differences between tested and released code."),
            ("What is a useful deployment gate?", "A measurable health or compatibility check."),
        ],
        "practice": ["Draw your current pipeline.", "Name one gate you changed.", "Explain rollback and artifact promotion."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D44",
        "area": "D4",
        "title": "Lead Production Incident Recovery",
        "skill_item": "Production incident handling with logs, metrics, traces",
        "level3": "Walks an incident they handled: detection to resolution to prevention",
        "subtopics": ["triage", "telemetry correlation", "mitigation", "post-incident learning"],
        "def_intro": "During an incident, restore service first, preserve evidence, and turn the timeline into prevention afterward.",
        "def_bullets": [
            "<b>Detect:</b> confirm user impact and establish severity.",
            "<b>Correlate:</b> connect metrics, structured logs, traces, and recent changes.",
            "<b>Mitigate:</b> roll back, disable, scale, or degrade safely.",
            "<b>Prevent:</b> fix the cause and improve detection and runbooks.",
        ],
        "interview": "An alert showed checkout latency and error rate rising immediately after a release, and traces isolated the delay to a downstream pricing call. I rolled back to restore service, then added a timeout, fallback, dependency dashboard, and regression load test.",
        "table_headers": ["Signal", "Question answered", "Example"],
        "table_rows": [
            ["Metric", "How widespread is it?", "Error rate by endpoint"],
            ["Log", "What context accompanied failure?", "Order and correlation IDs"],
            ["Trace", "Where was time spent?", "Slow dependency span"],
        ],
        "mistakes": [("Debug before mitigation", "Keeps investigating while impact grows", "Restores service using the safest reversible action")],
        "quiz": [
            ("What is the first incident priority?", "Protect users and restore service safely."),
            ("Why correlate telemetry?", "Each signal answers a different part of the failure story."),
            ("What closes an incident well?", "Root-cause work, prevention, ownership, and verified follow-up."),
        ],
        "practice": ["Prepare a minute-by-minute incident story.", "Separate mitigation from root-cause fix.", "Name one prevention metric."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D45",
        "area": "D5",
        "title": "Design Durable API Contracts",
        "skill_item": "API design: idempotency, pagination, versioning, error contracts",
        "level3": "Defends API decisions from a service they own; knows what breaks clients",
        "subtopics": ["idempotency", "pagination", "versioning", "problem details"],
        "def_intro": "An API is a long-lived promise: retries, growth, errors, and client evolution must be designed before production exposes them.",
        "def_bullets": [
            "<b>Retry safely:</b> use idempotency keys for repeatable writes.",
            "<b>Bound reads:</b> paginate stable ordered collections.",
            "<b>Evolve:</b> prefer additive changes and version breaking contracts deliberately.",
            "<b>Standardize:</b> return machine-readable error codes and trace identifiers.",
        ],
        "interview": "For order creation, I used an idempotency key so client retries returned the original result instead of creating duplicates. Cursor pagination handled a growing dataset, while a stable problem-details contract let clients distinguish validation, conflict, and transient errors.",
        "table_headers": ["Concern", "Decision", "Client impact"],
        "table_rows": [
            ["Retries", "Idempotency key", "No duplicate operation"],
            ["Large results", "Cursor pagination", "Stable bounded reads"],
            ["Errors", "Typed error contract", "Predictable handling"],
        ],
        "mistakes": [("Breaking evolution", "Renames or removes a response field", "Adds fields or introduces a versioned contract")],
        "quiz": [
            ("What makes a write idempotent?", "Repeating the same logical request has the same intended effect."),
            ("Why can offset pagination drift?", "Concurrent inserts or deletes move row positions."),
            ("What commonly breaks clients?", "Removing fields, changing types or semantics, and altering status behavior."),
        ],
        "practice": ["Defend one API you owned.", "List its breaking changes.", "Explain retry and error behavior."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D46",
        "area": "D5",
        "title": "Draw Boundaries That Last",
        "skill_item": "Service/component design: layering, boundaries, dependency direction",
        "level3": "Sketches their service's structure and justifies each boundary",
        "subtopics": ["layers", "domain boundaries", "dependency inversion", "adapters"],
        "def_intro": "A maintainable service keeps business decisions inward and replaceable infrastructure details at the edges.",
        "def_bullets": [
            "<b>API:</b> translate transport concerns into application requests.",
            "<b>Application:</b> coordinate use cases and transaction boundaries.",
            "<b>Domain:</b> own business rules without infrastructure dependencies.",
            "<b>Infrastructure:</b> implement persistence and external adapters.",
        ],
        "interview": "I structure services so controllers depend on application use cases, use cases depend on domain abstractions, and infrastructure implements those abstractions. This lets business rules be tested without a database and keeps transport or vendor changes at the edge.",
        "table_headers": ["Boundary", "Owns", "Must not own"],
        "table_rows": [
            ["API", "HTTP mapping", "Business policy"],
            ["Domain", "Rules and invariants", "Database SDK calls"],
            ["Infrastructure", "External implementations", "Use-case orchestration"],
        ],
        "mistakes": [("Layer leakage", "Controller queries the database directly", "Controller delegates to an application use case")],
        "quiz": [
            ("Where should dependencies point?", "Toward stable business policy."),
            ("Why isolate infrastructure?", "Technology changes stay local and core logic remains testable."),
            ("What justifies a boundary?", "Different responsibilities, change rates, or ownership constraints."),
        ],
        "practice": ["Sketch one service in four boxes.", "Draw dependency arrows.", "Justify each boundary with a change scenario."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D47",
        "area": "D5",
        "title": "Scale Stateless Services Horizontally",
        "skill_item": "Distributed basics: statelessness, horizontal scaling, load balancing",
        "level3": "Explains what made their service scalable (or what blocked it)",
        "subtopics": ["statelessness", "load balancing", "shared state", "autoscaling"],
        "def_intro": "Horizontal scaling works when any healthy instance can handle the next request without hidden local state.",
        "def_bullets": [
            "<b>Externalize:</b> keep durable session and workflow state in shared systems.",
            "<b>Balance:</b> route traffic only to healthy instances.",
            "<b>Scale:</b> add instances using demand and saturation signals.",
            "<b>Constrain:</b> account for database, connection, and dependency limits.",
        ],
        "interview": "We removed in-memory session affinity, stored shared state externally, and made request handlers idempotent so any instance could serve a retry. CPU-based scaling helped until database connections became the bottleneck, so we bounded pools and reduced query cost.",
        "table_headers": ["Mechanism", "Benefit", "Limit"],
        "table_rows": [
            ["Stateless handlers", "Instance interchangeability", "External state latency"],
            ["Load balancer", "Traffic distribution", "Health-check quality"],
            ["Autoscaling", "Elastic capacity", "Downstream saturation"],
        ],
        "mistakes": [("Scale assumption", "Adds instances without checking dependencies", "Models the whole request path and shared limits")],
        "quiz": [
            ("Why avoid sticky sessions?", "They reduce flexibility and make failures or rebalancing harder."),
            ("What can block horizontal scale?", "Shared databases, locks, connection limits, or local state."),
            ("What should drive scaling?", "Demand and saturation signals tied to service behavior."),
        ],
        "practice": ["Name your service's local state.", "Identify its first shared bottleneck.", "Explain one scaling signal."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D48",
        "area": "D5",
        "title": "Cache Without Serving Surprises",
        "skill_item": "Caching architecture: layers, invalidation, consistency",
        "level3": "Describes a cache they added: what was cached, TTL vs event invalidation, staleness handling",
        "subtopics": ["cache-aside", "TTL", "event invalidation", "stampede control"],
        "def_intro": "A cache is a deliberate consistency trade: every fast read needs an explicit freshness and failure policy.",
        "def_bullets": [
            "<b>Select:</b> cache expensive, frequent, reusable reads.",
            "<b>Expire:</b> choose TTL from acceptable staleness and update frequency.",
            "<b>Invalidate:</b> use events when important changes must propagate quickly.",
            "<b>Protect:</b> handle misses, stampedes, and cache outages.",
        ],
        "interview": "I cached product configuration with cache-aside because reads dominated and brief staleness was acceptable. A ten-minute TTL provided recovery from missed events, update events evicted hot keys, and single-flight loading prevented a miss storm.",
        "table_headers": ["Policy", "Best fit", "Tradeoff"],
        "table_rows": [
            ["TTL only", "Bounded staleness accepted", "Changes remain stale temporarily"],
            ["Event invalidation", "Fast freshness needed", "Events may be delayed or lost"],
            ["Cache-aside", "Read-heavy access", "First request pays miss cost"],
        ],
        "mistakes": [("Permanent cache", "Caches without expiry or invalidation", "Defines freshness, eviction, and outage behavior")],
        "quiz": [
            ("How should TTL be chosen?", "From tolerated staleness, update rate, and origin load."),
            ("What is a cache stampede?", "Many callers rebuild the same expired value simultaneously."),
            ("Should cache failure break the service?", "Usually no; use a bounded fallback to the source when safe."),
        ],
        "practice": ["Describe one cached value.", "Defend its TTL.", "Explain invalidation and outage behavior."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D49",
        "area": "D5",
        "title": "Make Messaging Fail Safely",
        "skill_item": "Async & messaging patterns: queues, pub/sub, retries, idempotency, DLQ",
        "level3": "Explains a real async flow incl. what happens on consumer failure",
        "subtopics": ["queues and pub/sub", "retries", "idempotent consumers", "dead-letter queues"],
        "def_intro": "Reliable messaging assumes duplicates, delays, reordering, and poison messages are normal operating conditions.",
        "def_bullets": [
            "<b>Choose:</b> use a queue for work distribution and pub/sub for independent reactions.",
            "<b>Retry:</b> back off transient failures with a strict attempt limit.",
            "<b>Deduplicate:</b> make consumers idempotent using stable message identity.",
            "<b>Quarantine:</b> send persistent failures to a monitored DLQ.",
        ],
        "interview": "Order creation wrote an outbox record in the same transaction, then a publisher delivered the event to independent inventory and notification consumers. A failed consumer retried with backoff, ignored already processed message IDs, and moved poison messages to a DLQ with an alert and replay runbook.",
        "table_headers": ["Failure", "Control", "Outcome"],
        "table_rows": [
            ["Transient dependency", "Bounded retry with jitter", "Later recovery"],
            ["Duplicate delivery", "Idempotency record", "One logical effect"],
            ["Poison message", "DLQ and alert", "Flow continues safely"],
        ],
        "mistakes": [("Infinite retries", "Retries poison messages forever", "Bounds retries and quarantines failures")],
        "quiz": [
            ("Why must consumers be idempotent?", "Most brokers provide at-least-once delivery, so duplicates can occur."),
            ("What belongs in a DLQ process?", "Alerting, diagnosis, correction, and controlled replay."),
            ("What does an outbox solve?", "Atomic recording of business change and intent to publish."),
        ],
        "practice": ["Draw a real message path.", "Explain every consumer failure state.", "Describe deduplication and replay."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D50",
        "area": "D5",
        "title": "Contain Failures by Design",
        "skill_item": "Resilience: timeouts, circuit breakers, bulkheads, graceful degradation",
        "level3": "Names the failure modes their service survives and how each is handled",
        "subtopics": ["timeouts", "circuit breakers", "bulkheads", "fallbacks"],
        "def_intro": "Resilience is not retrying everything; it is bounding damage and preserving the most valuable service behavior.",
        "def_bullets": [
            "<b>Timeout:</b> stop waiting before the caller's budget expires.",
            "<b>Break:</b> pause calls to a dependency that is predictably failing.",
            "<b>Isolate:</b> reserve concurrency so one dependency cannot exhaust all capacity.",
            "<b>Degrade:</b> return a safe reduced experience when possible.",
        ],
        "interview": "Our catalog service survived slow recommendations by timing out within the request budget and falling back to a page without personalization. A circuit breaker reduced pressure during sustained failures, while a separate concurrency pool prevented that dependency from consuming all request threads.",
        "table_headers": ["Failure mode", "Pattern", "Result"],
        "table_rows": [
            ["Slow dependency", "Timeout", "Latency remains bounded"],
            ["Repeated failure", "Circuit breaker", "Load is shed"],
            ["Resource exhaustion", "Bulkhead", "Other features stay healthy"],
        ],
        "mistakes": [("Retry amplification", "Retries without budgets or limits", "Retries only transient failures within an end-to-end budget")],
        "quiz": [
            ("What sets a timeout?", "The caller's end-to-end latency budget and dependency behavior."),
            ("What does a circuit breaker protect?", "Both the caller and the failing dependency from repeated work."),
            ("What is graceful degradation?", "Serving reduced but safe functionality instead of total failure."),
        ],
        "practice": ["List three service failure modes.", "Map each to a control.", "Name one safe degraded response."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D51",
        "area": "D5",
        "title": "Turn NFRs Into Numbers",
        "skill_item": "NFRs as numbers: availability, latency, throughput targets",
        "level3": "States actual SLO-type targets from a project and how they were verified",
        "subtopics": ["SLIs and SLOs", "percentile latency", "throughput", "error budgets"],
        "def_intro": "A non-functional requirement becomes actionable only when it names a signal, target, scope, and measurement window.",
        "def_bullets": [
            "<b>Availability:</b> define successful eligible requests over a time window.",
            "<b>Latency:</b> use percentiles, not averages, for user experience.",
            "<b>Throughput:</b> state sustained and peak load expectations.",
            "<b>Verify:</b> combine production telemetry with representative load tests.",
        ],
        "interview": "Our checkout SLO was 99.95% successful eligible requests monthly, p95 latency below 400 ms, and 250 requests per second sustained with twice that burst capacity. Dashboards tracked the production SLIs, while pre-release load tests and error-budget alerts verified readiness and ongoing compliance.",
        "table_headers": ["NFR", "Example target", "Verification"],
        "table_rows": [
            ["Availability", "99.95% monthly", "Success-ratio SLI"],
            ["Latency", "p95 under 400 ms", "Histogram dashboard"],
            ["Throughput", "250 RPS sustained", "Load test and production rate"],
        ],
        "mistakes": [("Vague NFR", "Says the API must be fast", "Defines percentile, threshold, workload, and window")],
        "quiz": [
            ("Why use p95 latency?", "It exposes slower user experiences hidden by an average."),
            ("What is an SLI?", "A measured indicator of service behavior."),
            ("What is an error budget?", "The allowed unreliability implied by an SLO."),
        ],
        "practice": ["State three real targets.", "Define each measurement window.", "Explain how each was verified."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D52",
        "area": "D5",
        "title": "Estimate Capacity Before Scaling",
        "skill_item": "Scalability analysis: bottleneck identification, capacity estimation",
        "level3": "Does a rough capacity estimate live (users -> RPS -> instances) and explains the assumptions used",
        "subtopics": ["traffic model", "RPS estimation", "instance capacity", "bottlenecks"],
        "def_intro": "A useful capacity estimate makes assumptions visible, converts demand into load, and checks every constrained dependency.",
        "def_bullets": [
            "<b>Demand:</b> estimate active users and actions per interval.",
            "<b>Peak:</b> apply a measured or explicit peak-to-average factor.",
            "<b>Supply:</b> use tested safe throughput per instance.",
            "<b>Headroom:</b> include failures, growth, and downstream limits.",
        ],
        "interview": "If 120,000 daily users each make six calls, with 20% concentrated in a peak hour, that is about 40 RPS before burst headroom. At a tested safe 25 RPS per instance, I would start with three instances for redundancy and margin, then verify database connections and queue throughput.",
        "table_headers": ["Input", "Assumption", "Derived value"],
        "table_rows": [
            ["Daily users", "120,000", "Demand base"],
            ["Peak share", "20% in one hour", "About 40 RPS"],
            ["Instance capacity", "25 safe RPS", "Three instances with margin"],
        ],
        "mistakes": [("False precision", "Presents guessed inputs as exact", "States assumptions and gives a defensible range")],
        "quiz": [
            ("How do users become RPS?", "Multiply users by actions in the interval and divide by its seconds."),
            ("Why use safe instance capacity?", "Benchmark maximums leave no operating headroom."),
            ("What follows instance sizing?", "Validate downstream limits and measure in production."),
        ],
        "practice": ["Estimate users to peak RPS.", "Calculate instances with headroom.", "Name the likely next bottleneck."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D53",
        "area": "D5",
        "title": "Map Threats to Controls",
        "skill_item": "Security architecture: OWASP top 10, secrets handling, data protection",
        "level3": "Maps 3+ OWASP risks to concrete mitigations in their own project",
        "subtopics": ["OWASP risks", "authorization", "secrets", "data protection"],
        "def_intro": "Security architecture connects concrete threats in a real request path to preventive, detective, and recovery controls.",
        "def_bullets": [
            "<b>Authorize:</b> enforce object and action permissions server-side.",
            "<b>Validate:</b> use parameterized access and constrained input handling.",
            "<b>Protect:</b> encrypt sensitive data and minimize its retention.",
            "<b>Manage:</b> store secrets in a vault, rotate them, and avoid logs.",
        ],
        "interview": "In our project, broken access control was mitigated with resource-level authorization, injection with parameterized queries, and security misconfiguration with hardened deployment templates and automated scans. Secrets came from managed identity and a vault, while sensitive fields were encrypted and redacted from logs.",
        "table_headers": ["Risk", "Concrete control", "Verification"],
        "table_rows": [
            ["Broken access control", "Resource authorization policy", "Negative authorization tests"],
            ["Injection", "Parameterized queries", "SAST and integration tests"],
            ["Security misconfiguration", "Hardened templates", "Configuration scanning"],
            ["Sensitive data exposure", "Encryption and redaction", "Log and access audits"],
        ],
        "mistakes": [("Checklist security", "Names OWASP categories only", "Maps each relevant threat to code, platform, and verification controls")],
        "quiz": [
            ("Where should authorization be enforced?", "At the trusted server boundary for every protected resource and action."),
            ("Why use managed identity?", "It reduces stored credentials and supports controlled access."),
            ("Is encryption enough for sensitive data?", "No; minimize collection, restrict access, redact, rotate, and audit."),
        ],
        "practice": ["Map three OWASP risks to your project.", "Explain secret rotation.", "Name a verification test for each control."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D54",
        "area": "D5",
        "title": "Observe What Users Experience",
        "skill_item": "Observability strategy: what to log/measure/trace and why",
        "level3": "Describes dashboards/alerts they built and one they'd add tomorrow",
        "subtopics": ["structured logs", "service metrics", "distributed traces", "actionable alerts"],
        "def_intro": "Observability starts with user and operator questions, then instruments the smallest signals that answer them.",
        "def_bullets": [
            "<b>Log:</b> record structured decision and failure context without secrets.",
            "<b>Measure:</b> track traffic, errors, latency, and saturation.",
            "<b>Trace:</b> follow sampled requests across service boundaries.",
            "<b>Alert:</b> page on actionable symptoms tied to user impact.",
        ],
        "interview": "I built a dashboard for request rate, error ratio, p50/p95/p99 latency, dependency health, and queue depth, all filterable by service version. Alerts used sustained SLO burn rather than single spikes; tomorrow I would add an alert for oldest queued message because depth alone can hide stuck work.",
        "table_headers": ["Signal", "Best question", "Example"],
        "table_rows": [
            ["Logs", "Why did this request fail?", "Structured error context"],
            ["Metrics", "How many users are affected?", "Error ratio and latency"],
            ["Traces", "Which hop is slow?", "Dependency span duration"],
        ],
        "mistakes": [("Noisy alert", "Pages on every isolated error", "Alerts on sustained actionable user impact")],
        "quiz": [
            ("What are core service signals?", "Traffic, errors, latency, and saturation."),
            ("Why use structured logs?", "Fields can be searched, aggregated, and correlated reliably."),
            ("What makes an alert actionable?", "It identifies meaningful impact and has a clear response path."),
        ],
        "practice": ["Describe one dashboard you built.", "Explain one alert threshold.", "Name one missing signal and why it matters."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D55",
        "area": "D5",
        "title": "Explain Architecture Tradeoffs Clearly",
        "skill_item": "Tradeoff articulation: consistency models, CAP in practice, cost vs performance",
        "level3": "Frames a real decision as 'we accepted X to gain Y'; adapts when constraint changes",
        "subtopics": ["consistency", "availability", "latency", "cost"],
        "def_intro": "A credible architecture decision names the constraint, alternatives, benefit gained, cost accepted, and trigger to revisit.",
        "def_bullets": [
            "<b>Frame:</b> state the decision and the dominant constraint.",
            "<b>Compare:</b> evaluate realistic alternatives using the same criteria.",
            "<b>Accept:</b> make the downside and mitigation explicit.",
            "<b>Adapt:</b> explain what changed constraint would reverse the choice.",
        ],
        "interview": "We accepted up to two minutes of stale search results to gain lower read latency and isolate search availability from the source database. If inventory correctness became part of that response, I would keep authoritative stock on a strongly consistent path and use search only for discovery.",
        "table_headers": ["Choice", "Gain", "Accepted cost"],
        "table_rows": [
            ["Asynchronous index", "Fast resilient reads", "Temporary staleness"],
            ["Strong write path", "Correct inventory", "Higher latency"],
            ["More instances", "Lower saturation risk", "Higher infrastructure cost"],
        ],
        "mistakes": [("Absolute claim", "Calls one architecture always best", "Ties the choice to constraints and revisit triggers")],
        "quiz": [
            ("What is a tradeoff statement?", "We accepted X to gain Y under constraint Z."),
            ("How does CAP apply in practice?", "During a network partition, a distributed operation cannot guarantee both availability and strong consistency."),
            ("When should a decision be revisited?", "When assumptions, constraints, scale, or measured outcomes change."),
        ],
        "practice": ["Prepare one accepted-X-to-gain-Y story.", "Name two alternatives.", "Change one constraint and adapt the decision."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D56",
        "area": "D5",
        "title": "Defend Designs With Evidence",
        "skill_item": "Documenting and defending designs (ADRs, design reviews)",
        "level3": "Has written/presented a design that was challenged, and can replay the debate",
        "subtopics": ["ADRs", "design proposals", "review debate", "decision records"],
        "def_intro": "A design document makes assumptions and tradeoffs reviewable before code makes them expensive.",
        "def_bullets": [
            "<b>Context:</b> define the problem, scope, constraints, and success measures.",
            "<b>Options:</b> compare alternatives with evidence and operational impact.",
            "<b>Decision:</b> record the choice, consequences, owners, and status.",
            "<b>Challenge:</b> capture objections and how evidence changed the design.",
        ],
        "interview": "I presented a proposal for asynchronous invoice generation, and reviewers challenged delivery guarantees and supportability. We added an outbox, idempotent consumer, DLQ ownership, and reconciliation metric; the ADR recorded why this complexity was justified over a synchronous timeout-prone flow.",
        "table_headers": ["Section", "Question answered", "Evidence"],
        "table_rows": [
            ["Context", "Why act now?", "Failure and demand data"],
            ["Options", "What else could work?", "Common comparison criteria"],
            ["Decision", "What did we accept?", "Consequences and mitigations"],
        ],
        "mistakes": [("Decision theater", "Documents only the preferred option", "Shows credible alternatives and consequences")],
        "quiz": [
            ("What should an ADR preserve?", "Decision context, alternatives, choice, and consequences."),
            ("Why replay objections?", "It proves the design survived meaningful scrutiny."),
            ("When should an ADR change?", "Supersede it when a later decision changes the architecture."),
        ],
        "practice": ["Select one challenged design.", "Replay the strongest objection.", "Explain what changed and why."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D57",
        "area": "D6",
        "title": "Tell Your Project Story",
        "skill_item": "2-3 project STAR narratives: what YOU built, why, and the outcome",
        "level3": "Two-minute tight story per project; 'I' not 'we'; answers follow-up questions with clear rationale",
        "subtopics": ["STAR structure", "personal ownership", "technical rationale", "outcomes"],
        "def_intro": "A strong project narrative lets the interviewer see your decisions, actions, and measurable contribution in two focused minutes.",
        "def_bullets": [
            "<b>Situation:</b> set only the context needed to understand the stakes.",
            "<b>Task:</b> state your ownership and success criteria.",
            "<b>Action:</b> explain your decisions, implementation, and tradeoffs.",
            "<b>Result:</b> give measured outcomes and learning.",
        ],
        "interview": "I owned the redesign of our claims intake API after peak traffic caused timeouts and manual retries. I profiled the path, moved document processing behind an idempotent queue, added SLO dashboards, and reduced p95 latency from 2.4 seconds to 380 milliseconds while supporting three times the volume.",
        "table_headers": ["STAR part", "Time", "Focus"],
        "table_rows": [
            ["Situation and task", "25 seconds", "Stakes and ownership"],
            ["Action", "70 seconds", "Your choices and execution"],
            ["Result", "25 seconds", "Numbers and learning"],
        ],
        "mistakes": [("Team-only story", "Says we throughout", "Credits the team while naming personal decisions and work")],
        "quiz": [
            ("Which STAR section deserves most time?", "Action, because it reveals your capability and rationale."),
            ("How many project stories should be ready?", "Two or three distinct, adaptable stories."),
            ("What strengthens follow-up answers?", "Clear alternatives, constraints, evidence, and personal reasoning."),
        ],
        "practice": ["Write three two-minute STAR stories.", "Replace vague we statements with precise ownership.", "Prepare five follow-up answers per story."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D58",
        "area": "D6",
        "title": "Own Failure and Improve",
        "skill_item": "A failure story: a production issue you owned end to end",
        "level3": "Owns the mistake or gap honestly and lands on what changed after",
        "subtopics": ["accountability", "incident ownership", "learning", "systemic prevention"],
        "def_intro": "A mature failure story is specific about your gap, responsible during recovery, and durable about what changed afterward.",
        "def_bullets": [
            "<b>Own:</b> name your decision or omission without blame shifting.",
            "<b>Respond:</b> explain how you contained impact and communicated.",
            "<b>Learn:</b> identify why existing safeguards failed.",
            "<b>Change:</b> show verified process and technical prevention.",
        ],
        "interview": "I approved a configuration change without a representative load test, and it exhausted the database connection pool during peak traffic. I led rollback and recovery, then added a performance gate, pool-saturation alert, canary rollout, and runbook; later releases stayed within the new limits.",
        "table_headers": ["Story beat", "Strong signal", "Weak signal"],
        "table_rows": [
            ["Ownership", "Names personal gap", "Blames another team"],
            ["Recovery", "Protects users first", "Focuses on appearing right"],
            ["Learning", "Changes the system", "Promises to be careful"],
        ],
        "mistakes": [("Safe fake failure", "Uses perfectionism as the mistake", "Chooses a real gap with bounded impact and concrete learning")],
        "quiz": [
            ("What makes a failure story credible?", "Specific ownership, impact, response, and verified change."),
            ("Should teammates be blamed?", "No; explain system context while owning your part."),
            ("What is stronger than 'I became careful'?", "A durable control such as a test, gate, alert, or process change."),
        ],
        "practice": ["Choose a real production failure.", "State your gap in one sentence.", "List technical and process changes that followed."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D59",
        "area": "D6",
        "title": "Tell a Decision Story",
        "skill_item": "A decision story: a technical choice you made and its tradeoffs",
        "level3": "Names alternatives considered and why they lost",
        "subtopics": ["decision criteria", "alternatives", "tradeoffs", "validation"],
        "def_intro": "A decision story demonstrates judgment by showing how constraints and evidence eliminated credible alternatives.",
        "def_bullets": [
            "<b>Constraint:</b> define the outcome and non-negotiable limits.",
            "<b>Alternatives:</b> name at least two realistic choices.",
            "<b>Decision:</b> compare them against explicit criteria.",
            "<b>Validate:</b> report the measured result and revisit trigger.",
        ],
        "interview": "I chose PostgreSQL for a new order workflow over a document store and event-only persistence because transactions, relational reporting, and team operating experience dominated the decision. We accepted schema migration work, validated throughput with load tests, and documented when partitioning or a separate read model would become necessary.",
        "table_headers": ["Alternative", "Why considered", "Why it lost"],
        "table_rows": [
            ["PostgreSQL", "Transactions and reporting", "Selected"],
            ["Document store", "Flexible records", "Weaker fit for relational queries"],
            ["Event-only store", "Complete history", "Operational complexity exceeded need"],
        ],
        "mistakes": [("Predetermined choice", "Lists alternatives after deciding", "Uses explicit criteria and evidence to compare them")],
        "quiz": [
            ("How many alternatives make a useful story?", "Usually two or three credible options."),
            ("What should comparison criteria come from?", "Business goals, technical constraints, risk, cost, and operations."),
            ("How should the chosen option be described?", "With both its advantage and accepted downside."),
        ],
        "practice": ["Choose one consequential decision.", "List two rejected alternatives.", "Explain criteria, outcome, and revisit trigger."],
        "code": None,
        "expected": "",
    },
    {
        "id": "D60",
        "area": "D6",
        "title": "Prove Impact With Numbers",
        "skill_item": "Quantified impact: numbers for scale, performance, or business outcome",
        "level3": "Gives at least 2 real numbers (latency, volume, cost, revenue) without prompting",
        "subtopics": ["baselines", "performance", "scale", "business outcomes"],
        "def_intro": "Numbers turn an activity claim into evidence by showing the baseline, measured change, and business meaning.",
        "def_bullets": [
            "<b>Baseline:</b> state the starting metric and measurement window.",
            "<b>Change:</b> quantify the technical or operational improvement.",
            "<b>Scale:</b> include traffic, data, users, or transaction volume.",
            "<b>Meaning:</b> connect the result to cost, risk, revenue, or experience.",
        ],
        "interview": "I reduced checkout p95 latency from 1.8 seconds to 420 milliseconds at a peak of 600 requests per second. The change cut compute cost by 28% and reduced timeout-related support tickets from about 90 to 15 per month.",
        "table_headers": ["Metric type", "Before", "After"],
        "table_rows": [
            ["p95 latency", "1.8 seconds", "420 milliseconds"],
            ["Compute cost", "Baseline", "28% lower"],
            ["Support tickets", "90 per month", "15 per month"],
        ],
        "mistakes": [
            ("Number-free impact", "Says performance improved significantly", "States baseline, result, scale, and measurement"),
            ("Unowned metric", "Claims a team-wide result without attribution", "Explains personal contribution and other factors"),
        ],
        "quiz": [
            ("Why include a baseline?", "A result has no magnitude without a starting point."),
            ("Which two number types strengthen a story?", "A technical measure and a user, business, cost, or scale measure."),
            ("How should uncertain attribution be handled?", "State the measured correlation and your contribution without overclaiming causation."),
        ],
        "practice": ["Add two real numbers to every STAR story.", "Record sources and measurement windows.", "Connect each metric to business or user impact."],
        "code": None,
        "expected": "",
    },
]
